### ISSUE TITLE
Working with IDs

### ISSUE THREAD

**Issue by loelkes** [msiemens/tinydb#101]
Hi,
i want to get all the elements in the database with their eid. After reading the docs i figured out that the only way is to get alle the field and run a loop to get the eid for each field. 
Is there any way to get the eids with .all() or a similar function? Why is the eid hidden if i call .all()?

It's a cosmetic thing. I don't understand why .all() does not provide ALL the informations...
```
everything = db.all()
for item in everything:
    entry = db.get(Query().name == item['name']) # ?? How do i get all eids without this line ??
    print(str(entry.eid) + " " + item['name'])
```
This is a simple example and should fail as soon as i have identical name fields. So not really a solution. Please help :)
I use Python 3.5.1 with TinyDB 3.2.0

Thanks

**Comment by eugene-eeo** [comment]
Note that the documents returned by ``db.get`` and ``db.all`` are the same thing:

```python
>>> from tinydb import TinyDB, where
>>> db = TinyDB('./.d')
>>> db.insert({'int': 1, 'char': 'a'})
1
>>> db.insert({'int': 1, 'char': 'b'})
2
>>> [e.eid for e in db.all()]
[1, 2]
```

**Comment by loelkes** [comment]
Thank you for the quick answer. It's so simple i feel stupid.

**Comment by msiemens** [comment]
@loelkes Seems like the documentation didn't make it clear that all elements returend from TinyDB have the `.eid` attribute, is that right? In that case I'd consider that to be a documentation bug.

**Comment by loelkes** [comment]
Yes, this is not clear. 
I think this is misleading:
> Different TinyDB methods also work with IDs, namely: update, remove, contains and get.

**Comment by msiemens** [comment]
I've now updated the docs accordingly. Hope it's better now.
