### ISSUE TITLE
Inconsistency with purge functions

### ISSUE THREAD

**Issue by neRok00** [msiemens/tinydb#103]
The way I see it at the moment, the database contains tables, and tables contain elements.

With the functions `database.purge_table(name)` and `database.purge_tables()`, it is evident from their names that they act upon the 'children' of the 'parent'. If this same logic were applied to deleting elements from a table, wouldn't `table.purge_element(element)` and `table.purge_elements()` be more appropriate?

To me, the current `table.purge()` implies you are going to purge the table itself, which means it would have the same functionality as `database.purge_table(name)` (which it doesn't). The google-supplied definition of purge is "remove (something) completely", which agrees with my thoughts here (purge the table object).

If you agree there is an inconsistency, then I think there are 2 ways to fix it;
1. Have the 4 complimentary functions `database.purge_table(name)`,  `database.purge_tables()`, `table.purge_element(element)` and `table.purge_elements()`. This option gives a very precise meaning to the functions.
2. Have a `database.purge()` and keep `table.purge()`. Whilst this option gives simple function names, they don't really agree with the definition of purge, and thus I think this option can be discounted.
3. Similar to option 2, but make the functions have targets, so `database.purge(table)` and `table.purge(element)`. For 'purge all' functionality, perhaps people would have to pass the targets `database.purge(database.tables())` and `table.purge(table.all())`.

PS - just noticed whilst writing option 3, there is also an inconsistency with `database.tables()` and `table.all()`. Wouldn't `table.elements()` be more complimentary to `database.tables()`? Perhaps this needs a discussion too.

**Comment by msiemens** [comment]
That's an interesting point to discuss, I haven't really thought about that. Just for reference: the current state of affairs is that for removing tables we have `db.purge_table(name)` and `db.purge_tables()`, for deleting elements `table.delete(query)` and `table.purge()` as equivalents.

I think the question to ask here is what is more intuitive for the user. Maybe consistency between removing tables and removing elements is what users would expect. Personally I feel like removing tables and removing elements is different enough to justify an inconsistency here, but I've worked on TinyDB far too long to have an outsider's view on that. What do you think?

Another point we shouldn't ignore is that the current functions have been around for most of the time that TinyDB exists so we should be certain that it's worth having a breaking change and thus releasing TinyDB 4.0 for that change only.

**Comment by therden** [comment]
A vote here for clarity and consistency in command names and forms.  

To avoid breaking existing apps, support for the current terminology can be continued indefinitely (until such time as their discontinuation can be introduced at the same time as  other, major breaking changes), but deprecated (removed from documentation examples.)

**Comment by rz** [comment]
As an outsider (first time looking at TinyDB), I was at first confused by what the functions in question did. I would favor having a naming scheme along these lines:

```
db.purge_all_tables()
db.purge_table(name)
table.purge_elements(query)
table.purge_all_elements()
```

While they are a bit more verbose, I think they clarify the intent of the functions and give a way to deprecate the old functions without breaking backward compatibility.

**Comment by ffeast** [comment]
Agree that `table.purge` should be equal to `db.purge_table`
I think it were called differently like `db.drop_table` and `table.purge` it would be less confusing

Or just remove the method `table.purge` - as I understand it does the same as `table.remove()` anyway

**Comment by radek-sprta** [comment]
I would argue that option two is the most sensible. It keeps the function names consistent and concise. Moreover, it is in line with the meaning of the verb 'purge' - to get rid of unwanted elements (as evidenced by Cambridge Dictionary of English and other major dictionaries).
