### ISSUE TITLE
What software does your forum use?

### ISSUE THREAD

**Issue by jfmatth** [msiemens/tinydb#108]
Thanks for writing TinyDB, i'm considering it for a project at work :)

I love the forum and it's format, what software is that?

thanks

**Comment by nkantar** [comment]
It appears to be [Flarum](http://flarum.org).

**Comment by jfmatth** [comment]
thanks.

**Comment by fenderrex** [comment]
You could build the full stack with python backend,flask for web interfacing, bootstrap with for the tons of cool free and flexible templets, nginx load balancer with unix sockets enabled. Then host it at home a AWS or digitalocean droplet for as low as 5$ month... If you can spend the time you can be all mobile, anyone want to buy a 30$* month web app? :)

**Comment by msiemens** [comment]
As @nkantar already guessed, I'm using Flarum for the forum.
