### ISSUE TITLE
Can't get tinydb imported

### ISSUE THREAD

**Issue by learningtour** [msiemens/tinydb#120]
If I run the sample script from a file (python tinydb.py) on Python 2.7.6. on my Mac, I get this error:

Traceback (most recent call last):
  File "tinydb.py", line 1, in <module>
    from tinydb import TinyDB, where
  File "/Users/sergedebeer/Desktop/tinydb.py", line 1, in <module>
    from tinydb import TinyDB, where
ImportError: cannot import name TinyDB

If I paste it line-by-line, directly in Python it loads perfectly.

Maybe a beginners question, but I hope you can help me.

Serge de Beer,
Netherlands

**Comment by msiemens** [comment]
Hey, the problem is most certainly that your file is called `tinydb.py` which causes Python to try to import `TinyDB` from your file instead of the installed library. Just renaming your file should fix it 🙂 Also, if there's a `tinydb.pyc` remaining, just remove it. Does that fix it for you?

**Comment by learningtour** [comment]
Thanks for your quick response. I feel a little bit ashamed that the solution is so simple... :)
But now it works perfectly!

**Comment by msiemens** [comment]
No worries, we all started with that kind of problems :)
