### ISSUE TITLE
How to insert via Update() method

### ISSUE THREAD

**Issue by jfmatth** [msiemens/tinydb#123]
Hi, thanks again for this project, it's great.

The documentation says you can update or insert values with the update() method, but I don't see how that's done?

```
db.update(fields, query) only allows you to update an element by adding or overwriting its values.
```

Any help is appreciated

**Comment by msiemens** [comment]
Hey, `update()` is only for updating existing elements, actually. Seems like the documentation is off there. Could you provide a link where the documentation states that `update()` would also insert values?

**Comment by jfmatth** [comment]
I'll make a pr and send it over
