### ISSUE TITLE
Forum Github / Twitter login broken?

### ISSUE THREAD

**Issue by cdeil** [msiemens/tinydb#125]
I'm getting an error trying to log into the forum with both Github and Twitter.

For Github I get a 404, for Twitter an HTML page with an error message.

Can someone reproduce the issue?

**Comment by msiemens** [comment]
Oh, thanks for reporting! I don't know why it suddenly stopped working (without any changes on my side), but I've updated some of the forum software and it seems to work now. Can you confirm that?

**Comment by cdeil** [comment]
Fixed. Thanks!
