### ISSUE TITLE
Custom columns/data types for spatial data

### ISSUE THREAD

**Issue by achapkowski** [msiemens/tinydb#128]
Can tinydb handle spatial data?  
If not, is there a way to insert wkb data? Or should it stick to wkb/geojson?

Thanks

**Comment by eugene-eeo** [comment]
TinyDB certainly can _store_ spatial data, but there is no meaningful way to fetch the data (e.g. TinyDB has no way of fetching all of the points within a circle) unless you're willing to write your own query functions. Some useful links include:

 - [Advanced Usage - Queries](http://tinydb.readthedocs.io/en/latest/usage.html#queries)
 - [`tinydb.queries.Query`](http://tinydb.readthedocs.io/en/latest/api.html#tinydb.queries.Query)

Although TinyDB works fine for small workloads, if you want something that is more focused on spatial data, and you want more efficient queries something like [Tile38](http://tile38.com) is good.

**Comment by achapkowski** [comment]
@eugene-eeo Thanks, I'm looking for something small, where users can manipulate datasets in say a pandas' dataframe then save the data to disk, share it, or work on it later.  

I wanted a db that didn't require dll's to be installed (for example spatialite), and one that I can create without using some sort of install like mongodb.

**Comment by eugene-eeo** [comment]
@achapkowski no problem. If you're using Pandas then there are a variety of ways to [save a DataFrame to disk](http://pandas.pydata.org/pandas-docs/stable/api.html#id12). However if none of those satisfy your requirements then by all means use TinyDB, just be aware that TinyDB doesn't know about the structure of your data or how to do spatial queries.
