### ISSUE TITLE
Search element in list

### ISSUE THREAD

**Issue by mathben** [msiemens/tinydb#133]
Hi, I would like to search element in list. I show you an exemple of data structure.

```json
{
  "user_name":"bob",
  "character":[
    {
      "xp_1":true,
      "xp_2":false,
      "life":2
    },
    {
      "xp_1":false,
      "xp_2":true,
      "life":4
    }
  ]
}
```

So, I try that query.
```python
import tinydb
user_db = tinydb.TinyDB(...)
# search all user with xp_1 at True
lst_user = user_db.search(tinydb.Query().character.all(tinydb.Query().xp_1 == True))
```
Result attempt : 
lst_user = ["bob"]

This return error : 
«{AttributeError}'tuple' object has no attribute 'hashval'

Documentation : 

- http://tinydb.readthedocs.io/en/latest/api.html#tinydb.queries.Query.all
- http://tinydb.readthedocs.io/en/latest/usage.html#advanced-queries

Thanks for your help!

Edit: I update the json with list.

**Comment by msiemens** [comment]
Hey,

`Query.all` is meant to be used with lists. To query nested dicts you can simply add it to the query like this:

```
user_db.search(Query().character.xp_1 == True)
```

I think right now we don't have an example for that in the documentation, is that correct?

**Comment by mathben** [comment]
Sorry, I made a mistake, I forgot to add the list in "character" key.

For nested fields, we have example here : http://tinydb.readthedocs.io/en/latest/usage.html#queries

**Comment by msiemens** [comment]
That's interesting, the following code seems to work just fine:

```python
from tinydb import TinyDB, Query
from tinydb.storages import MemoryStorage
db = TinyDB(storage=MemoryStorage)
db.insert({
    "user_name": "bob",
    "character": [
        {
            "xp_1": True,
            "xp_2": False,
            "life": 2
        },
        {
            "xp_1": False,
            "xp_2": True,
            "life": 4
        }
    ]
})

lst_user = db.search(Query().character.all(Query().xp_1 == True))
print(lst_user)
```

Does it raise an exception when you run it?

By the way, the query won't return any elements as it requires that _all_ `xp_1` values are `True` while the example code has one `xp_1` set to `False`.

**Comment by msiemens** [comment]
@mathben Is this still an issue?

**Comment by mathben** [comment]
I will test the code later (like in October 2017). We can close the issue, thank you.

**Comment by msiemens** [comment]
Alright. Feel free to re-open the issue, if it's still a problem :)

**Comment by kevintruong** [comment]
It still have a issue on seach element on list

**Comment by msiemens** [comment]
@kevintruong What's the exact issue you are having?

**Comment by kevintruong** [comment]
Sorry for not detail on the issue 
for example 
`{
  "_default": {
    "1": {
      "user": "kevintruong",
      "cards": [
        {
          "id": "card_id",
          "info": {
            "model": [
              "abc",
              "def",
              "xyz"
            ],
            "lasttime": "lasttime_test",
            "shared": "true"
          }
        }
      ]
    }
  }
}`
I am trying to querry to get specific card in the list `cards` and update on the card element only. But unlucky I am, still stuck
Currently, only edit the card through the whole object 
```
user = self.db.get(Query().user == user_id)
        for index, each_card in enumerate(user['cards']):
            if each_card['id'] == card.id:
                user['cards'][index] = card.to_dict()
        self.db.update(user)
```

**Comment by msiemens** [comment]
I fear there's not really a way around looping through all cards and performing the updates there. This is mainly due to the fact that although TinyDB has support for partially updating objects, this is implemented by overwriting the fields of the existing document using the values from the data provided to the update method. In other words, TinyDB can only replace document values, but not parts of document values (like in your example where you want to update a _single_ card, not the list of cards altogether).

An alternative approach would be to store cards in a separate TinyDB table and store the user ID for each card. This way you could update a single card easily. The downside is that fetching a user's cards is now a separate step as you need to look them up in the new table.
