### ISSUE TITLE
Python 3.6 not mentioned in README

### ISSUE THREAD

**Issue by paul-hammant** [msiemens/tinydb#143]
Upper bound days v3.5, right now.

v3.6:
* planned?
* explicitly not supported right now?
* might work?
* impossible for reasons?

**Comment by msiemens** [comment]
Hey, it was just an oversight, I forgot to update the list of supported versions in the docs. We already run all tests on Python 3.6 so it should work just fine :)

**Comment by paul-hammant** [comment]
:)
