### ISSUE TITLE
ACID and resilience

### ISSUE THREAD

**Issue by paul-hammant** [msiemens/tinydb#144]
What happens if Ctrl-C happens during a write?  Documentation should perhaps talk of this some.

**Comment by msiemens** [comment]
TinyDB offers no ACID guarantees. If the Python interpreter is interrupted during a TinyDB write operation, as far as I can tell no data should get lost. But if you need stronger guarantees than "should", it's probably better to use [sqlite](https://docs.python.org/3.6/library/sqlite3.html) which is highly resilent agaist corruption. But you're right, the docs should mention this.

**Comment by msiemens** [comment]
For now I've added a note in the introduction (see 99ea605b8875d7ecc3ff2179354db387686627aa).

**Comment by paul-hammant** [comment]
Thanks for updating the docs so promptly - great work :)
