### ISSUE TITLE
Isolation

### ISSUE THREAD

**Issue by guibos** [msiemens/tinydb#146]
I know  that this engine is not ACID. But I want to know if this database have isolation feature. I want to use it in a small http server, that one or two people con read or write in the database. 

Nice project!

Thanks

**Comment by msiemens** [comment]
Hey, what concept of isolation are you referring to? Do you mean any form of access control with multiple users?

**Comment by guibos** [comment]
Thanks for reply. For example my application is a webapp. I would like to know if two users write simultaneously in this database, the file may be truncated or corrupted since the server can receive several simultaneous requests.

**Comment by eugene-eeo** [comment]
@guibos writing to the same database (whether on the same instance or not) in _parallel_ is not supported out of the box. Think of the default TinyDB as a wrapper around a file, there's no locking guaranteed and no defined behaviour if you write to it in parallel.

**Comment by guibos** [comment]
Thanks @msiemens ! Case closed.

**Comment by msiemens** [comment]
BTW, maybe https://github.com/eugene-eeo/tinyrecord is something for you, it has a per-database lock so a database can only be accessed by one thread at a time
