### ISSUE TITLE
A version attr for tinydb - Enhancement

### ISSUE THREAD

**Issue by Phuket2** [msiemens/tinydb#148]
It would be nice to have a version attr for tinydb.  After my embarrassing mistake of running such an old version of tinydb, in the small app I am doing i wanted to do a version test on the lib. I still consider myself a beginner, so there may be other ways to do this that I am unaware of. But I have seen other Libs like SQLite for example have a version attr.
For backward compatibility we could use hasattr(db, 'version') before accessing it directly which if failed would tell us the maximum version it could be, if does not fail could then use the version attr.  
Seems to me to this would be ok given, you typically would do this once at the star of your app.

**Comment by msiemens** [comment]
That's a good idea! I'll release TinyDB v3.4.1 shortly which exposes the TinyDB version from the `tinydb` module like this:

```
import tinydb
print(tinydb.__version__)

# or

from tinydb import TinyDB, __version__ as tinydb_version
print(tinydb_version)
```

**Comment by Phuket2** [comment]
Perfect. Thanks. That will be useful for me, I hope others also
