### ISSUE TITLE
Nested search issue .has

### ISSUE THREAD

**Issue by caiofcm** [msiemens/tinydb#149]
I just installed this module and I`m learning to use it.

When trying the following command from the [documentation](http://tinydb.readthedocs.io/en/latest/usage.html):

    db.insert({'field': {'name': {'first_name': 'John', 'last_name': 'Doe'}}})
    db.search(where('field').has('name'))`

I get the error: `TypeError: 'Query' object is not callable`

I can't figure out what I am doing wrong here. Any guidance? Thank you.

**Comment by Phuket2** [comment]
@caiofcm , i cant see you example in the documentation.  But the below may help
```python
from tinydb import TinyDB, Query

_fn='test.json'

db=TinyDB(_fn)
db.insert({'field': {'name': {'first_name': 'John', 'last_name': 'Doe'}}})
q=Query()
print(db.search(q.field.name.first_name == 'fred'))
print(db.search(q.field.name.first_name == 'John'))
print(db.search(q.field.name.last_name == 'Doe'))
```

**Comment by caiofcm** [comment]
Ok, I was referring to an older documentation. Thank you for explaining.
