### ISSUE TITLE
TinyDB name already in use by older project

### ISSUE THREAD

**Issue by therden** [msiemens/tinydb#152]
Searching for some information about your project today, I came across another, pre-existing one with the same name:

[TinyDB: An Acquisitional Query Processing System for Sensor Networks](http://telegraph.cs.berkeley.edu/tinydb/)

Just thought you'd want to know.

**Comment by msiemens** [comment]
That's interesting. I remember doing a search for the name `tinydb` before releasing it without finding anything really that used this name. Somehow I must have missed this one. Anyway, it seems to be targeted at embedded systems and not dynamic scripting languages so I think this is fine. Also, TinyDB is itself 4 years old now so I think it's too late to change the name now. But thanks for letting me know!

**Comment by therden** [comment]
I agree that the domains of the two projects are dissimilar enough that the
shared name shouldn't be a problem; just thought you'd want to know of the
other's existence.
