### ISSUE TITLE
How to use array indexing notation with traditional where query form?

### ISSUE THREAD

**Issue by therden** [msiemens/tinydb#153]
In the Queries section of the Advanced Usage page of the docs, the example of a nested field query is given.

> db.search(User.birthday.year == 1990)

This can also be expressed using array indexing notation

> db.search(User['birthday']['year'] == 1990)

But how can array indexing notation be combined with the *where()* shorthand query form?  
When this

> db.search(where('birthday''year') == 1990)

didn't work as expected, I tried the following variations, with no luck.

> db.search(where('birthday','year') == 1990)
> db.search(where('birthday'.'year') == 1990)
> db.search(where(['birthday'].['year']) == 1990)
> db.search(where(['birthday']).['year'] == 1990)
> db.search(where(['birthday')['year'] == 1990)
> db.search(where(['birthday']).'year' == 1990)

Am I missing something, or isn't this supported?

**Comment by msiemens** [comment]
Hey, the docs should explain this better now.

**Comment by therden** [comment]
Yes they do.  Thank you!
