### ISSUE TITLE
Clarification re: Regex searches in documentation's "Advanced queries" section

### ISSUE THREAD

**Issue by therden** [msiemens/tinydb#154]
Although they map directly to the usage of Python's re module, it might still be worth noting within tinydb's documentation the distinction between the *matches()* and *search()* methods, (whole string has to match, versus only substring has to match.)

**Comment by msiemens** [comment]
Hey @therden, I updated the documentation now, I hope it's now better in explaining the difference between `matches()` and `search()`.

**Comment by therden** [comment]
I think you nailed it.  Thanks!
