### ISSUE TITLE
'Advanced Queries' documentation of list field methods is confusing

### ISSUE THREAD

**Issue by therden** [msiemens/tinydb#155]
After some trial and error, I was able to figure out the list-based approach.  But the comments preceding the list-based examples are confusing.  The following might be better for *any()*:

> \>\>\>  \# User's groups list field includes at least one value from ['admin', 'user'] list

And for *all()*:

> \>\>\>  \# User's groups list includes _all_ values from ['admin', 'user'] list

Could you provide more information in the documentation about the underlying database structure referenced in the examples for the Query-based approach to working with fields containing lists?  I'm having trouble understanding this section.

**Comment by msiemens** [comment]
Hey, this too should be explained better now. Do you feel like the explanation is now more accessible/understandable now?

**Comment by therden** [comment]
Adding the insert statement helps some.  However, another line needs to be added to make the example work:

> Group = Query()

**Comment by therden** [comment]
I think this section still needs more work.  I'd suggest

1) adding a minimum of two more records

> db.insert({'name': 'user1', 'groups': [{'name': 'user'}]})
> db.insert({'name': 'user2', 'groups': [{'name': 'admin'}, {'name': 'user'}]})
> db.insert({'name': 'user3', 'groups': [{'name': 'sudo'}, {'name': 'user'}]})

2. , showing an *all()* query that produces a result other than an empty list, like:

> db.search(User.groups.all(Group.name == 'user'))

An even better example would show how to use all() to specify two or more values (like 'user' and 'admin') -- I haven't so far been able to guess how to do that.

**Comment by therden** [comment]
I am puzzled that in the current example the list contains dicts which all have the same key.  Wouldn't it be more natural for the list just to contain the group values?

> db.insert({'name': 'user1', 'groups': ['user']})
> db.insert({'name': 'user2', 'groups': ['admin', 'user']})
> db.insert({'name': 'user3', 'groups': ['sudo', 'user']})

Then the queries would look simpler:

> db.search(Query().groups.any('user'))
> \>\>\> [{'groups': ['user'], 'name': 'user1'},
> \>\>\>   {'groups': ['admin', 'user'], 'name': 'user2'},
> \>\>\>   {'groups': ['sudo', 'user'], 'name': 'user3'}]

Even with multiple search values:

> db.search(Query().groups.all(['user', 'admin']))
> \>\>\>  [{'groups': ['admin', 'user'], 'name': 'user2'}]

(Although the value supplied to *all()* has to be a list.)

**Comment by msiemens** [comment]
> I think it is unnecessarily confusing that currently the list in the initial record contains dicts which all have the same key, while the second record contains a list of values.

You're right about that! To be honest, I was too lazy to come up with a new example for the second case but you're totally right that it's actually kind of confusing. I've now reordered the examples so searching with lists comes first and then we introduce a new example for nested queries.

> db.search(Query().groups.any('user'))

BTW, this actually only works by accident. Python lets `'foo' in 'foo'` evaluate to `True`, but this doesn't work when using ints for example. So the proper way to use a query like this would still be

> db.search(Query().groups.any(['user']))

I'm not sure though whether or nor we should add a note about this special case in the docs...

**Comment by therden** [comment]
I think that your latest updates have greatly improved this section of the docs.  Thank you for being so responsive!

If you are partial to the 'only works by accident' (under some conditions) form of nested query, I think it will definitely be worth noting the limitations of that approach.  Personally, I would recommend removing the 'works by accident' form from the docs entirely and *only* show the 'proper' form for nested queries that will *always* work as expected.

**Comment by therden** [comment]
*all()* seems to work differently when the field contains a list of, for example, strings than it does when the field contains a list of dicts.

With dicts, records for which the field's list contents exactly match the values provided in *all()* -- if the list in the record contains an extra dict, it won't be returned.  In this case, *all()* works as thoughtit means *exact()*.

But with strings, records for which the field's list contents include the values provided in *all()* will be returned -- even if the list in the record contains additional, unmatched strings.  In this case, *all()* works as though it means *at_least()*.  Example follows:

> db.insert({'name': 'user1', 'groups': ['user', 'test']})
> db.insert({'name': 'user2', 'groups': ['admin', 'user', 'test']})
> db.insert({'name': 'user3', 'groups': ['sudo', 'user', 'test']})

> db.search(Query().groups.all(['user', 'test']))
> \>\>\> [{'groups': ['user', 'test'], 'name': 'user1'},
> \>\>\>  {'groups': ['admin', 'user', 'test'], 'name': 'user2'},
> \>\>\>  {'groups': ['sudo', 'user', 'test'], 'name': 'user3'}]

**Comment by msiemens** [comment]
> Personally, I would recommend removing the 'works by accident' form from the docs entirely and only show the 'proper' form for nested queries that will always work as expected.

As far as I can tell that's already what we're doing 🙂 Or did I miss anything?

> With dicts, records for which the field's list contents exactly match the values provided in all() -- if the list in the record contains an extra dict, it won't be returned. In this case, all() works as thoughtit means exact().

Could you provide an example for that? I just tested it and extra dicts shouldn't make a difference:

```python
>>> db.insert({'followers': [{'name': 'john'}, {'name': 'jane'}]})
>>> db.insert({'followers': [{'name': 'john'}, {'name': 'jane'}, {'name': 'bob'}]})
>>> db.search(where('followers').all([{'name': 'jane'}, {'name': 'john'}]))
[{'followers': [{'name': 'john'}, {'name': 'jane'}]},
 {'followers': [{'name': 'john'}, {'name': 'jane'}, {'name': 'bob'}]}]
```
 
Altough, if you _add an extra field_ to a otherwise matching element, it won't match anymore:

```
>>> db.purge()
>>> db.insert({'followers': [{'name': 'john'}, {'name': 'jane', 'logged_in': True}]})
>>> db.search(where('followers').all([{'name': 'jane'}, {'name': 'john'}]))
[]
```

**Comment by therden** [comment]
Sorry, in writing that I didn't refer to the current version of the
documentation -- I was responding to your prior message, which I now
realize that I misread.

I now see that you were letting me know that it was the malformed query I'd
sent that works only by accident, not the example that you'd added to the
docs.  I now agree with your decision *not* to mention in the docs the
'wrong form that sometimes works' that I stumbled upon.

**Comment by therden** [comment]
I had in mind the last example in this section of the docs; it does not
return all the records that match at least the query term, but only the
record that exactly matches it.

Or is this an aspect of nested queries rather than an aspect of *all()* and
nested fields?

**Comment by msiemens** [comment]
> it does not return all the records that match at least the query term, but only the record that exactly matches it.

If I understand you correctly, you mean that a query like this:

```
db.search(Group.permissions == {'type': 'read'})
```

won't match a document with extra fields in `permissions`, like

```
{'permissions': {'type': 'read', 'enabled': True}}
```

Is that correct?

That would be an aspect of queries themselves. When comparing records like this, we check if they are completely identical. If one side (either in the database or provided by the user) has extra or missing fields, the query won't match.
