### ISSUE TITLE
Get or insert question

### ISSUE THREAD

**Issue by ffeast** [msiemens/tinydb#156]
Hi

What's the recommended way to implement get_or_insert(key, val) that is "insert something if such a key isn't there yet"? Is it just db.search / db.get followed by db.insert? 
Thanks

**Comment by therden** [comment]
I'm just beginning to learn tinydb, but I'm willing to try to help.  But first, I'll need to understand whether you are asking:

a) how to test for the existence of an element (AKA record or document) and add it to the database if it does not exist, 

or

b) how to add a key and an associated value to every element/record/document in a database that does not already have that key?

**Comment by ffeast** [comment]
@therden, a)

**Comment by msiemens** [comment]
Hey @ffeast, if you want to check if a complete element/record exists, you'll have to do a full search followed by an insert, if it doesn't exist. On the other hand, if you want to only check, if an element ID exists, you can use `db.contains(eids=[...])` to check, if that ID is already present.

In general, I think it would be worth considering if we should add a shorthand for the second option (if an ID exists). With regards to the first option, I think it will be better to do a regular search followed by an insert as it's a relatively expensive operation and the TinyDB API shouldn't pretend it anything else (`get_or_insert` would suggest a relatively cheap operation)

**Comment by ffeast** [comment]
@msiemens, thanks, that answers my question
