### ISSUE TITLE
el.doc_id not working?

### ISSUE THREAD

**Issue by haukero** [msiemens/tinydb#160]
I get the following error using el.doc_id with TinyDB 3.5.0:
`>>> tinydb.__version__`
`'3.5.0'`

`>>> from tinydb import TinyDB`
`>>> testdb = TinyDB('test.json')`
`>>> testdb.insert({'value': 10})`
`1`

`>>> testdb.all()[0].doc_id`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`AttributeError: 'Element' object has no attribute 'doc_id'`

el.eid however works although I don't see a deprication warning:
`>>> testdb.all()[0].eid`
`1`

Is there some problem in the code or am I doing something wrong?

Thanks!

**Comment by haukero** [comment]
I see, the documentation refers to the latest changes but not to the latest release.
When are the el.doc_id changes being released?

Thanks!

**Comment by msiemens** [comment]
Hey @haukero, sorry for the confusion! The doc (unfortunately in this case) always point to the current dev version and I haven't gotten around to release v3.6.0 last week as I wanted. I've now released it, so after a quick update it should work as expected :)

**Comment by haukero** [comment]
Thanks a lot, works as expected, great!

**Comment by paul-hammant** [comment]
A "new in v 3.6.0" note in the documentation might help people avoid googling to solve the problem.

Maybe a note about speed too? "Using Doc_Ids for updates is faster than the same operation with a Query() usage" (if true).

**Comment by eugene-eeo** [comment]
@paul-hammant fair point. Do you want to write a PR for that? If not I'll do it some time this week. On the speed point, I think it is true (since we do a direct lookup on the hash table) but not by much.

**Comment by paul-hammant** [comment]
Will do :)

**Comment by paul-hammant** [comment]
https://github.com/msiemens/tinydb/pull/169 :)
