### ISSUE TITLE
tinydb in sqlite?

### ISSUE THREAD

**Issue by faststare** [msiemens/tinydb#166]
is possible to create storage with sqlite? I already created a prototype with your api but no caching mechanism using unidbm which they store pickle/json in sqlite row with table name and bolb column which store the data while the query part I just used directly your class in tinydb.utils.Query and it works.
it would nice to see tinydb have support with other storages in the core or create a tinydb extension with this matter. thanks in advance.

**Comment by alshapton** [comment]
@faststare  Presumably you''d like to use tinydb with an SQLITE backend ? They are both embedded databases, so unless I'm missing something, I can't see why you would use a combination of the two.... can you clarify what I'm missing ???? Thanks !

**Comment by faststare** [comment]
sqlite can store blob file like img file json etc. i just want to store json file in sqlite to be less cluttter ng may disk space. but it perform poorly without caching the data.

**Comment by msiemens** [comment]
@faststare My question would be why not using SQLite altogether? There are good reasons for using TinyDB with a JSON backend or using SQLite, but trying to combine both doesn't seem to bring any real benefits as far as I can see. I don't see how a JSON file clutters disk space more than SQLite does. If disk space is a concern, you always can write a storage that GZIPs the JSON file…
