### ISSUE TITLE
upsert not defined for tables

### ISSUE THREAD

**Issue by cinnamennen** [msiemens/tinydb#168]
If I do something like
```python
database = TinyDB('db.json', default_table='translate')
database.upsert({'username': 'John', 'role': 'admin'})
```
it results in an error `AttributeError: 'Table' object has no attribute 'upsert'`

**Comment by msiemens** [comment]
That's correct! I plan to implement #164 this weekend and then publish a new release of TinyDB :)

**Comment by msiemens** [comment]
Version 3.7.0 of TinyDB has just been released, so this problem should be fixed now 🙂
