### ISSUE TITLE
Clarification Reqd: Running script from Windows Task Scheduler gives permission error

### ISSUE THREAD

**Issue by mssharathchandra** [msiemens/tinydb#173]
I have a script that has the line:
`db = TinyDB('leave_db.json')`

I later do some inserts into the DB in the code. This is a script that I want to run on a scheduled basis and I am trying to use the Windows Task Scheduler to run this script. When I run this script through command prompt, it runs without any problems. But, when the task scheduler runs the script, I get the following error:

Traceback (most recent call last):
  File "C:\Users\dummy\tracker.py", line 7, in <module>
    db = TinyDB('leave_db.json')
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\tinydb\database.py", line 142, in __init__
    self._storage = storage(*args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\tinydb\storages.py", line 89, in __init__
    touch(path, create_dirs=create_dirs)  # Create file if not exists
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\tinydb\storages.py", line 24, in touch
    with open(fname, 'a'):
PermissionError: [Errno 13] Permission denied: 'leave_db.json'

I don't have admin privileges on the system where I am scheduling this task. I am not sure if this is an issue in the TinyDB package or if Windows doesn't allow this to work. Please clarify on how I can proceed with this.

TinyDB version used: 3.7.0
Python version: 3.6
Windows version 10 Enterprise

**Comment by cmccandless** [comment]
Try using an absolute path for `leave_db.json`. Most likely issue is that the working directory is not "C:\Users\dummy", but instead "C:\Windows\system32" (location of `taskschd.msc`, the executable for Task Scheduler).

**Comment by mssharathchandra** [comment]
Hello @cmccandless,

Thank you so much for your response. I now feel miserable that I asked this question in the first place; I should've thought about this myself. After using the absolute path, everything works perfectly! Thanks again for the gentle response and helping me out, much appreciated.

Regards,
Sharath
