### ISSUE TITLE
Using with multithreading TinyDB throws error ValueError: Invalid control character at: line 1 column 951 (char 950)

### ISSUE THREAD

**Issue by jinesh90** [msiemens/tinydb#176]
I am using tinyDB insert with python multithreading and it gives seldom error

I am using by following code
```
class foo: 
  def __init__(self):
      pass
  def get_some_data(self, param1, param2):
       data = get_data()
       db = TimyDB('data.json')
       db.insert(data)
  def populate_data(self):
      threads = []
      thread = Thread(target=self.get_some_data, args=(param1, param2))
      threads.append( thread )
      for thread in thread_list:
          thread.start()
      thread.join()

def main():
    f = foo()
    f.populate_data()
  ```

Gives me error below sometimes:
ValueError: Invalid control character at: line 1 column 951 (char 950)

**Comment by msiemens** [comment]
Hey @jinesh90, that's correct. As [mentioned in the documentation](https://tinydb.readthedocs.io/en/latest/intro.html#why-not-use-tinydb), TinyDB is not meant to be used with multithreading. If you want, you can use your own locking mechanism (for example based on Python's [Lock](https://docs.python.org/2/library/threading.html#lock-objects). You could also use an extension like [tinyrecord](https://github.com/eugene-eeo/tinyrecord/).

**Comment by jinesh90** [comment]
@msiemens , Thank you for feedback, I was reading document and realized that it is not meant to be used with multithreading, I modified my code below and it works for me.
 `from threading import RLock
  class foo: 
     def __init__(self):
         
      
  def get_some_data(self, param1, param2):
       data = get_data()
       db = TimyDB('data.json')
       self.rlock.acquire()
       db.insert(data)
       self.rlock.release()
  def populate_data(self):
      threads = []
      thread = Thread(target=self.get_some_data, args=(param1, param2))
      threads.append( thread )
      for thread in thread_list:
          thread.start()
      thread.join()

def main():
    f = foo()
    f.populate_data()`

**Comment by chemradio** [comment]
Thank you for making everything clear in this thread. I've managed to use Rlock slightly differently

`from tinydb import TinyDB, Query
from threading import RLock
main_db_lock = RLock()


def thread_safe(func):
    def wrapper_thread_safe(*args, **kwargs):
        with main_db_lock:
            func(*args, **kwargs)
            return func(*args, **kwargs)
    return wrapper_thread_safe



class TinyDBHandler:
    def __init__(self) -> None:
        self.db = TinyDB('./database/db.json')


    @thread_safe
    def add_db_entry(self, parameters):
        return self.db.insert(parameters)`
