### ISSUE TITLE
using while loops for updating

### ISSUE THREAD

**Issue by ire4ever1190** [msiemens/tinydb#178]
Hi I'm trying to use a while loop for updating my data base but it keeps giving me this error message

> TypeError: 'QueryImpl' object is not iterable

my code is like this

```
query = Query()
while x < 10:
        number = "my  number is " + str(x)
	qoute = "foo bar"
	tinydb.update({'number': number},{'qoute': qoute}, query.day == 'monday')
	x = x + 1
```

**Comment by msiemens** [comment]
Hey, I looked into this and the error is how you pass the arguments. `db.update(…)` expects two parameters: the updated fields and the query. You instead pass three parameters: two dicts and a query, which confuses TinyDB. Is it possible that you mean to use one dict instead? Like this:

```
query = Query()
while x < 10:
        number = "my  number is " + str(x)
	qoute = "foo bar"
	tinydb.update({'number': number, 'qoute': qoute}, query.day == 'monday')
	x = x + 1
```

This would set both `number` and `quote` to the values calculated in the loop for all documents with `day == 'monday'`.

**Comment by ire4ever1190** [comment]
Thank you that worked.
