### ISSUE TITLE
Python 2.6 failed to setup in CI test

### ISSUE THREAD

**Issue by davidlatwe** [msiemens/tinydb#185]
### Problem

In the time I made PR #184 , Python 2.6 start failing to pass the CI test setup, due to `pytest-runner` not able to find the package `setuptools_scm`. Checkout branch `master` to build test also showed same result.

### Discussion

Based on this [fact](https://github.com/msiemens/tinydb/pull/184#issuecomment-359277834), can Python 2.6 be dropped ?

**Comment by msiemens** [comment]
I think this should be fine as pip also dropped support for Python 2.6 (see pypa/pip#3955). If no one else has any objections, we can do this.

@eugene-eeo

**Comment by hugovk** [comment]
Please see PR https://github.com/msiemens/tinydb/pull/188.
