### ISSUE TITLE
Missing documentation for tinydb.database.Document

### ISSUE THREAD

**Issue by alex-ball** [msiemens/tinydb#186]
On the website, there is a cross-reference from Element to Document, but no documentation for tiny.database.Document:
http://tinydb.readthedocs.io/en/latest/api.html#tinydb.database.Element

I can't reproduce this on my local system since Sphinx always picks up the installed version, not the adjacent source code, but I presume that in `docs/api.rst`, the line:

```
.. autoclass:: tinydb.database.Element
```

should be

```
.. autoclass:: tinydb.database.Document
```

**Comment by msiemens** [comment]
Thanks for reporting, should be fixed with 7ac89ddc0cdb44e54520a3260479b29c50d9de5e 🙂
