### ISSUE TITLE
How can I use tindyDB in my ApiInterface ?

### ISSUE THREAD

**Issue by ismailtosun** [msiemens/tinydb#189]
Hi , My api interface class like this 

```
public interface ApiInterface {
    @FormUrlEncoded
    @Headers("wkey",***********TinyDB*********)
    @POST("srrvk")
    Call<JoinAllAllowedInnoResponse> GETJOINALLOWEDINNOLIST(@Field("a") Integer lastOrderId, @Field("b") Integer rowCount);
```

I saved a wkey parameter in tinyDB, My question is how can I use tinyDB in my apiInterface class ?

**Comment by msiemens** [comment]
Hey, that doesn' look like Python code to me. TinyDB is a Python project and won't run with other progamming languages :)

Cheers!
