### ISSUE TITLE
Table' object has no attribute 'write_back'

### ISSUE THREAD

**Issue by ChristopherLRios** [msiemens/tinydb#190]
I was trying to go through the Replacing Data part of the usage and I ran into the error below. I can't quite figure out what I am doing wrong. 

* I have just been following the guide in the link below
http://tinydb.readthedocs.io/en/latest/usage.html#replacing-data
---------------------------------------------------------------------------
.......
.......
~\Anaconda3\lib\site-packages\tinydb\database.py in __getattr__(self, name)
    220         Forward all unknown attribute calls to the underlying standard table.
    221         """
--> 222         return getattr(self._table, name)
    223 
    224     # Methods that are executed on the default table

AttributeError: 'Table' object has no attribute 'write_back'

**Comment by msiemens** [comment]
Hey @ChristopherLRios, are you sure you used the latest version of TinyDB?

**Comment by ChristopherLRios** [comment]
See below; I have not updated to your latest commit, however. 
---------------------------------------------------------------------------------------------
Python 3.5.4
Type "help", "copyright", "credits" or "license" for more information.
>>> import tinydb
>>> tinydb.__version__
'3.7.0'
>>> db = tinydb.TinyDB('test.json')
>>> db.write_back
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "....\lib\site-packages\tinydb\database.py", line 222, in __getattr__
    return getattr(self._table, name)
AttributeError: 'Table' object has no attribute 'write_back'

**Comment by msiemens** [comment]
Well, TinyDB 3.5.4 doesn't yet support `db.write_back(…)` (as it's not listed in this versions docs in https://tinydb.readthedocs.io/en/v3.5.0/usage.html). You'll have to update your TinyDB version to use new features 🙂

**Comment by ChristopherLRios** [comment]
Sorry, I have Python 3.5.4 running tinydb 3.7.0

**Comment by msiemens** [comment]
Sorry, somehow confused that. Still, `write_back` is available starting with TinyDB v3.8.0, so it's not available yet in TinyDB 3.7.0.

**Comment by msiemens** [comment]
So I forgot to publish the latest version to the Python package index. If you could again upgrade to the latest version of TinyDB, everything should work 🙂

**Comment by ChristopherLRios** [comment]
It works perfectly :) thank you

**Comment by msiemens** [comment]
Awesome 🙂 And sorry for the confusion with not publishing the latest version on PyPI!

**Comment by psiehr** [comment]
I just had the same error, as I did run v3.7.  Thanks for adding it to v3.8 and thanks for the write_back() method. This method should also be much faster than doing a update()/insert() for each document as write_back() only writes once on the hard drive, compared to a loop with update()/insert() in each step. Is that correct, @msiemens  ?  (Small remark v3.8 is not listed on the [changelog](http://tinydb.readthedocs.io/en/latest/changelog.html#unreleased).

**Comment by msiemens** [comment]
@psiehr Yes, that's correct. It's basically like an `update` working with a list of documents instead of only a single document at a time. And thanks for reporting the missing changelog, the latest docs build failed. It should be fixed now!
