### ISSUE TITLE
IEEE Standard for Floating-Point Arithmetic while using ujson to operate float

### ISSUE THREAD

**Issue by ClericPy** [msiemens/tinydb#191]
some float will gain a long tail...
```
>>> ujson.loads('[0.47]')
[0.47000000000000003]
```
```
>>> json.loads('[0.47]')
[0.47]
```
So sorry to bother, is there anyway to avoid this issue from ujson? 
https://github.com/esnme/ultrajson/issues/213 
IEEE 754, IEEE Standard for Floating-Point Arithmetic https://en.wikipedia.org/wiki/IEEE_754

**Comment by msiemens** [comment]
Hey @ClericPy, I don't think there's much that TinyDB can do in this case. One could make a good point that `json.loads('[0.47]')[0] == ujson.loads('[0.47]')[0]` should evaluate to `True`, but this is something that `ujson` would have to do, not TinyDB:

**Comment by ClericPy** [comment]
Thanks, I know what you said, the 0.47000000000000003 doesn't matter too much, I will ignore this.
