### ISSUE TITLE
A function that updates entries in the db and does not produce duplicates.

### ISSUE THREAD

**Issue by psiehr** [msiemens/tinydb#192]
At the moment I want to create a small database with <10000 entries and <10 different keys. I found tinydb as I am coding a lot in Python and I did not want to learn SQL etc. 
There is one major function missing that does the following. 

Using letters  for keys and integers as values. Assume the db has the entries:
```
1: {A:1} 
2: {B:2, C:42}
3: {A:3, C:42}
```
Now you want to insert `{A:1, B:2, C:42}` and the db should look like this: 
```
1: {A:1, B:2, C:42} 
3: {A:3, C:42}
```

What happened? 

1.  `{A:1}` was updated to `{A:1,B:2,C:42}`.
2.  `{B:2, C:42}` was updated to `{A:1,B:2,C:42}`. This entry got removed as it is now a duplicate.
3.  `{A:3;C:42}`  has been untouched

I am looking for advise, as this kind of update method get's awfully slow and there might be an elegant way that I don't see.  
Has anyone ever coded such a function?
Is there a method that cleans the database from duplicates? 

I have created two methods that I can share, if desired. One is unusable due to runtime ^^, but the other one works "ok". 

Thx for your help.

**Comment by Phuket2** [comment]
@psiehr, i just started to work on the issue you present here just out of interest . But it didn't take long for me to realise this is quite difficult(well for me it is). It seems to me, that a merge method is required vrs a dedupe method. But what should be merged and what operation should be applied to the value of the key being merged?  In your example, its clear you want sum operation to occur.  But what if a key 'A' had multiple values mostly int's but a few strings? Ok, then you define uniqueness to key and type(value), but you still would need decide what __add__ etc... does for each type encountered.  Then maybe you want to use multiple keys to define uniqueness, starts to get more difficult especially as each value of key can be any type. Then what to do with docs that have the same key set but varying k,v?  I guess you could use some set methods like 'union'.   
It seems like by using TinyDB's insert, update, upsert methods etc... you could avoid this scenario altogether.
I did think about different solutions, using methods from collections, sets etc... Mind you I am not so good with this.  
But, I have been suprised many times how powerful Python is.  Maybe the problem could be solved using a nested comprehension  + unpacking etc...
Would be interesting to see a generic solution to this.

Below is just my starter code I used to start to test. Only creates the db with some test data

```python
from tinydb import TinyDB, Query
import string

_db_fn = 'merge_example.db'
_db = TinyDB(_db_fn)
_testdata = [{k:i} for i,k in enumerate(string.ascii_uppercase * 2 + \
             string.ascii_uppercase[:5])]

def db_populate_test_data(data_list):
    _db.purge_table('_default')
    _db.insert_multiple(data_list)

if __name__ == '__main__':
    db_populate_test_data(_testdata)
    for item in _db.all():
        print(item)
    
    _db.close()
    print('Finished...')
```

**Comment by psiehr** [comment]
It is difficult - that is why I started this issue :) 

Still, I think I started it to early.  I almost finished writing the whole program, and will provide a minimal program, including a database, when finished. Using this as basis for optimization should be the better way. Sorry for the confusion.

Since I can't use my companies data for this minimal program, I will test your code then. Thank you, for your comment!

**Comment by msiemens** [comment]
> I am looking for advise, as this kind of update method get's awfully slow and there might be an elegant way that I don't see.
> Has anyone ever coded such a function?
> Is there a method that cleans the database from duplicates?

That's an interesting problem, altough it seems to me like it's useful in very specific cases only and I'm not sure whether this is something that TinyDB itself should handle. As far as I understand, you basically want a deduplication method which not just removes identical documents but also documents which are supersets of any given one. Is that correct?

**Comment by psiehr** [comment]
Sadly, I could not work more on this small project, as it is not prioritized at all. 

> which not just removes identical documents but also documents which are supersets of any given one. Is that correct?

The method should remove duplicates, but it should not remove supersets. At least in how I understand supersets. In the example above, there was the step:
2.  `{B:2, C:42}` was updated to `{A:1,B:2,C:42}`. This entry got removed as it is now a duplicate.

For the definitions:  `{B:2, C:42} ⊂  {A:1,B:2,C:42}`, so  `{A:1,B:2,C:42}` is a superset of `{B:2, C:42}`, while  `{B:2, C:42}` is the subset. 

---
> , altough it seems to me like it's useful in very specific cases only 

If you data is scattered between several sources (e.g. Excel files of different departments in a company), you may hit the case, where you need to merge these sources into one database. 

Or maybe I have a false understanding of how databases work. I will try to break down my problem into a minimal problem in the following. Sorry for this xy-problem ... 

---
As said above, I do have several Excel files containing information. Between these sources there exist connections by common keys. 

Source 1 contains  information "A" and "B",  Source 2  contains "A" and "C". 
So key "A" is the connection between both sources.  In total the sources  contain ~10000 entries and ~10 different keys. Sources may contain more than 2 keys and two sources may have more than just one key as connection. 

Source 1:
```
1: {A:1} 
2: {A:2, B:2}
3: {B:3}
```
Source 2:
```
1: {A:5} 
2: {A:2, C:2}
3: {C:4}
4: {A:2, C:5}
```

Task: If given any information (e.g `A==2`), create an output with all information known. 
Input: `A==2`
Output: `{A:2, B:2, C:3}; {A:2, B:2, C:2}`

My solution is/was to create one database that contains elements with all information in one database. 
```
1: {A:1} 
2: {A:2, B:2, C:2}
3: {A:2, B:2, C:3}
4: {B:3}
5: {A:5} 
6: {C:4}
```

So now you can use `db.search()` to get all the information necessary. Due to the process of this "merging" of databases it might happen that duplicates occur. Hence, my original question. 

I thought about doing something like: `{A:2, B:2, C:[2,3]}`, as this describes more the behaviour of the data in the sources. (E.g. a "A" can have several "C"s but a "C" can have at most one "A"). But then `db.search()` can't be used for key `C` anymore, if you don't know all values of C.

Another solution, that came to my mind, is the creation of a database for each source. 
Then searching in "the" database would mean to search in all databases.
Input: `C==2`
Step 1:  Search in database of source 2 and find `{A:2, C2}` 
Step 2: Search in database of source 1 for `A==2` and find `{A:2, B2}`. 
Output: `{A:2, C2}` and `{A:2, B2}`  (in some nice format)

With this solution the creation of databases is quite simple and fast.  But searching is something that takes more time and effort. So this solutions simply shifts "work" from the creation of the database to the application of the database. 
Since usually you create the basis of a database only once and later only update/insert new information, I dropped this solution. Searching is something that the user wants to do within fractions of a second. If the creation takes an hour noone minds. 

Additionally adding elements to the database is easier using one database. If the user wants to insert a new element, you can simply add it. In the second solution you need to find the correct database to insert the element. The same, but worse, problem occurs if you decide to add an additional source. How would Step 2 look like with several (new) databases? For sure it is more complicated.

---

**Comment by msiemens** [comment]
That's certainly an interesting problem to solve. Still, I don't think this should be included in the core of TinyDB but rather a custom solution or an extension. Sorry, I can't help with that.
