### ISSUE TITLE
Additional query operations

### ISSUE THREAD

**Issue by FHellmann** [msiemens/tinydb#193]
For a better usage of tinydb it would be awesome to have operations like:

- `db.search( ... ).min( Query().field )`
- `db.search( ... ).max( Query().field )`
- `db.search( ... ).avg( Query().field )`
- `db.search( ... ).sum( Query().field )`
- `db.search( ... ).limit( n ).xyz()`
- `db.search( ... ).first()`
- `db.search( ... ).last()`

**Comment by alshapton** [comment]
To me, this would seem to go against TinyDB's ethos of being tiny, however, having an "add-on" package with these in would seem to be the way to go. Since if you dont need them, you wont be lumbered with extra code in the base libraries..... Thoughts?

**Comment by msiemens** [comment]
Yeah, that's a tough call to make. What should be included and where should one draw the line? I'd say it should be easy to make a simple extension out of this (using a custom table class), but I'm open to change my mind.
