### ISSUE TITLE
dataset + tinydb

### ISSUE THREAD

**Issue by divanovGH** [msiemens/tinydb#196]
what if we integrate https://github.com/pudo/dataset into tinydb?

**Comment by msiemens** [comment]
@divanovGH What exactly do you have in mind? I think `dataset` and TinyDB have different goals, with `dataset` being a nice wrapper around relational databases while TinyDB is a document storage at its core. Altough it would be interest to port the TinyDB query syntax to `dataset`, though that's way beyond the scope of TinyDB.

**Comment by msiemens** [comment]
As I said, I'm open to spin-off projects and experiments, but this likely won't make it into the TinyDB core

**Comment by divanovGH** [comment]
I understand, thanks
