### ISSUE TITLE
Clarification on using db.all() len(db) etc. - Documentation

### ISSUE THREAD

**Issue by Phuket2** [msiemens/tinydb#198]
Documentation for len(db), len(db.all()) needs some rework/clarification. When the db object is used this way, its operating on the Table pointed to/named by TinyDB.DEFAULT_TABLE. So its the equivalent of doing len(db.table().all()).  Same as if you iterated over db.all(), you are still only working with the Table(TinyDB.DEFAULT_TABLE). 

Below is a link to the thread where this is discussed in the last few posts.
https://forum.m-siemens.de/d/21-eid-s-is-there-an-optimised-way-to-get-a-list-of-all-eid-s-in-the-tdb/7

**Comment by msiemens** [comment]
Thanks for the note, this is fixed now :)
