### ISSUE TITLE
write_back list index out of range

### ISSUE THREAD

**Issue by bluppfisk** [msiemens/tinydb#200]
My code updates an existing tinydb database as follows:
```
items = db.all()
for item in items:

    item.location = update_location(item.location) # do stuff with location entry 

db.write_back(items)
```
but this leads to an error:

> File "/usr/local/lib/python3.5/dist-packages/tinydb/database.py", line 503, in write_back
>     if sorted(doc_ids)[-1] > self._last_id:
> IndexError: list index out of range

Unsure what the problem might be.

**Comment by eugene-eeo** [comment]
Hi, I think it is because the database is empty. So when you call `write_back(items)`, you are calling it with an empty list of `items`. This raises an exception when `sorted(...)[-1]` is called. I will try to fix the problem in a PR.

**Comment by bluppfisk** [comment]
Hi Eugene, the database is most certainly not empty, neither the flat file nor the list of items. As you can see in the above code, the location is changed of every item (which would not work if the items were empty).

**Comment by eugene-eeo** [comment]
Can you do `print(items)` and show me what the output is?

**Comment by bluppfisk** [comment]
Hi Eugene, found the culprit. In the above code, I have written my own implementation on top of `db.all()` which returns a generator object rather than a list. The generator is of course exhausted by the time it's time to write the list back, so you're right, it is an empty list. I'll need to revisit that part.
