### ISSUE TITLE
changing order of OR query conditions changes the outcome

### ISSUE THREAD

**Issue by answerquest** [msiemens/tinydb#201]
I have a column carrying 1/0 values that may be stored as either string or number in the json. I'm keeping an `or` condition in my query to ensure that it works no matter. My query was failing,
```
db = TinyDB(dbfile, sort_keys=True, indent=2)
Item = Query()
tripsDB = db.table('trips')
# initial

tripsDB.contains( Item['direction_id'] == '0' or Item['direction_id'] == 0 )
> False
```
And of course, this evaluation is faulty. The db does contain elements having value '0' or 0 for that key.
But when i flipped the condition, it appeared to work:
```
tripsDB.contains(Item['direction_id'] == 0 or Item['direction_id'] == '0' )
> True
```
Putting extra brackets around each condition or changing single quotes to double has no effect on the outcome. I'm proceeding right now with what has worked for me (check for number first and string later), but this is a very weird quirk I'm seeing so inviting the developers to check it out.
PS: Please tell if the forum is a better place for posting this.

**Comment by eugene-eeo** [comment]
Hi, you have to use the `|` operator. So what you want is:

```
(Item['direction_id'] == '0') | (Item['direction_id'] == 0)
```

Since the `or` operator only returns booleans.

**Comment by answerquest** [comment]
Yikes, my apologies for this! I should have checked the documentation again before posting here. Relevant section : https://tinydb.readthedocs.io/en/latest/usage.html#query-modifiers . Closing this.
