### ISSUE TITLE
Is it ok to use the Table._last_id to retrieve the last row in a table?

### ISSUE THREAD

**Issue by Phuket2** [msiemens/tinydb#207]
@msiemens, I realise the attr _last_id starts with a dunder, so therefore normally you should avoid using it.  It seems too me there are 2 ways to get the last record.

1. print(db.all()[-1])
or
2. print(tbl.get(doc_id = tbl._last_id))

I would think that method 2 would be preferable over method 1 in terms of performance and memory usage.  Its just wether or not it's safe to use (i.e, its state will always correct)

**Comment by eugene-eeo** [comment]
They are both the same – the entire dataset is loaded into memory in both cases, the first one should be used since like you said, you don't use any _private_ attributes.

**Comment by msiemens** [comment]
@Phuket2 Just for curiosity: what is your use case for using the last row's ID?

**Comment by Phuket2** [comment]
@msiemens, it was no use case for me.  I just seen a question on StackOverFlow about how to do it. I have had a bit more time lately ad trying to learn more, so looking at peoples questions.
