### ISSUE TITLE
support for objects that have a to_dict method - enhancement

### ISSUE THREAD

**Issue by Phuket2** [msiemens/tinydb#210]
I hope this is not stupid enhancement request. But it seems like it would be nice to be able pass in addition to dicts to tinydb, but any object that defines a to_dict method that returns a dict. 
So I can have the below class and be able to pass it to insert, upsert, insert_multiple etc... hence tinydb would check to see if the object has a to_dict method if the passed object is not an instance of dict.  

Maybe there is a simpler way than this.  If so, I cant see it (however thats not suprising). I tried subclassing dict and trying to override "__getattribute__" in combination with "__getattr__" , I tried collections.UserDict. 
I couldn't get any these working 100% correctly.  The only approach that was close to ok that I could manage was to subclass dict and have a method defined to call the dicts update method. Of course this had to be called before passing it to tinydb. Very messy.  

Anyway, to my mind if tinydb supported the calling of a method (like to_dict_) on a passed object to get the data it would infinitely increase the flexibility of the users of tinydb when modelling their data/classes.  Well in my opinion.

Edit: obj.asdict() seems to be more correct.  It appears the new dataclass in py3.7 will have a asdict method 
  
```python
class Person:
    def __init__(self, *args, **kwargs):
        self.first_name = 'Ian'
        self.last_name = 'Smith'
        self.age = 25
    
    def to_dict(self):
        return {k:v for k,v in self.__dict__.items()}
```

**Comment by therden** [comment]
Implementing your request would violate the second principle of **The Zen of Python** ("Explicit is better than implicit.")  

Code using the proposed enhancement would give the false impression that tinydb was storing the object -- something that, by its essential nature, tinydb cannot do.

Rather than passing the object to insert, upsert, etc. and relying on tinydb to access "to_dict" or "asdict" methods as you propose, would it not be better to *explicitly* call the appropriate method for your object when using those and similar tinydb commands?

**Comment by msiemens** [comment]
> Edit: obj.asdict() seems to be more correct. It appears the new dataclass in py3.7 will have a asdict method

Regarding `dataclasses`: As far as I can tell, `asdict` is not a method of dataclasses but rather a helper function:

```
from dataclasses import dataclass, asdict

@dataclass
class C:
     l: List[Point]

p = Point(10, 20)
assert asdict(p) == {'x': 10, 'y': 20}
```

An option wold be to use [`tinydb-serialization`](https://github.com/msiemens/tinydb-serialization). Other than that, there's no real standard for serializing arbitrary python objects to dictionaries. I also agree with @therden that making something like `doc.as_dict()` a magic method that - if present - adds serialization would go against the ideal of explicitness.

**Comment by Phuket2** [comment]
Ok, thanks guys. I will close this issue.  Seems a shame to me that classes dont have a magic method built in that could be queried by developers of databases etc... Even better if it was bidirectional. 
Always seems to be this disconnect about an apps data represention it needs (the classes) for the app and then interacting with a module for data storage. Would be perfect to override a __serialisation__ method and just pass your objects to the Lib.  
I realise its only a few extra steps, but it always seems messy to me.   I am probably over simplifying it.
