### ISSUE TITLE
Unprofessional README

### ISSUE THREAD

**Issue by PyDever** [msiemens/tinydb#211]
Hey man! Great library.. your readme needs some work. Please consider putting your changelog in `/docs` and **not** in your readme. It is very annoying to have to see such a cluttered readme file. Again, great job on this project. It powers all of my `flask` app backends. I use it for everything.

**Comment by NGenetzky** [comment]
I would agree that the changelog doesn't belong in the readme; however, I do not think `/docs/` is the right place for it. I would put it at the root level and name it similarly to a popular project.

**Comment by PyDever** [comment]
agreed.

**Comment by NGenetzky** [comment]
I take back my statement about the location, because I notice you already have it at that location. I still believe it should be removed from the README. 

> I do not think /docs/ is the right place for it

**Comment by msiemens** [comment]
Should be fixed now :)
