### ISSUE TITLE
Question not an issue:

### ISSUE THREAD

**Issue by PyDever** [msiemens/tinydb#213]
I am super into the Flask eco-system and would like to no if I can build a flask extension off of your database framework. All credit for TinyDB still goes to you however I would get credit simply for making it easily accessible to Flask .

**Comment by PyDever** [comment]
Is this something you would be interested in helping with or should I just go solo?

**Comment by msiemens** [comment]
No problem! I won't be able to help as I currently don't have any spare resources, but I'd be glad to link to it in the readme and the extensions list 🙂

**Comment by PyDever** [comment]
Ok awesome. It will take a while to complete. Really all it is is wrapping the TinyDB and Query class into my own class, adding some Flask fluff, and then renaming it. It would only be a formality, simply to recognize your work.

**Comment by msiemens** [comment]
Awesome! I'll close this issue for now, feel free to open a new issue when you want it to be included in the extensions list.
