### ISSUE TITLE
tinydb sometimes generate the wrong  bracket?

### ISSUE THREAD

**Issue by MMmaomao** [msiemens/tinydb#215]
## can not load the json file because of the proper json format
![image](https://user-images.githubusercontent.com/4596276/40766496-3f82cc86-64e2-11e8-816b-53b8b3bb8034.png)
![image](https://user-images.githubusercontent.com/4596276/40766509-453ba4b8-64e2-11e8-8f05-195157945f15.png)

**Comment by MMmaomao** [comment]
manually fix it can work
![image](https://user-images.githubusercontent.com/4596276/40766589-8aeb93b0-64e2-11e8-9eeb-f8a3254c7c87.png)

**Comment by msiemens** [comment]
Hey, can you post some example code that generates the incorrect JSON?

**Comment by MMmaomao** [comment]
Hi, msiemens, sorry, I can't reproduce this issue. I only see this issue once.
I my case, I have multi process insert records to the same single database file.
So maybe the issue is because of multi process?

**Comment by msiemens** [comment]
Yes, as mentioned in [the docs](https://tinydb.readthedocs.io/en/latest/intro.html#why-not-use-tinydb) TinyDB doesn't support multithreading natively and doesn't support multiprocessing at all (without extending it to support file locking), see #84 and #113

**Comment by MMmaomao** [comment]
thanks
