### ISSUE TITLE
[IDEA] lock the file when database is opened.

### ISSUE THREAD

**Issue by Cologler** [msiemens/tinydb#219]
Since tinydb cannot access from multiple processes or threads, I think this is one way to keep the data safe.

reference:

https://github.com/WoLpH/portalocker

**Comment by msiemens** [comment]
You can implement this in your own Storage implementation 🙂 With the current architecture it's not possible to write a mechanism which does file locking for all possible Storage implementations as Storages might use an in-memory storage or even storing data on the network, where file locking won't make any sense

**Comment by Cologler** [comment]
JSONStorage is file system storage, the lock can implement inside it.

Markus Siemens <notifications@github.com> 于 2018年8月3日周五 21:36写道：

**Comment by msiemens** [comment]
That's correct. If you want, you can create such a storage as a separate repository and I can link it from the extensions list 🙂 Although I don't want to integrate this into the TinyDB core as it's another performance penalty for users who use single threaded database access.

**Comment by Cologler** [comment]
I don't think this has performance penalty since only lock file once in `JSONStorage.__init__()`.

The reason I have not create a PR for this is the lock require a external package `portalocker`, but the tinydb readme says: `has no external dependencies.`

**Comment by msiemens** [comment]
> I don't think this has performance penalty since only lock file once in JSONStorage.__init__().

In this case only one TinyDB instance could be open for the file at a time. In other words, as long as the file is opened at all, no other TinyDB instance can access it. If you want to allow interleaved access, you'll have to use the lock on every read and write operation with the overhead I already described.
