### ISSUE TITLE
Recently created records without processing redundant records

### ISSUE THREAD

**Issue by brock-b** [msiemens/tinydb#220]
Hi,

I have a need to poll TinyDB at set intervals (every 1 minute) and do some processing based on recently inserted records while ensuring that I dont process the same record twice.

I was thinking that I could use the row number (doc_id) at the table-level to do this but it doesn't appear that doc_id can be retrieved at the table level - only the db level.  Is this true?  I can sort of work around this by changing the DEFAULT_TABLE.

After changing DEFAULT_TABLE, I can retrieve doc_id this way but is this the best way to approach this problem?  I also dont appear to be able to retrieve a range of doc_ids >= x - is this possible?

```
from tinydb import TinyDB, Query
db = TinyDB('/tmp/test.json')
table_name = 'myTable'
table = db.table(table_name)
db.insert({'name': 'bob', 'dept': 'dept1', 'age': 20})
db.insert({'name': 'jim', 'dept': 'dept1', 'age': 40})
db.insert({'name': 'george', 'dept': 'dept2', 'age': 60})
TinyDB.DEFAULT_TABLE = table_name
db.get(Query().name == 'george').doc_id
3
db.get(doc_id=3)
{'age': 60, 'dept': 'dept2', 'name': 'george'}
db.get(doc_id>=2)
NameError: name 'doc_id' is not defined
# ideally this would have returned a list of:
{'name': 'jim', 'dept': 'dept1', 'age': 40}
{'name': 'george', 'dept': 'dept2', 'age': 60}
```

Appreciate any thoughts/suggestions you have.  Thanks and keep up the great work!

**Comment by msiemens** [comment]
I might also suggest using a proper SQL database like sqlite as TinyDB may be too constraining and not powerful enough for you
