### ISSUE TITLE
[FR] use doc_id as id if the dict has doc_id

### ISSUE THREAD

**Issue by Cologler** [msiemens/tinydb#221]
for example, the id of `db.insert({ 'doc_id': 'abc' })` should be 'abc':

``` json
{
    "_default": {
        "abc": {
            ......
        }
    }
}
```

**Comment by msiemens** [comment]
I don't think we want to allow this directly. That way users can overwrite arbitrary entries while expecting to insert new ones. Also, this would break any usage where someone already uses the `doc_id` field in their database.

**Comment by msiemens** [comment]
@Cologler What's your exact use case for this?

**Comment by Cologler** [comment]
Proposal: insert or replace exists item without enumerate all items

**Comment by Cologler** [comment]
It would not break anything if doc_id in both of key and entity:

``` 
"the Id": { "doc_id": "the Id"  }
```

**Comment by Cologler** [comment]
since tinydb already has a `upsert()` method:

when user call `db.insert({ 'doc_id': 'abc' })`, if the id already exists, raise a `KeyError`.

**Comment by eugene-eeo** [comment]
An alternative would be to have a special `_meta` attribute on `Query()`. (Inspired by Elasticsearch) For instance:

```python
user = Query()
db.get(user._meta.doc_id >= 2)
```

but this would require changing how the Query object works internally. I.e. it would have to receive now two parameters, the document currently being tested and the metadata associated with the document. In `Query._test_generate` we would have to change it to something like:

```python
...
        def impl(value, meta):
            try:
                # Resolve the path
                for part in self._path:
                    value = value[part]
            except (KeyError, TypeError):
                return False
            else:
                return test(value, meta)
...
```

To differentiate between the new `Query()._meta` (query on the _metadata_) and an actual query on the `_meta` field, we would use `Query()['meta']` to mean the latter.
