### ISSUE TITLE
[FR] add encoding argument for JSONStorage

### ISSUE THREAD

**Issue by Cologler** [msiemens/tinydb#222]
Currently, JSONStorage use `open(..., encoding=None)` to open the json file. 

But I try to use utf-8 encoding.

**Comment by msiemens** [comment]
Hey @Cologler, could you provide an example what you write to the database, what the database file looks like and which OS and Python version you use?

As far as I can tell, Python uses the default encoding (as determined by `locale.getpreferredencoding()`) which in many cases is UTF 8 (but Windows for example may differ). Now, non-ASCII characters will be escaped unless passing `ensure_ascii=False` to the TinyDB constructor:

```python
db_file = tmpdir.join('test.db')
db = TinyDB(str(db_file), ensure_ascii=False)

# Write contents
db.insert({'a': 'ברי צקלה'})

assert db.all() == [{'a': 'ברי צקלה'}]
assert db_file.read() == '''{"_default": {"1": {"a": "ברי צקלה"}}}'''
```

**Comment by Cologler** [comment]
In my windows, `locale.getpreferredencoding()` return `cp936`.

I use some editor to edit the json file (save to utf-8), and tinydb cannot open it agains.

**Comment by msiemens** [comment]
Okay, fair enough, that I can try to reproduce somehow :)

**Comment by msiemens** [comment]
@Cologler Can you post the exact error that occurs while reading a UTF-8 database file modified from an external editor? I'm still trying to come up with a test case for the test suite and it always works without any modifications…

**Comment by msiemens** [comment]
As far as I can tell, Python's JSON module always uses UTF-8 by default, so I don't know why this wouldn't work

**Comment by Cologler** [comment]
The external json editor is not ensure asscii, so you can simple to add test case:

``` py
db_file = 'test.db'
with tinydb.TinyDB(db_file) as db:
    db.insert({'a': 'ברי צקלה'})

with open(db_file, 'r', encoding='utf-8') as fp:
    data = json.loads(fp.read())

with open(db_file, 'w', encoding='utf-8') as fp:
    fp.write(json.dumps(data, ensure_ascii=False))

# should not raise:
tinydb.TinyDB(db_file)
```

**Comment by msiemens** [comment]
@Cologler Funny, your example already works for me, both on Python 2 and 3…

**Comment by msiemens** [comment]
> @msiemens why does the tag v3.11 in github repo not match v3.11 on pypi?

I just forgot to actually change the version number when tagging the release. I then adjusted the version number and actually uploaded the release to PyPI.

**Comment by Cologler** [comment]
@msiemens 

Sorry for the wrong test case.

Json use `utf-8` encoding by default, but https://github.com/msiemens/tinydb/blob/ef654e74b361ebb659bda80cf1c7238eb0ac02d2/tinydb/storages.py#L91
already decode the file using system encoding (not `utf-8`).

![snipaste_2018-09-14_16-30-51](https://user-images.githubusercontent.com/10906962/45539488-809b2580-b83c-11e8-820f-98b87703a1b0.png)

**Comment by Cologler** [comment]
update test case:

``` py
import tinydb
import json
import os

db_file = 'test.json'
record = {'a': 'ברי צקלה'}

with tinydb.TinyDB(db_file) as db:
    db.purge()
    db.insert(record)

with open(db_file, encoding='utf-8') as fp:
    model = json.load(fp)

with open(db_file, 'w', encoding='utf-8') as fp:
    fp.write(json.dumps(model, ensure_ascii=False))

with tinydb.TinyDB(db_file) as db:
    items = list(db.all())
    assert len(items) == 1
    assert items[0]['a'] == record['a']
```

**Comment by msiemens** [comment]
Thanks for the test case. Now, I only can get it to fail with Python 2 since when using Python 3, it always should use UTF-8 as a default. But when using Python 2, I can't get the test to pass even when adding an `encoding` parameter to the JSONStorage and opening the file with `codecs.open(…, encoding=…)`. So basically, with Python 3 I cannot reproduce this, while with Python 2 I can't seem to fix this…

**Comment by Cologler** [comment]
@msiemens 
> since when using Python 3, it always should use UTF-8 as a default

is not true. the default encode page is 936 (utf-8 should be 65001) on my PC (windows 10). 

You can see the console output for example:

![](https://user-images.githubusercontent.com/10906962/45539488-809b2580-b83c-11e8-820f-98b87703a1b0.png)

**Comment by Cologler** [comment]
`sys.getfilesystemencoding()` is not the default encoding when open a file.

https://stackoverflow.com/questions/36303919/python-3-0-open-default-encoding

**Comment by msiemens** [comment]
Ah, good to know! Then I was wrong about that. Do you know a way to change the encoding Python 3 uses for opening files so I can add something to the test suite that covers this issue?

**Comment by Cologler** [comment]
Add `encoding=None` argument for JSONStorage and pass it to `open()` could fix this without break change.
Sorry for that my test case won't work on linux & mac (travis-ci does not support windows yet).

**Comment by msiemens** [comment]
(Note: this is still waiting for #238 which has been reviewed and still requires some small modification)
