### ISSUE TITLE
Validate against json schema

### ISSUE THREAD

**Issue by NicoHood** [msiemens/tinydb#225]
Hi, ever thought about adding json schema support? It would be nice to check on every insert if the new content still validates against a defined json schema. This way you can avoid errors in the database very easily without much coding.

**Comment by eugene-eeo** [comment]
I think this would be better suited to a plugin. I like the idea though, it's just that adding JSON schema support to the core would most likely clog up things a little.

**Comment by claell** [comment]
I am also interested in seeing this, but as it seems this is not very popular.

**Comment by msiemens** [comment]
If someone writes a TinyDB extension I'll be happy to link to it from the extensions list, but I myself don't have the capacity to work on a JSON schema validation module
