### ISSUE TITLE
Implement `__repr__` methods for classes `TinyDb`, `Table`, `Query` etc.

### ISSUE THREAD

**Issue by cool-RR** [msiemens/tinydb#226]

**Comment by msiemens** [comment]
@cool-RR Any suggestions what `__repr__` should contain for these classes? Do you know what other databases do here with Python?

**Comment by cool-RR** [comment]
Table should have the table name, maybe the number of entries. Tinydb
should have the number of tables. Query should have the query.

**Comment by msiemens** [comment]
@cool-RR Would you be willing to write a Pull Request for this?

**Comment by cool-RR** [comment]
No, sorry. I understand if this ticket will be closed.

**Comment by msiemens** [comment]
Okay, I've added the `contributions-welcome` tag and am happy to accept pull request if anyone wants to implement this 🙂

**Comment by piraces** [comment]
Hello! I would like to participate and try implement it. So I will work on it if you’re open 🙂

**Comment by mrfunnyshoes** [comment]
Hello, is this still open? I might wanna contribute...

**Comment by cool-RR** [comment]
I believe it is, go for it Edgar!

**Comment by Xarvalus** [comment]
Hello 🙂

I have opened [WIP] PR on your issue, sorry for getting in your way @mrfunnyshoes with my contribution, I was investing some time for this case since a few days before.

If you are willing to help with the matter feel free to contribute within https://github.com/msiemens/tinydb/pull/229, definiently there will be more work to do 😄

**Comment by msiemens** [comment]
Well, now we have two PRs for this 🙈 @mrfunnyshoes Would you be interested in doing a code review for the patch by @Xarvalus (on #229)?

**Comment by msiemens** [comment]
And I really appreciate both contributions and don't want anyone to feel like their work is not valued, even if it's a 'small' thing like `__repr__`! The PR by @Xarvalus is more exhaustive and covers testing too, that's why inclined towards this one.
