### ISSUE TITLE
Single write multiple read

### ISSUE THREAD

**Issue by wiryonolau** [msiemens/tinydb#228]
Hi, is it safe to read from multiple thread without cache mechanism ?

I use this as a backend of my GTK app, there will be a lot of read from multiple thread at once.
For writing I dedicate a single thread that use a thread queue, all writing command will added to the queue first, this should be safe.

**Comment by msiemens** [comment]
Hey @wiryonolau! Single write multiple read access is safe in the sense that it probably won't lead to data corruption, but it may crash (throw exceptions) when reading from a partially written file.

**Comment by wiryonolau** [comment]
I can live with exception
