### ISSUE TITLE
how to do pagination with tinydb?

### ISSUE THREAD

**Issue by yyz1989** [msiemens/tinydb#234]
Hi,

Just a simple question. Does anyone know how to use something like limit and offset of control pagination of the results? I didn't find it in the documentation. Or I can use slice notation?

Many thanks for any hint.

Best regards,
Yang

**Comment by msiemens** [comment]
Hey @yyz1989, TinyDB doesn't have `LIMIT` or `OFFSET` controls like SQL-based databases. For small data sets you can use Python's slice notation like this:

```
offset = 10
limit = 5
results = db.search(queries…)[offset:offset + limit]
```

If you actually have a lot of data where retreiving all search results on every search is a performance problem, it's probably better to switch to a relational database like `sqlite` which is also included in Python.

**Comment by patarapolw** [comment]
If NoSQL, maybe MongoDB or [MontyDB](https://github.com/davidlatwe/MontyDB) would be an answer.
