### ISSUE TITLE
JSONStorage __init__() modifies database Modify and Change times

### ISSUE THREAD

**Issue by sserrata** [msiemens/tinydb#235]
I noticed that `touch(path, create_dirs=create_dirs)` is called during `JSONStorage` initialization which executes `os.utime(fname, None)` on the database file. I'm looking for an explanation as to why this is necessary as it appears to be part of the initial commit?

I wouldn't expect the database file `modify` or `change` times to update unless a database operation is performed that actually modifies the file or the file permissions are altered.

**Comment by msiemens** [comment]
Hey @sserrata, this behavior has been there since the initial commit in b01cf23013c745c551f6bdffc78d737bf8e5f1f2 and no one really bothered to change it so far 🙃 Would you be willing to help out with a pull request?

**Comment by sserrata** [comment]
Hi @msiemens - sure, I'd be honored to submit a PR :smile:.

**Comment by msiemens** [comment]
Closing this as it has been fixed in #242 🙃
