### ISSUE TITLE
Refactor isinstance(document, dict) check in Table._get_doc_id()

### ISSUE THREAD

**Issue by caichinger** [msiemens/tinydb#246]
First and foremost: I really like this project and its great documentation (as well as test coverage), thank you! :)

**Description**
When inserting elements into a table through [`Table.insert()`](https://github.com/msiemens/tinydb/blob/cc7647ad6b933efc8a365d0c61d67f8cee1194ca/tinydb/database.py#L434) or [`Table.insert_multiple()`](https://github.com/msiemens/tinydb/blob/cc7647ad6b933efc8a365d0c61d67f8cee1194ca/tinydb/database.py#L449), [`Table._get_doc_id()`](https://github.com/msiemens/tinydb/blob/cc7647ad6b933efc8a365d0c61d67f8cee1194ca/tinydb/database.py#L381) gets called. This call involves the condition [`isinstance(document, dict)`](https://github.com/msiemens/tinydb/blob/cc7647ad6b933efc8a365d0c61d67f8cee1194ca/tinydb/database.py#L382).

**Question/Suggestion**
It seems to me that this check is rather strict and that checking for a dict-like
interface might suffice.

Changing the condition to `isinstance(document, MutableMapping)` (where `from collections.abc import MutableMapping`) would allow one to easily implement custom `dict`-like container/wrapper for documents. In my case: I want to implement a simple container class representing a document
that guarantees a certain structure (like a template).

What do you think?

**Notes**
It is of course possible to subclass dict but this is tends to be a rather evolved
procedure. See these discussions:
- https://stackoverflow.com/questions/3387691/how-to-perfectly-override-a-dict
- https://stackoverflow.com/questions/2390827/how-to-properly-subclass-dict-and-override-getitem-setitem

For Python 3, the test suite does not discover any issues arising from this change (though I have not taken a look at the interals). See the respective PR #245.
If you think this refactoring makes sense, I will take a look at a Python 2 and Python 3 compatible solution.

**Comment by msiemens** [comment]
@caichinger Thanks for the kind words and for the suggestion! I think checking for `collections.abc.MutableMapping` would be a nice addition, I simply didn't think of that use case when implementing the check 🙃

**Comment by caichinger** [comment]
@msiemens if you feel like taking a look, #245 is green.

**Comment by caichinger** [comment]
Closed through #245
