### ISSUE TITLE
update API documentation for Query

### ISSUE THREAD

**Issue by yyz1989** [msiemens/tinydb#253]
Hi,

The examples listed at https://tinydb.readthedocs.io/en/latest/api.html#tinydb-queries about using binary operators are wrong. 

The examples are:

`db.search(where('field1').exists() & where('field2') == 5) # Binary AND`
`db.search(where('field1').exists() | where('field2') == 5) # Binary OR`

but bitwise operators evaluate before logical operators, so they have to be

`db.search((where('field1').exists()) & (where('field2') == 5)) # Binary AND`
`db.search((where('field1').exists()) | (where('field2') == 5)) # Binary OR`

Best regards,
Yang

**Comment by msiemens** [comment]
Thanks for reporting! This is fixed in fb43ae946aa145f7722389213a1a07427ff7ba12 🙂
