### ISSUE TITLE
Direct access to the underlying storage

### ISSUE THREAD

**Issue by msiemens** [msiemens/tinydb#258]
Raised in https://forum.m-siemens.de/d/56-explicitly-flush-with-caching-middleware:

Sometimes it's useful to have direct access to the storage a `TinyDB` instance uses if the storage exposes additional methods/properties besides `read()` and `write()`. For example the `CachingMiddleware` has a `flush()` method, which one cannot call manually without using the internal `db._storage` variable.

Maybe we could expose the storage using a read-only property on `TinyDB` instances.

@eugene-eeo What do you think?

**Comment by eugene-eeo** [comment]
@msiemens yeah I don't see any issues with this. I guess we have to add a warning to the docs that if you access `storage` then you need to know what you're doing.
