### ISSUE TITLE
Can't "remove" with a working query

### ISSUE THREAD

**Issue by etienne-napoleone** [msiemens/tinydb#261]
Hello!
Just picked up tinydb recently, but I got some troubles removing some entries.
A query that works for search doesn't work for removing.

```
>>> s.db.search(s.key.network.id == '114')
[{'network': {'id': '114', 'name': 'ok', 'rpc': 'dac', 'ticker': 'mkay'}}]
>>> s.db.remove(s.key.network)
[]
>>> s.db.search(s.key.network.id == '114')
[{'network': {'id': '114', 'name': 'ok', 'rpc': 'dac', 'ticker': 'mkay'}}]
```

-----------

using v. 3.12.2
no special configuration, just a json file storage

**Comment by msiemens** [comment]
Thanks for the report, @etienne-napoleone! Right now I cannot reproduce this issue. What's the content of the `s.key.network.id` and `s.key.networks` variables you use?

**Comment by etienne-napoleone** [comment]
so `key` is an instance of `Query`:
`self.key = tinydb.Query()`

So in this case, should be the equivalent, afaik, of:
```python
q = tinydb.Query()
db = TinyDB('db.json')
db.search(q.network.id == '114')  # results
db.remove(q.network.id == '114')  # no deletion
```

**Comment by msiemens** [comment]
Thanks for the clarification, @etienne-napoleone. Unfortunately, even with the code from your reply I cannot reproduce this error. Is it possible that some other process also writes to the database file?

**Comment by etienne-napoleone** [comment]
I guess we can close that, no idea where it came from but might be a mistake on my side somehow ¯\_(ツ)_/¯

**Comment by msiemens** [comment]
@mastercoms If you can reproduce this, can you please create a new issue? Ideally with the steps to reproduce this behavior 🙂

**Comment by mastercoms** [comment]
I'll try to figure it out
