### ISSUE TITLE
Add support for ordered json databases (using OrderedDict)

### ISSUE THREAD

**Issue by lnv42** [msiemens/tinydb#267]
Hi, for another project, i needed to have some fully ordered DBs.
So i made few modifications (https://github.com/lnv42/tinydb) to add this support while you give argument : "object_pairs_hook=collections.OrderedDict" to TinyDB() (directly passed to json.load)
it may have some impact on performance, probably positive in most case with modern python3 but maybe negative in some specifics ones...
Are you interested into merging that or not ?
(It works for me but I did not run/fixe any test yet nor tried it on Python2.)

**Comment by msiemens** [comment]
Thanks for the proposal @lnv42! I don't feel like this is something that belongs into the TinyDB core, I'm afraid. It's definitely useful for some applications, but I'm not sure how to include something like this without making the API much more complex for all users, even those who don't need thisa
