### ISSUE TITLE
Add json support to Query, and where functionalities.

### ISSUE THREAD

**Issue by nihilist-banana** [msiemens/tinydb#268]
I think we should have a json support for creating queries in the Data Base.
This would streamline a lot of the complex queries.
I am basically thinking of supporting two types:
1. A dict passed with a common operator like `and` or `or`
2. A nested json like object specifying the operator similar to the structure a query object has at the end being evaluated.

**Comment by nihilist-banana** [comment]
If possible, assign this to me, @msiemens.

**Comment by msiemens** [comment]
@nihilist-banana Do you mean storing queries inside the database? Or a query syntax like the one MongoDB uses?

**Comment by nihilist-banana** [comment]
@msiemens, sorry for the late reply, I believe a mongo query syntax would be overkill. I was talking about a way so that people can make combination queries in one go. Maybe I will just give it a try and talk when I've figured it out a bit more?

**Comment by msiemens** [comment]
Well, TinyDB has `AND` and `OR` operations, so it's possible to combine queries:

```python
# And:
(where('a') == 1) & (where('b') == 2)

# Or:
(where('a') == 1) | (where('b') == 2)
```

Do you mean something like this?
