### ISSUE TITLE
Reading an existing json file written without using TinyDB

### ISSUE THREAD

**Issue by s1782662** [msiemens/tinydb#269]
Hi, Is it part of system behaviour to append "_default": {} when reading an exiting json file which was not written using TinyDB

For eg 
       

         `  
       with open(os.path.join(data_dir,'{}.json'.format(name)),'w') as file :
            json.dump(
                {DEFAULT_TABLE: {
                    1:{
                        'name':'climbing',
                        'category':'sport'
                    }
                }},file)`

 Now my file contains 
 `  {"standard": {"1": {"category": "sport", "name": "climbing"}}}`

And if i read the above file using TinyDB, i get 
`{"_default": {}, "standard": {"1": {"category": "sport", "name": "climbing"}}}`

**Comment by s1782662** [comment]
Hi, This is fixed. I didn't know that I have manually set the Default table.

**Comment by msiemens** [comment]
Ah, glad you were able to fix it!
