### ISSUE TITLE
ConcurrencyMiddleware in Documentation

### ISSUE THREAD

**Issue by david-ml** [msiemens/tinydb#272]
The documentation says TinyDB ships with both CachingMiddleware and ConcurrencyMiddleware: https://tinydb.readthedocs.io/en/v1.4.0/usage.html#middlewares

Looks like ConcurrencyMiddleware was removed long ago per #18

**Comment by msiemens** [comment]
Hey! That's the documentation for version 1.4.0 which indeed did ship with the `ConcurrencyMiddleware` 🙃 You can always find the latest documentation at https://tinydb.readthedocs.io/en/latest/
