### ISSUE TITLE
Why is doc_id not in all()

### ISSUE THREAD

**Issue by dradux** [msiemens/tinydb#273]
Why is doc_id not in all() (e.g. table.all()) results? This makes it difficult to fetch a large set of data (hence the all()) and display to the user allowing the user to see the unique id to perform subsequent queries with.

Example:
```
db.table("history").insert(
        {
            "date": rundts,
            "runtime": runtime,
            "result": {"status": ae["code"], "message": ae["message"]},
            "calling_params": calling_params,
            "derived_params": rc_clean(rc),
            "image_name": rc["build"]["repository"]["value"],
            "image_tag": rc["build"]["version"]["value"],
        }
    )

```
If I now show all() records of the table history I get the following:
```
print(db.table("history").all())
...
[{'date': '2019-07-17 15:41:31 -04:00', 'runtime': 0.002065, 'result': {'status': 1, 'message': 'Request canceled'}, 'calling_params': '--build-version=1.7.19', 'derived_params': '', 'image_name': 'example.com', 'image_tag': '1.7.19'}]  #note doc_id: is not in result
```
If I loop over history I can get the doc_id:
```
for r in history:
    print("{0}: {1}".format(r.doc_id, r))
...
1: {'date': '2019-07-17 15:41:31 -04:00', 'runtime': 0.002065, 'result': {'status': 1, 'message': 'Request canceled'}, 'calling_params': '--build-version=1.7.19', 'derived_params': '', 'image_name': 'example.com', 'image_tag': '1.7.19'}
```
Is there a way to get `doc_id` in the all() resultset or can this be added?

**Comment by msiemens** [comment]
Hey @dradux,

I'm not exactly sure what you mean. `TinyDB.all()` returns a list of `Document` objects, where each one has a `doc_id` attribute. It's just not printed as `Document` is a subclass of `dicts` and they use `dict`'s `__str__` implementation.
