### ISSUE TITLE
How to update nested field without overwriting the rest of the fields?

### ISSUE THREAD

**Issue by Eido95** [msiemens/tinydb#274]
Hi there, I'll start with an example:
```python
>>> from tinydb import TinyDB, Query
>>> from tinydb.operations import set
>>> db = TinyDB('db.json')
>>> User = Query()
>>> db.insert({
...     'name': 'John',
...     'age': 22,
...     'eyes': {
...         'color_type': 6,
...         'total': 1
...     }
... })
1
>>> db.search(User.name == 'John')
[{'name': 'John', 'age': 22, 'eyes': {'color_type': 6, 'total': 1}}]
>>> db.update({'total': 2})
[1]
>>> db.search(User.name == 'John')
[{'name': 'John', 'age': 22, 'eyes': {'color_type': 6, 'total': 1}, 'total': 2}] 
# Second field being added, instead of updating the existing one.
>>> db.update(set('total', 3))
[1]
>>> db.search(User.name == 'John')
[{'name': 'John', 'age': 22, 'eyes': {'color_type': 6, 'total': 1}, 'total': 3}]
# Second field being updated, instead of updating the first one.
```
I try to update `total` field under `eyes` field  - without updating `color_type` field.
Instead of updating the existing `total` field under `eyes` field, a second `total` field being added to the root for document.
I know that if I would update the entire `eyes` field it will work, but I want to know if it possible to do it without overwriting the rest of the nested fields.

Much thanks.

**Comment by msiemens** [comment]
Hey @Eido95,

I think the easiest way is to use a custom operation like this:

```python
def set_nested(path, val):
    def transform(doc):
        current = doc
        for key in path[:-1]:
            current = current[key]

        current[path[-1]] = val

    return transform

db.update(set_nested(['eyes', 'total'], 2))
```

Basically, you define an operation that receives a path and traverses the nested `dict` objects until it meets the final object, where the update is performed.

Does this work for you?

**Comment by Eido95** [comment]
@msiemens thank you for your reply.

`set_nested` function you provided does exactly what I needed - much thanks!

In current case, that updating nested fields is not supported out-of-the-box, the correct way to structure a _basic_ document fields is with only 1 level of nesting (i.e. on document root level)?

**Comment by msiemens** [comment]
In general TinyDB should work fine with nested documents, it's supported by TinyDB's query language. It's just updating nested fields that may not be straight-forward all the time. I guess it would be easier to just fetch a document, update it and store the new document in place of the old one.
