### ISSUE TITLE
function to update Table._last_id when using MultiProcessing

### ISSUE THREAD

**Issue by dmtvanzanten** [msiemens/tinydb#276]
I'm using TinyDB with TinyMP and MultiProcessing.Pool (and MultiProcessing.Lock) which runs without process when updating. But when inserting/upserting documents I get into problems with the doc_id, i.e. different processes insert documents with the same doc_id. Consider the example below:

```python
rdb = tinydb.TinyDB('db.mpdb', storage=tinymp.MsgPackStorage)
table = rdb.table('fits', cache_size=0)

def task(_id):
    print('RUNNING id: {}'.format(_id))
    
    lockdb.acquire()
    try:
        entry = table.get(doc_id = _id)    
    finally:
        lockdb.release()
    
    # do stuff
        
    lockdb.acquire()
    try:
        print("SAVING id: {}".format(_id))
        # table._init_last_id(table._read()) # possible fix...
        _nid = table.insert(dict(entry))
        print("DONE id: {}, new id: {}".format(_id, _nid))
    except Exception as err:
        print(err)
    finally:
        lockdb.release()

def init(l):
    global lockdb
    lockdb = l

if __name__ == '__main__':
    import multiprocessing as mp
    
    entries = table.search(tinydb.Query().id == [])
    if not entries:
        raise RuntimeError('Not entries found.' )
    
    nproc = min(12, len(entries))
    results = []
    with mp.Pool(processes=nproc, initializer=init, initargs=(mp.Lock(),)) as pool:
        for item in entries:
            result = pool.apply_async(task, (item.doc_id,))
            results.append(result)
                
        for result in results:
            result.wait()
```

I think the the problem is because the table class only indexes the documents present during initialization. This happens for each process at the beginning. From this point each process only tracks the insertions done by itself and is therefor unaware of the actual documents present. 

Forcing the table the re-index just before inserting/upserting fixes the problem. 
`table._init_last_id(table._read())`
Would it be possible to add a keyword argument to the insert/upsert method to force re-indexing?

**Comment by msiemens** [comment]
Hey @dmtvanzanten,

Thanks for you request! I'm torn about adding a keyword to force updating the latest ID cache. I'd rather have the API as simple as possible instead of adding keyword arguments that change the whole behavior.

I think a better solution would be to create a custom table class that reloads the latest ID by overwriting `Table._get_next_id` to load the latest ID from the most recent data. I haven't tested it but I think something like this should point you in the right direction:

```python
class MyTable(Table):
    def _get_next_id(self):
        return max(i for i in self._read()) + 1
```
