### ISSUE TITLE
Is there a way to better handle missing values for queries using test

### ISSUE THREAD

**Issue by willthames** [msiemens/tinydb#277]
I'm trying to work with kubernetes label selectors

Two possible label selectors are `!label` - find all resources without the label `label`, and `label notin (val1, val2)` which should find all resources without the label `label` or where the `label` is set to something other than `val1` or `val2`.

Looking at [the code](https://github.com/msiemens/tinydb/blob/master/tinydb/queries.py#L137-L138), if `labels` isn't even in the resource definition, then 
```
query = (metadata.labels.test(labels_match_selectors, selectors))
```
returns `False` even though I would like it to find all resources with no labels at all in the `notin` and `!label` cases.

I understand the implementation decision (there is no obvious better thing to do for ever case), but wonder if there's any way to work around it without having to manipulate the underlying data.

So some of the ways I'd consider would be some way of setting a default value (e.g. `metadata.labels.default({}).test`) or passing a sentinel value to `test` if the value is not present. I realise for backward compatibility that that would have to be optional.

Hopefully I've just missed an easy alternative.

**Comment by msiemens** [comment]
Hey @willthames,

If I understand you correctly, you want get all documents which have either no labels or the labels specified by `labels_match_selectors(doc, selectors)`, is that correct?

I think you could use a custom test function like this one:

```python
def labels_match_selectors(doc, selectors):
    if 'labels' no in doc:
        return True
    
    ... # Your labels_match_selectors logic using doc['labels']

query = (metadata.test(labels_match_selectors, selectors))
```

**Comment by willthames** [comment]
@msiemens thanks for the response - that definitely seems like something that could well work, thank you! I'll let you know how it goes and close the ticket if it solves my problem.

**Comment by willthames** [comment]
Thanks @stale for the reminder! I did try the above technique and it definitely fixed my problem. And thanks @msiemens for the advice!

**Comment by msiemens** [comment]
I'm glad I was able to help 🙂
