### ISSUE TITLE
How to disable caching on default table?

### ISSUE THREAD

**Issue by bengineer19** [msiemens/tinydb#278]
Hi!

Firstly, thanks for making an awesome project.
From the docs, I can see that it's possible to disable caching on a particular table using `cache_size=0` in the constructor of `db.table()`.

But what if I'm using the default table? Is it possible to disable query caching? 

Thanks!

**Comment by msiemens** [comment]
Hey @bengineer19,

That's an interesting question! Seems like right now there is no way to disable caching on the default table using the public API.

A quick workaround would be to set `db._table._query_cache.capacity = 0`. But that's not a really clean solution. I gues we could add an attribute like `TinyDB.DEFAULT_TABLE_KWARGS` which can specify arguments to the Table class like this:

```python
TinyDB.DEFAULT_TABLE_KWARGS = {'cache_size': 0}
```

What do you think?

**Comment by bengineer19** [comment]
Yep I think that seems reasonable. 
It's definitely an edge case, so as long as there's some way to "forward" parameters from `TinyDB()` to `self._table = self.table(default_table)` I think it should work.

**Comment by msiemens** [comment]
I've created a pull request at #279, I'll need to think about what the best API is for this feature 🙃

**Comment by msiemens** [comment]
I've now published this feature in the new TinyDB v3.15.0 🙃

**Comment by bengineer19** [comment]
Awesome - thanks!
