### ISSUE TITLE
How to combine n "&" queries into one db.search(queries)?

### ISSUE THREAD

**Issue by hdm-dt-fb** [msiemens/tinydb#280]
First of: Thank you so much for the amazing TinyDB project!
I use it in a few projects and enjoy it quite a bit!

Now I came across this case where I got n queries, which I would like to combine in one search.
The documentation demonstrates this nicely for two queries:
```python
>>> # Logical AND:
>>> db.search((User.name == 'John') & (User.age <= 30))
```
Is there a canonical way to do the same for n queries?
I did not find this case in the already existing issues - hopefully I did not read over it and also sorry if this is actually obvious.

I am able to accumulate the QueryImpl objects and operators: 
```python
queries = [
    QueryImpl('==', ('foo',), '1'), 
    "&",
    QueryImpl('==', ('bar',), '10'),
    "&",
    QueryImpl('==', ('baz',), '100'),
]
found = db.search(queries)
```
How would I send them with the "&" or "|" operators to one following db.search in a sane way?

**Comment by msiemens** [comment]
Hey @hdm-dt-fb, sounds like you could use Python's `reduce` operator ([built-in](https://docs.python.org/2/library/functions.html#reduce) for Python 2, in [`functools.reduce`](https://docs.python.org/3/library/functools.html#functools.reduce) for Python 3). You can apply it like this:

```python
queries = [
    QueryImpl('==', ('foo',), '1'), 
    QueryImpl('==', ('bar',), '10'),
    QueryImpl('==', ('baz',), '100'),
]

combined_query = reduce(lambda a, b: a & b, queries)
found = db.search(combined_query)
```

This should create a query in `combined_query` which is the `&` combination of all queries in `queries`.

Does this work for you?

**Comment by hdm-dt-fb** [comment]
Hi @msiemens thank you for the prompt answer 
and suggestion with the functools! 
(I should dig more into functools it seems)
**Works like a charm - thank you so much!! (-:**

**Comment by msiemens** [comment]
Awesome, I'm glad I could help 😊
