### ISSUE TITLE
howto delete an k/v pair in a value list

### ISSUE THREAD

**Issue by adrianchi** [msiemens/tinydb#281]
Hi, i am trying to use tinyDB for a personal learning project, but after two days of hitting my head to the wall i sill can't figure this out...

Having this structure 
```
db.all()
[{'customer': 'c1', 'sites': [{'site': 'site1'}, {'site': 'site2'}]}]
```

how can i delete one of the elements, as an example **site1**, to get this output
`[{'customer': 'c1', 'sites': [{'site': 'site2'}]}]`

And going further, tinyDB could be usefull if i want to maintain this kind of structure?

**Customer X -> sites of the customer -> devices per site**

```
{'customer': 'c1', 'sites': [
    {'site': 'site1',
     'devices':[
        {'ip':'1.1.1.1', 'user':'pepe'}
        {'ip':'2.2.2.2', 'user':'pepe'}],
    {'site': 'site2'}]}]
     'devices':[
        {'ip':'3.3.3.3', 'user':'pepe'}
        {'ip':'3.3.3.3', 'user':'pepe'}]

{'customer': 'c2', 'sites': [
    {'site': 'site1',
     'devices':[
        {'ip':'1.1.1.1', 'user':'pepe'}
        {'ip':'2.2.2.2', 'user':'pepe'}],
    {'site': 'site2'}]}]
     'devices':[
        {'ip':'3.3.3.3', 'user':'pepe'}
        {'ip':'3.3.3.3', 'user':'pepe'}]
```

**Comment by adrianchi** [comment]
I added this function to the operations.py and its working fine.
```
def remove(field, n):
    """
    Remove n from a given field/nested list from the document
    """
    def transform(doc):
        doc[field].remove(n)

    return transform
```

I will keep checking as i go deeper in the nesting. And if it works may i propouse this addition to the code?

**Comment by adrianchi** [comment]
The code will not work with nested fields, going to tables like a traditional DB is the solution. And creating individual tables for customer, sites, and devices

**Comment by msiemens** [comment]
Hey @adrianchi 

It seems like your data is highly relational. In this case you'd probably be better served with a relational database. I'd suggest looking into Python's [`sqlite`](https://docs.python.org/3.7/library/sqlite3.html) support. The main advantage is that with `sqlite` the database makes sure all references are correct and supports native access for accessing and manipulating related entries. You can do this yourself with TinyDB of course with the advantage of higher flexibilty but the downside of having to write this logic yourself.

Cheers!

**Comment by adrianchi** [comment]
hi @msiemens 

This is my first time using a DB with Python, and i was amazed about tinyDB, super interesting and easy to use what you have build here, congrats!
I haven't tried sqlite yet, i didn't wanted to go into the scripting for that when tinyDB was much more easier to work with. Of course there some tradeoff like you mention, but it is still cool to learn something new and i liked the fact of the JSON format right away.
Indeed yesterday I easily did the scripting for keeping the tables synchronized manually (ADC). It works like a charm :)
I didn't have previous experience with DOC oriented DB, now I've got my first contact by using tinyDB and it was easy to use.
So, thanks for answering, suggesting, and keep doing what you do ;)

Cheers!

**Comment by msiemens** [comment]
>  Indeed yesterday I easily did the scripting for keeping the tables synchronized manually (ADC). It works like a charm :)

It's great to hear you found a way to make it work 😊
