### ISSUE TITLE
Push latest release to conda-forge and pypi

### ISSUE THREAD

**Issue by dcflachs** [msiemens/tinydb#282]
Forgive me if this isnt directly something you control, but i have been hoping to see your latest release v3.14.2 land in conda-forge.

**Comment by msiemens** [comment]
That's my fault! I forgot to push v3.14.2 to PyPI 🙈 I've pushed it now and I expect conda-forge to be updated soon 🙂 Sorry for the inconvenience!

**Comment by msiemens** [comment]
The feed update has been merged now 🙂

**Comment by msiemens** [comment]
Closing this as the update has been merged into the Conda Forge feed. Feel free to reopen if there are issues related to this.

**Comment by dcflachs** [comment]
Thank you @msiemens
