### ISSUE TITLE
How can I call tinydb in another folder?

### ISSUE THREAD

**Issue by YunzhaoLu** [msiemens/tinydb#287]
I just git clone the source code, and I want to use tinydb outside the source folder. When I run python3
$ python3
Python 3.6.6 (default, Mar 29 2019, 00:03:27)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tinydb.tinydb import TinyDB,where
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/kaldi/kaldi-websocket-python/tinydb/tinydb/__init__.py", line 28, in <module>
    from .database import TinyDB
  File "/usr/local/kaldi/kaldi-websocket-python/tinydb/tinydb/database.py", line 7, in <module>
    from tinydb.table import Table, Document
ModuleNotFoundError: No module named 'tinydb.table'

How can I resolve the relative folder issue?

Thanks,
Luke

**Comment by msiemens** [comment]
Hey, seems like you're using the `master` branch, which is a work in progress of TinyDB version 4.0. Using the `v3` branch should work fine 🙂

**Comment by YunzhaoLu** [comment]
Thank you for the reply. I changed it locally for testing.
