### ISSUE TITLE
keys in dict are "stringified" on write

### ISSUE THREAD

**Issue by asmodehn** [msiemens/tinydb#290]
Here is a behaviour that I wasn't expecting : 
```

Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.10.1

Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
In[2]: from tinydb import TinyDB, Query
In[3]: db = TinyDB("/tmp/testing.json")
In[4]: name = Query()
In[5]: db.insert({'name': 'myitem', 51: 42})
Out[5]: 1
In[6]: db.search(name.name == 'myitem')
Out[6]: [{'name': 'myitem', '51': 42}]
```
Note the key `51` being implicitely stringified to `'51'`.

After this code : 
```
cat /tmp/testing.json
{"_default": {"1": {"name": "myitem", "51": 42}}}
```

Is that expected ?
What should I do if I want to be able to have more than strings as dictionary key ?

**Comment by Qlii256** [comment]
It's normal behaviour of json.loads method in Python. It's the "standard" way of having keys in json-format, all keys are considered strings. So whenever you add data using TinyDB, it will write it to file and convert all keys to strings.

**Comment by msiemens** [comment]
Actually it's not just Python behavior but it's also part of the JSON standard: With JSON data, keys MUST be strings, it's not possible to have JSON data that has integers as keys.

**Comment by asmodehn** [comment]
Thanks for the information...
I guess I want something closer to python `dict` then, for simplicity in my usecase.

So I ll have to implement something using an extension of json (like json5 or so...). Which one would you advise (I m not familiar with the various improvements out there) ?

**Comment by msiemens** [comment]
I think the closest you can get to using a Python `dict` would be to store the data using the [Python `pickle` serialization](https://docs.python.org/3/library/pickle.html). This will serialize the `dict` as close as possible to the original data. But this format is not human-readable. If you want readability too, you might consider using [`YAML`](https://pyyaml.org/wiki/PyYAMLDocumentation) which is human-readable but more flexible than JSON.
