### ISSUE TITLE
Modifying read data will modify the cache

### ISSUE THREAD

**Issue by Qlii256** [msiemens/tinydb#291]
When having a huge amount of data, the process of reading that file every time the read-method is called takes time. My idea is to keep track if the file has been modified and if so read it again. If not, read from cache. This improves performance a lot and helps keep disk I/O down.

I've forked TinyDB and tried to come up with a solution myself, but it turns out it's harder than it looks. When storing dictionaries to cache them, it keeps a reference. So whenever data is modified by the end-user (after requesting the read-method), the changes are reflected in the cache. One way to solve this is returning the cached data with copy.deepcopy, but that takes a long time on bigger databases, which ends up being longer than straight up reading the whole file again, making the cache meaningless.

I've  looked online and found that json.loads(json.dumps)) in fact does the same thing but faster and it turns out it's doing it's job, but still find that it's making the overall experience slow. I was wondering if anyone got any ideas on how to make TinyDB perform faster without compromising being able to modify the read data.

**Comment by msiemens** [comment]
It seems like you are running into the limits of TinyDB. If you have a huge amout of data, it won't be fun performance-wise. Yes, it's not impossible to make it work (for example implementing a caching mechanism like the one you mentioned), but it will take a lot of work to implement it correctly and efficiently as you're dealing with a _lot_ of data.

I think the easiest way is to try using a database more suited to large datasets as sqlite using the [builtin Python module](https://docs.python.org/3/library/sqlite3.html). It supports concurrent access and is able to handle big amounts of data without issues.

I know that this doesn't really answer your question about the best way to clone data in TinyDB but the question of whether TinyDB is the best solution here would be the first question I'd ask.
