### ISSUE TITLE
Calling db.search in the loop shows outdated result

### ISSUE THREAD

**Issue by d-ivashchuk** [msiemens/tinydb#292]
Hello! First of all thanks for making tinyDB I really love it.

I am coming from JS background and learning python at the moment so sorry for any stupid questions coming from my ignorance in advance :)

I am making some hardware hobby project and want to use tinydb as simple data storage

in my db.py

from tinydb import TinyDB, Query

```python
db = TinyDB('db.json')
LastTweetInfo = Query()

```

in crawler.py 

```python
import db
import time
import twitter


try:
    while True:
        prevInfo = db.db.search(db.LastTweetInfo.acc == 'divdev_')
        db.db.update({'prevLikes': prevInfo[0][
            'likes'],
            'prevRetweets': prevInfo[0]['retweets']}, db.LastTweetInfo.acc == 'divdev_')
        info = twitter.getLastTweetInfo()
        db.db.update({'likes': info[0],
                      'retweets': info[1]}, db.LastTweetInfo.acc == 'divdev_')
        time.sleep(6)
except KeyboardInterrupt:
    print("Cleaning up!")

```

in test.py  

```python
import db
import time


try:
    while True:
        info = db.db.search(db.LastTweetInfo.acc == 'divdev_')
        print(info)
        time.sleep(5)
except KeyboardInterrupt:
    print("Cleaning up!")

```

Crawler is used to get the info of the tweet and works totally as I expect it to work, values are updated as desired on every while loop tick.

The problem appears when I want to query the data to then display it on the screen, it seems like the query is always references the same state of the db. Although db.json gets updated correctly - printing the stuff from `test.py` always prints the same result (namely first call to db) and does not seem to react to file changes.

Note: I run both `crawler.py` and `test.py` simultaneously.

Thanks a lot for any pointers and clarifications!

**Comment by msiemens** [comment]
Hey @d-ivashchuk,

Accessing a TinyDB database simultaneously from multiple threads or processes (as in your case) is not supported unfortunately. This is because if multiple threads/processes access the database file, TinyDB may read the file during an incomplete write operation, thus reading invalid data. It would be possible to implement some sort of locking mechanism, but that is outside the scope of TinyDB.

Cheers!

**Comment by d-ivashchuk** [comment]
Ah, ok, probably missed that if it’s in the docs! Thanks a lot for clarifying👍🏼
