### ISSUE TITLE
Ability to query by doc_id?

### ISSUE THREAD

**Issue by Granitosaurus** [msiemens/tinydb#293]
AFAIK right now it's not possible to used `doc_id` in `Query` logic? I'd like to retrieve any document where `doc_id > 10` but neither `where` nor `Query` objects support this logic:

```python
db.count(Query().doc_id > 10)
0
db.count(where('doc_id') > 10)
0
db.count(Query().doc_id)
0
```

Am I missing something?

**Comment by vasudevanv** [comment]
You should be able to do this with a list comprehension

`python
docs = [ item for item in db.all() if item.doc_id > 10 ]
`

**Comment by msiemens** [comment]
As @vasudevanv said, using a list comprehension is the best way to do this probably.

There's no native support for filtering document IDs in TinyDB as they are fundamentally NOT a field in the table data but used as keys for the table dicts. Thus implementing filtering on document IDs would require re-implementing all query operations a second time for document IDs which I don't really want to do.

I know this is limiting for some applications but implementing this would lead to a lot of duplicated or complicated code.
