### ISSUE TITLE
Enable file access mode for JSONStorage

### ISSUE THREAD

**Issue by jmborr** [msiemens/tinydb#297]
Problem: A user with no write permissions for the database file cannot open the database for reading.

Proposed solution:
Add optional argument `access_mode='r+'` to [JSONStorage.__init__](https://github.com/msiemens/tinydb/blob/master/tinydb/storages.py#L69). This parameter is passed on to the [open statement](https://github.com/msiemens/tinydb/blob/master/tinydb/storages.py#L81)

**Comment by msiemens** [comment]
The feature you implemented has been released in TinyDB v4.1.0 🙂
