### ISSUE TITLE
How to reset doc id index to 0 or 1 after deleting an entry

### ISSUE THREAD

**Issue by psycho-neon** [msiemens/tinydb#302]
Hi!

First of all thank you for this module, it helped me alot when it comes to storing data. I just stumbled upon one problem, i've searched through the internet and here as well from the previous cases but no luck in finding one.

I have lists of name in the database. as follows:
```json
{
    "_default": {
        "1": {
            "name": "Employee 1",
            "Quota": "100"
        },
        "2": {
            "name": "Employee 2",
            "Quota": "100"
        },
        "3": {
            "name": "Employee 3",
            "Quota": "100"
        },
        "4": {
            "name": "Employee 4",
            "Quota": "100"
        }
    }
}
```

If i remove for example `Employee 1` the database will look like this:
```json
{
    "_default": {
        "2": {
            "name": "Employee 2",
            "Quota": "100"
        },
        "3": {
            "name": "Employee 3",
            "Quota": "100"
        },
        "4": {
            "name": "Employee 4",
            "Quota": "100"
        }
    }
}
```

Is there any way to reset the indexes from 1? Since we use the `doc_id` for most of our operations.

**Comment by psycho-neon** [comment]
Hm. Okay I think the only way to do it now is to purge the table and re-instantiate it using db.table(name)

Example:

Database.json
```json
{
    "_default": {
        "1": {
            "Quota": "100",
            "name": "Employee 1"
        },
        "2": {
            "Quota": "100",
            "name": "Employee 2"
        },
        "3": {
            "Quota": "100",
            "name": "Employee 3"
        }
    }
}
```

and if I want to remove `Employee#2` i will use the following:
```python
database.remove(doc_ids=[2,])           # remove employe number 2
data = database.all()                   # save the current data to a list (after deletion)
database.purge_table("_default")        # purge the table.
table = database.table("_default")      # reinitiate the table (this resets the table index to 1 again)
table.insert_multiple(data)             # insert back the data
```

Final output of the Database.json
```json
{
    "_default": {
        "1": {
            "Quota": "100",
            "name": "Employee 1"
        },
        "2": {
            "Quota": "100",
            "name": "Employee 3"
        }
    }
}
```


---
if there is any other way to do it, please let me know. I will leave this one open.

**Comment by msiemens** [comment]
Hey @psycho-neon,

TinyDB doesn't reclaim empty document IDs and there are no plans to implement something like that. Doing so would introduce a lot of complexity for just a small benefit. I'd like to keep TinyDB as simple as possible to make it easier to understand its mechanics and reduce opportunities to introduce bugs.

**Comment by psycho-neon** [comment]
I understand. The workaround I've made satisfies my requirements, so I can on that way. 

We can close this issue now. Thank you so much.
