### ISSUE TITLE
feature request: user defined document _id

### ISSUE THREAD

**Issue by yodog** [msiemens/tinydb#303]
as discussed here: https://forum.m-siemens.de/d/67-set-custom-doc-id

i'm fetching some records from elasticsearch, and after a few calculation i'd like to store it in a file.

the problem is i cant find a way to set the doc_id.
its always a incremental integer.

in my elasticsearch solution i have a custom value (defined by me) as the document _id, and i would like to use the same value

**Comment by msiemens** [comment]
@yodog I've now implemented this using this syntax:

```python
>>> db.insert(Document({'int': 1, 'char': 'a'}, 77))
77
```

What do you think?

**Comment by yodog** [comment]
very nice :)  

does it allow for alphanumeric chars too?  

sometimes our doc ids can be fingerprints...  


![Screenshot from 2020-06-23 19-40-28](https://user-images.githubusercontent.com/2393347/85473480-af097100-b589-11ea-801f-19a59c147ff5.png)

**Comment by msiemens** [comment]
@yodog In this case you'd have to overwrite `Table.document_id_class` to use strings for document IDs as well as well as overload `Table._get_next_id()` to work with strings (right now it assumes integers).
