### ISSUE TITLE
TypeError on multiple methods when database is empty

### ISSUE THREAD

**Issue by dinko-pehar** [msiemens/tinydb#307]
When `TinyDB` is instantiated, it raises `TypeError` on multiple occasions because of line:
https://github.com/msiemens/tinydb/blob/f0e39093e140c33c67580ac29a1d6c7d04211a74/tinydb/table.py#L509

Example:
```python
from tinydb import TinyDB

# Create db.json (empty file)
db = TinyDB('db.json')

# All lines below raise `TypeError`

print(db)
print(len(db))

table1 = db.table('table1')
print(table1)
print(len(table1))
```

Traceback:
```python
Traceback (most recent call last):
  File "/home/dinko/personal_projects/tinydb/example.py", line 6, in <module>
    print(db)
  File "/home/dinko/personal_projects/tinydb/tinydb/database.py", line 98, in __repr__
    'default_table_documents_count={}'.format(self.__len__()),
  File "/home/dinko/personal_projects/tinydb/tinydb/database.py", line 263, in __len__
    return len(self.table(self.default_table_name))
  File "/home/dinko/personal_projects/tinydb/tinydb/table.py", line 509, in __len__
    return len(tables[self.name])
TypeError: 'NoneType' object is not subscriptable
```

Reason for this is because `storage.read()` return `None` when db is empty. This happens with `JSONStorage` and `MemoryStorage`. Solution would be just to return empty dict when it's `None`. I can make pull request if you like. This change doesn't break any tests.

**Comment by msiemens** [comment]
Thanks for reporting this, I've pushed a fix 🙂

**Comment by dinko-pehar** [comment]
Great !

I'll try to look more in the internals of `TinyDB` . If I find something else, I'll open a issue.
