### ISSUE TITLE
Failed to insert when default table in specified

### ISSUE THREAD

**Issue by dinko-pehar** [msiemens/tinydb#308]
When specifying [default_table](https://tinydb.readthedocs.io/en/latest/usage.html#default-table) to be something other than `_default`, it fails to insert.

Example:
```python
from tinydb import TinyDB

# Specify default table
db = TinyDB('db.json', default_table='other')

# Can't insert. Raises TypeError
db.insert({'name': 'Apple'})

```

Traceback:
```python
  File "/home/dinko/personal_projects/tinydb/examples/example_2.py", line 7, in <module>
    db.insert({'name': 'Apple'})
  File "/home/dinko/personal_projects/tinydb/tinydb/table.py", line 159, in insert
    self._update_table(updater)
  File "/home/dinko/personal_projects/tinydb/tinydb/table.py", line 638, in _update_table
    self._storage.write(tables)
  File "/home/dinko/personal_projects/tinydb/tinydb/storages.py", line 127, in write
    serialized = json.dumps(data, **self.kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
TypeError: __init__() got an unexpected keyword argument 'default_table'

Process finished with exit code 1
```

**Comment by dinko-pehar** [comment]
I'm testing from `master` branch. This evaluates correctly on latest version.

**Comment by msiemens** [comment]
Hey! The `default_table` argument is part of TinyDB v3 which the documentation referred to whereas the `master` branch contained TinyDB v4 where the argument has been removed in favor of using the `TinyDB.default_table_name` attribute.

**Comment by dinko-pehar** [comment]
Yeah, I used `master` branch for testing, but referred to latest build of documentation on _readthedocs.io_ . Didn't think there will be a lot of unpublished commits. I'll explore more on version _v4.0.0_ .
