### ISSUE TITLE
Documentation outdated on purge methods

### ISSUE THREAD

**Issue by dinko-pehar** [msiemens/tinydb#309]
Documentation is outdated.

It shows usage on methods like `purge_tables`, `purge_table` and `purge` [<sup>1</sup>](https://tinydb.readthedocs.io/en/latest/getting-started.html#recap) [<sup>2</sup>](https://tinydb.readthedocs.io/en/latest/usage.html#tables), but these methods doesn't exist. I found `truncate` and `remove`. Maybe documentation needs update.

**Comment by msiemens** [comment]
Hey! Thanks for reporting this! Seems like you used the latest version from the `master` branch, which contained the development for TinyDB v4 whereas the documentation still referred to TinyDB v3. But as I've now published v4.0.0 the documentation has now been updated, too :)

**Comment by dinko-pehar** [comment]
Great, now with release of v4.0.0 documentation is in sync with release. You can close this one.

**Comment by msiemens** [comment]
Thanks!
