### ISSUE TITLE
ImportError on 4.0.0: from tinydb_serialization import SerializationMiddleware

### ISSUE THREAD

**Issue by dagraham** [msiemens/tinydb#310]
(env) dag@cricket:~/tinydb-test$ pip freeze
pkg-resources==0.0.0
tinydb==4.0.0
tinydb-serialization==1.0.4

Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tinydb
>>> from tinydb_serialization import SerializationMiddleware
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dag/tinydb-test/env/lib/python3.7/site-packages/tinydb_serialization/__init__.py", line 6, in <module>
    from tinydb.utils import with_metaclass
ImportError: cannot import name 'with_metaclass' from 'tinydb.utils' (/home/dag/tinydb-test/env/lib/python3.7/site-packages/tinydb/utils.py)

**Comment by dinko-pehar** [comment]
@dagraham I think `with_metaclass` is used as compatibility for abstract classes both in Python 2 and Python 3. Due to recent release of _TinyDB_ to v4.0.0. , `tinydb-serialization` which used this method can also be updated to be compatible only with Python 3.

**Comment by dagraham** [comment]
I get the same error just importing tinydb_serialization.

**Comment by dinko-pehar** [comment]
Install latest working version that is compatible with `tinydb-serialization`: 
> _pip install tinydb==3.15.2_ 

This one should work.

**Comment by anelles** [comment]
Does 'for now' mean that this on the list of being fixed or should we plan on this taking longer? 
Our project would appreciate an update, but we can also use the workaround with the version for the time being.

**Comment by dinko-pehar** [comment]
@msiemens I can make pull request on `tinydb_serialization` to fix this error. @anelles If pull is accepted, and `tinydb_serialization` is released on PyPI with version bump, this will close this issue you are facing currently.

**Comment by anelles** [comment]
Perfect! That would be great, thanks!

**Comment by dagraham** [comment]
Is the pull request still a possibility?

**Comment by dinko-pehar** [comment]
@dagraham Pull request is merged into master. It will be released soon Read  what @msiemens said at [here](https://github.com/msiemens/tinydb-serialization/pull/9)

**Comment by dagraham** [comment]
That's great - thanks very much!

**Comment by msiemens** [comment]
tinydb-serialization v2.0.0 has been published which supports TinyDB v4 :)
