### ISSUE TITLE
pip installs old version of pipy instead of 4.0.0

### ISSUE THREAD

**Issue by ankudinov** [msiemens/tinydb#311]
pip installs 3.x version of tinydb instead of 4.0.0
[This file](https://files.pythonhosted.org/packages/3c/06/5f001a5ebe3a13718f5a4016a41626b3d5afecfd43e58d048d544d1e44a2/tinydb-4.0.0.tar.gz) (uploaded on 2nd May) still contains 3.x code instead of latest one.

**Comment by msiemens** [comment]
Thanks for reporting this! Seems like I mixed something up when releasing v4.0.0. I've now published v4.0.0.post1 which should fix the issue!

**Comment by gorrioncillo** [comment]
i try to install with "pip3 install tinydb" and it install lot of other packages, I do not think yo upload the right package. Please check it again.
Meanwhile i use 3.15.2 version which installs correctly.

**Comment by msiemens** [comment]
Could you try installing TinyDB v4.1.0 instead? Does it work better?

**Comment by gorrioncillo** [comment]
it keeps installing many packages
`Package            Version                                                            
------------------ -------                                                            
atomicwrites       1.4.0                                                              
attrs              19.3.0                                                             
colorama           0.4.3                                                              
importlib-metadata 1.6.0                                                              
more-itertools     8.2.0                                                              
mypy               0.770                                                              
mypy-extensions    0.4.3                                                              
packaging          20.3                                                               
pip                18.1                                                               
pluggy             0.13.1                                                             
py                 1.8.1                                                              
pyparsing          2.4.7                                                              
pytest             5.4.1                                                              
pytest-mypy        0.4.2                                                              
setuptools         40.6.2                                                             
six                1.14.0                                                             
tinydb             4.1.0                                                              
typed-ast          1.4.1                                                              
typing-extensions  3.7.4.2                                                            
wcwidth            0.1.9                                                              
zipp               3.1.0 `

This is for a new virtual environment, and i just installed tinydb. That is correct?

**Comment by msiemens** [comment]
@gorrioncillo This seems to be the same as issue #315. I've published v4.1.1 which should not install these packages.

**Comment by ankudinov** [comment]
LGTM
