### ISSUE TITLE
Install from source failed

### ISSUE THREAD

**Issue by virtimus** [msiemens/tinydb#312]
I did:

```
git clone https://github.com/msiemens/tinydb/
cd tinydb
python setup.py install
```

I got 
"python: can't open file 'install': [Errno 2] No such file or directory"

And it's normal as I cannot find setup.py anywhere

**Comment by hugovk** [comment]
It's generally discouraged to call `python setup.py`, even if it exists.

Instead:

```
pip install .
```

**Comment by msiemens** [comment]
As @hugovk mentioned, running `pip install .` should install TinyDB from source. As TinyDB switched from `setup.py` to `pyproject.toml`, it doesn't include a `setup.py` file in the source tree any more.

**Comment by xu4wang** [comment]
> As @hugovk mentioned, running `pip install .` should install TinyDB from source. As TinyDB switched from `setup.py` to `pyproject.toml`, it doesn't include a `setup.py` file in the source tree any more.

Ah..thanks for clarification... I was also searching for setup.py
The documentation need to be updated.

https://tinydb.readthedocs.io/en/latest/getting-started.html#installing-tinydb
