### ISSUE TITLE
Migrating from 3 to 4

### ISSUE THREAD

**Issue by p-l-** [msiemens/tinydb#313]
Hi,

First of all, thank you for your work and this project!

We use TinyDB as one backend, amongst others, in [IVRE](https://github.com/cea-sec/ivre), and due to the way other backends work, we need to have an empty filter (an equivalent of `WHERE TRUE`), that would:
- match every entry (for that point, something like `lambda _: True` works)
- be composable as a regular filter / query (that we could, for example, use like this `flt_empty & other_flt`; for that point, `lambda _: True` won't work obviously).

With TinyDB < 4, we have been using `Query()` (no idea if that was a good idea, but that did work for both points we need). Starting with TinyDB 4, we cannot do that anymore, and we get `RuntimeError: Empty query was evaluated` exceptions.

Do you have something we could use for that?

Thanks!

**Comment by msiemens** [comment]
Hey!

Thanks for reporting this! Seems like I forgot to include this change in the changelog. I think in some cases having a no-op query will be useful so I'll add a `Query().noop()` query in the next release.

For background: I've added the exception to improve user experience when people search for an empty query by accident. When implementing this I didn't consider that having a no-op query might be useful in some cases. Having an explicit `noop` query seems like an elegant solution to me 🙂

**Comment by msiemens** [comment]
TinyDB v4.1.0 has now been published 🙂

**Comment by p-l-** [comment]
Thanks!

**Comment by munsuri** [comment]
Hei,

Thanks for TinyDB!
I'm actually trying to compose queries dynamically by using Query().noop() to **initialize** my query variable. However, I might be missing something... since noop() is always True, when I do OR composition (finalQuery **|=** oneQuery), I always get every document (True=always a match). Is there a way to to have the opposite of noop() (an always False)? 
Thanks again!

**Comment by msiemens** [comment]
Hey @munsuri,

you could use something like `Query().test(lambda _: False)` to implement something like this. Does that work for you?

**Comment by munsuri** [comment]
Hei @msiemens , thanks for your answer!

It looks like a good solution, however, I get the following exception:

```
    queryFilters = Query().test(lambda _: False)
  File "/usr/local/lib/python3.7/site-packages/tinydb/queries.py", line 346, in test
    ('test', self._path, func, args)
  File "/usr/local/lib/python3.7/site-packages/tinydb/queries.py", line 181, in _generate_test
    raise ValueError('Query has no path')
ValueError: Query has no path
```

**Comment by munsuri** [comment]
Oh, but adding a 'path', something like `Query()._.test(lambda _: False)` seems to work fine! Thanks for the suggestion!

**Comment by msiemens** [comment]
Glad you were able to make it work!
