### ISSUE TITLE
Multiple db.insert() not working in v4

### ISSUE THREAD

**Issue by viktorix** [msiemens/tinydb#314]
Not sure if anything changed or this is a bug. The issue happens when the **database isn't empty**, it has to have some data already. Take this simple example, let's say the database has 1 entry already:

```python
from tinydb import TinyDB

db = TinyDB("patterns_db2.json")

print(len(db))

db.insert({"entry": "one"})
db.insert({"entry": "two"})

print(len(db))
```
The output in v3.15.2 would be:
```
1
3
```
But starting with v4, the output is:
```
1
2
```
This is also the case if you're using for loop:
```python
for entry in entries:
    db.insert({"entry": "one"})
```

Did something change in v4, or is this a bug?

On Windows, using Python 3.8.1.

**Comment by msiemens** [comment]
Thanks for reporting this! This is indeed a bug in TinyDB, I've pushed a fix and will publish a new release shortly!

**Comment by msiemens** [comment]
TinyDB v4.1.0 has now been published 🙂
