### ISSUE TITLE
maximum number of records, maximum number of tables?

### ISSUE THREAD

**Issue by xu4wang** [msiemens/tinydb#316]
I'm checking if I should use tinyDB for one project. would like to know some limitations of tinyDB regarding performance.

Particularly, I would like to know:
* How many records can be stored in one table?
* How many tables can be used in one db?
* In practical, what's a recommended maximum number for the above?

Sorry if this is not a good place to ask, I checked the doc but didn't find answer.

https://tinydb.readthedocs.io/en/latest/search.html?q=maximum&check_keywords=yes&area=default

BR,Austin

**Comment by msiemens** [comment]
Hey!

TinyDB doesn't have limits it imposes on users. In theory you can as much data in TinyDB as you like. In practice though, you'll have to consider two limits:

- TinyDB reads the whole database into memory for its processing operations. This means that 1) the dataset you use has to fit into memory and 2) you have to consider that it will be read from disk for most operations.
- Search operations work by scanning the entire dataset using the query you provided. This means that a really large dataset might make it slow to perform queries.

The exact limits this will impose on your application performance depends on the performance expectations you have. From a quick test on my machine a database with 1 million documents takes roughly 6 seconds to create and then 1-2 seconds for operations like `len(db)` and `db.get(doc_id=…)` whereas searching might take up to 4 seconds. Mind you that these are just rough figures on my machine and these will depend on the hardware/software configuration as well as the exact operations you use.

In general I think having more than 500k documents in total (no matter how many tables you use) will lead to performance penalties that might make alternatives like `sqlite` more attractive.

**Comment by xu4wang** [comment]
> In general I think having more than 500k documents in total (no matter how many tables you use) will lead to performance penalties that might make alternatives like `sqlite` more attractive.

Thanks @msiemens  for your answer.  500k is already a big number for my scenario. :-)
 I love the interface tinyDB provided, I will try it.

**Comment by xu4wang** [comment]
Maybe in the future when the data increased too much, we can use some method to distribute the documents into remote different machines, while keeping the simple tinyDB interface?  Similar to the pattern used by memcached or redis.

**Comment by msiemens** [comment]
> Maybe in the future when the data increased too much, we can use some method to distribute the documents into remote different machines, while keeping the simple tinyDB interface? Similar to the pattern used by memcached or redis.

That would be an option but in my view that should be a project separate from TinyDB itself. One could write a custom storage that does all kinds of tricks to distribute documents into different machines/files/objects/… Or even create a new project with a TinyDB-compatible interface. But that's beyond the goals of TinyDB 🙃

**Comment by xu4wang** [comment]
> > Maybe in the future when the data increased too much, we can use some method to distribute the documents into remote different machines, while keeping the simple tinyDB interface? Similar to the pattern used by memcached or redis.
> 
> That would be an option but in my view that should be a project separate from TinyDB itself. One could write a custom storage that does all kinds of tricks to distribute documents into different machines/files/objects/… Or even create a new project with a TinyDB-compatible interface. But that's beyond the goals of TinyDB 🙃

Yeah. Agreed.. that would no longer be *Tiny* DB.
