### ISSUE TITLE
[feature] Add timestamp on document insertion/update

### ISSUE THREAD

**Issue by mcaples** [msiemens/tinydb#319]
Hi Markus,

My use-case for TinyDB requires a timestamp to be added to each document upon insertion and when that document is updated. This is useful for understanding database activities, establishing statistics and trends etc.

I have implemented this [feature](https://github.com/mcaples/tinydb/tree/feat_timestamp_insertion), nonetheless I think this is a fairly simple addition and would like to discuss and see if other people are interested in this feature.

A user settable flag is defined in the Table class. The default value is false (i.e. the feature is not active) so as to not break compatibility.

On insertion, the field 'created' is added to the document dictionary and initialized with the current UTC time in string format. The field 'updated' is also added but is initialized as empty string ''.

On update of a document, the field 'updated' is set to the current UTC time in string format.

I don't really care what time zone/format is chosen as long as it is consistent, UTC seems like a good choice. This might be a point of issue for some people and maybe it will require some customization down the track, although I like the simplicity of having only one time format.

Let me know what you think.

Cheers,

Miles

**Comment by eugene-eeo** [comment]
Seems like it would be hard to implement using the current architecture (just based on the middlewares). Also I'm not sure if @msiemens wants a rewrite 😅 so soon. Maybe it is best maintained as a plugin offering a wrapped up Table class that tracks timestamps? That class would intercept all calls to the modification operations, and add the appropriate timestamps.

**Comment by mcaples** [comment]
That's understandable :smile:

My initial approach was to subclass Table as below, but it required a change to \__init__.py to expose Table class. Thoughts?

```import time
from datetime import datetime, timezone
from typing import (
    Callable,
    Dict,
    Iterable,
    Iterator,
    List,
    Mapping,
    Optional,
    Union,
    cast
)

from tinydb import TinyDB, Query, Table


class MyTable(Table):
    def insert(self, document: Mapping):
        document['created'] = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S%z')
        document['updated'] = ''
        super().insert(document)

    def insert_multiple(self, documents: Iterable[Mapping]):
        for document in documents:
            document['created'] = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S%z')
            document['updated'] = ''
            super().insert(document)

    def update(
            self,
            fields: Union[Mapping, Callable[[Mapping], None]],
            cond: Optional[Query] = None,
            doc_ids: Optional[Iterable[int]] = None,
    ):
        fields['updated'] = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S%z')
        super().update(fields, cond, doc_ids)


db = TinyDB('test.json')
db.table_class = MyTable
Person = Query()
db.insert({'name': 'Bob', 'age': 22})
time.sleep(1)
db.update({'age': 25}, Person.name == 'Bob')
# db.insert_multiple([{'name': 'John', 'age': 22}, {'name': 'Mary', 'age': 23}])
print(db.all())
```

**Comment by eugene-eeo** [comment]
Yeah that seems good :+1:, that's what I'd naturally go for as well.

**Comment by msiemens** [comment]
As @eugene-eeo mentioned, using a `Table` subclass is the way to go here. TinyDB tries to have not too many assuptions about the data that is stored and magically adding `created` and `updated` fields that weren't specified in the original data is something I'd like to keep out of the TinyDB core altough it might be an useful extension.

**Comment by mcaples** [comment]
Thanks, I'll look at creating an extension! 😄

**Comment by pachacamac** [comment]
Hey @mcaples , @msiemens

I just discovered TinyDB and love it so far! However my Ruby/Rails background brought up my desire to also have created_at / updated_at timestamps handled for me so I found this issue and gave the extension approach a try. It seems to work quite nicely for me with this simple approach: 

```
class TimestampsMiddleware(Middleware):
  """Automatically handle timestamps in TinyDB"""

  def __init__(self, storage_cls, created_key='created_at', updated_key='updated_at', time_format='%Y-%m-%dT%H:%M:%S%z'):
    super().__init__(storage_cls)
    self.created_key = created_key
    self.updated_key = updated_key
    self.time_format = time_format

  def write(self, data):
    previous_data = self.storage.read()
    for table_name in data:
      table = data[table_name]
      for eid in table:
        if table_name not in previous_data.keys() or eid not in previous_data[table_name].keys(): # new entry
          dt = datetime.now(timezone.utc).strftime(self.time_format)
          data[table_name][eid][self.created_key] = dt
          data[table_name][eid][self.updated_key] = dt
        elif data[table_name][eid] != previous_data[table_name][eid]: # updated entry
          data[table_name][eid][self.updated_key] = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S%z')
    self.storage.write(data)
```

If that's the right way I'd like to know what would be the best way to offer this extension? I could

A) make PR to TinyDB and extend middlewares.py or

B) make my own repo and maybe you could list it [https://tinydb.readthedocs.io/en/stable/extensions.html](here)?

**Comment by msiemens** [comment]
Hey @pachacamac, the preferred way is to create a new repo. I'd be happy to link it in the extensions list, when you're ready 🙂 Thanks for your openness to contributing!

**Comment by pachacamac** [comment]
Hey @msiemens, always nice to give back to a cool open source project :) If you have time would you mind taking a look at my repo and letting me know what you think? https://github.com/pachacamac/TinyDBTimestamps

**Comment by msiemens** [comment]
@pachacamac That looks good to me! The only minor thing is that you use `TimestampsMiddleware` as your module name while the convention is to use snake case which would be `timestamps_middleware` (see [PEP 8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)). But I'll go ahead and link the repo in the extensions list, if you want, you can adapt the module name 🙃

**Comment by msiemens** [comment]
I've also marked the extension as experimental for now. If the extension is stable in your eyes, just open a pull request to update the docs accordingly 🙂

**Comment by pachacamac** [comment]
Thanks for the tip and for listing! I renamed the module.

**Comment by eugene-eeo** [comment]
Hi @pachacamac, just a minor comment:

[Here](https://github.com/pachacamac/TinyDBTimestamps/blob/b69d07666a700db6f66175c18967fdce14d25b43/timestamps_middleware/timestamps_middleware.py#L30) and [here](https://github.com/pachacamac/TinyDBTimestamps/blob/b69d07666a700db6f66175c18967fdce14d25b43/timestamps_middleware/timestamps_middleware.py#L34) you probably meant:

```
if self.created_key is not None:
    ...
```

otherwise it might lead to some confusion in some cases.


Also [here](https://github.com/pachacamac/TinyDBTimestamps/blob/b69d07666a700db6f66175c18967fdce14d25b43/timestamps_middleware/timestamps_middleware.py#L33) you can prevent some unnecessary copying if you stored only previous created/updated timestamps:

```
{table_name: {doc_id: (created, updated)}}
```

**Comment by pachacamac** [comment]
Thank you @eugene-eeo for pointing those out and linking to the right resources. Never packed a Python lib so this will be handy. 

For everyone who might see this thread in the future: Please open issues regarding my extension directly [here](https://github.com/pachacamac/TinyDBTimestamps/issues)
