### ISSUE TITLE
unclear what query_caching means

### ISSUE THREAD

**Issue by NeroVanbiervliet** [msiemens/tinydb#320]
It is unclear from the [docs on query caching](https://tinydb.readthedocs.io/en/latest/usage.html#query-caching) what it exactly does. I thought it determines how often updates are persisted to the `json` file, but this does not seem the case.

**Comment by mcaples** [comment]
I'll take a stab at an answer.

Query Caching is a feature that speeds up data retrieval from a database. It achieves this by storing the query together with the retrieved result, then if an identical query is requested it can serve the data faster without executing commands on the database.

The `cache_size` determines how many query-result pairs can be stored before new queries push the old ones out of memory, in a first in first out (FIFO) order.

Here's an example I've put together:
```
import time
import logging

from tinydb import TinyDB, Query, where
from tinydb.storages import MemoryStorage


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
ch = logging.StreamHandler()
ch.setFormatter(formatter)
logger.addHandler(ch)


def timeit(func):
    def wrapper(*args, **kwargs):
        ts = time.time()
        result = func(*args, **kwargs)
        te = time.time()
        logger.debug("{}, kwargs = {}, exc_time: {:.2f}ms".format(func.__name__, kwargs, (te-ts)*1000))
    return wrapper


@timeit
def add_documents_to_table(table, n):
    table.insert_multiple([{"int": i} for i in range(n)])


@timeit
def query_documents_lte(table, n):
    table.count(where('int') <= n)


def main():
    db = TinyDB(storage=MemoryStorage)
    table = db.table('table_name', cache_size=2)
    add_documents_to_table(table, n=50000)
    query_documents_lte(table, n=1000)  # query 1
    query_documents_lte(table, n=5000)  # query 2
    query_documents_lte(table, n=1000)  # cached, expect time == 0
    query_documents_lte(table, n=5000)  # cached, expect time == 0
    query_documents_lte(table, n=1234)  # query 3, queries > cache_size
    query_documents_lte(table, n=1000)  # expect time != 0 since query 3 pushed it out of cache
    query_documents_lte(table, n=1000)  # cached, expect time == 0


if __name__ == "__main__":
    main()

```
And the expected output:
```
2020-05-29 21:49:44,036 - DEBUG - add_documents_to_table, kwargs = {'n': 50000}, exc_time: 84.08ms
2020-05-29 21:49:44,100 - DEBUG - query_documents_lte, kwargs = {'n': 1000}, exc_time: 64.06ms
2020-05-29 21:49:44,164 - DEBUG - query_documents_lte, kwargs = {'n': 5000}, exc_time: 64.06ms
2020-05-29 21:49:44,164 - DEBUG - query_documents_lte, kwargs = {'n': 1000}, exc_time: 0.00ms
2020-05-29 21:49:44,164 - DEBUG - query_documents_lte, kwargs = {'n': 5000}, exc_time: 0.00ms
2020-05-29 21:49:44,228 - DEBUG - query_documents_lte, kwargs = {'n': 1234}, exc_time: 64.06ms
2020-05-29 21:49:44,292 - DEBUG - query_documents_lte, kwargs = {'n': 1000}, exc_time: 64.06ms
2020-05-29 21:49:44,292 - DEBUG - query_documents_lte, kwargs = {'n': 1000}, exc_time: 0.00ms
```
What is interesting though is that I have run the above program many times and noticed that on occasion (very very infrequently) the execution time for a cache hit is non-zero.
```
2020-05-29 21:50:52,309 - DEBUG - add_documents_to_table, kwargs = {'n': 50000}, exc_time: 83.08ms
2020-05-29 21:50:52,372 - DEBUG - query_documents_lte, kwargs = {'n': 1000}, exc_time: 63.07ms
2020-05-29 21:50:52,436 - DEBUG - query_documents_lte, kwargs = {'n': 5000}, exc_time: 64.05ms
2020-05-29 21:50:52,437 - DEBUG - query_documents_lte, kwargs = {'n': 1000}, exc_time: 1.00ms
2020-05-29 21:50:52,437 - DEBUG - query_documents_lte, kwargs = {'n': 5000}, exc_time: 0.00ms
2020-05-29 21:50:52,500 - DEBUG - query_documents_lte, kwargs = {'n': 1234}, exc_time: 63.06ms
2020-05-29 21:50:52,565 - DEBUG - query_documents_lte, kwargs = {'n': 1000}, exc_time: 65.06ms
2020-05-29 21:50:52,565 - DEBUG - query_documents_lte, kwargs = {'n': 1000}, exc_time: 0.00ms
```
Not sure how or why this pops up, and I'm not sure how you would catch this in pytest but I'll have a look around. Any ideas?

**Comment by NeroVanbiervliet** [comment]
Thanks for the example, it's clear to me now! Concerning the non-zero cache hit execution time, I assume you are referring to the `1.00ms`? It is certainly not a full lookup, but I have no clue what it could be.

**Comment by eugene-eeo** [comment]
@mcaples in the code, you're only running the function once here so 1ms might be due to something outside of our control, e.g. cache locality (maybe); but anyways I wouldn't read too much into it :sweat_smile: 

@NeroVanbiervliet a bit of a digression: one of the cool things about query-caching is that if you are using only the TinyDB "primitive" queries, e.g. `==`, `>=`, (and not `.test()`) then query-caching is quite smart; you do not have to worry about the order, i.e.

```python
hash((where('a') == 1) & (where('b') == 2)) == hash((where('b') == 2) & (where('a') == 1))
```

internally whenever you create a query, TinyDB creates an "AST"-representation of it; you can access and play around with it using the `_hash` attribute:

```python
>>> (where('a') == 1)._hash
('==', ('a',), 1)
>>> (where('a')['b'] == 1)._hash
('==', ('a', 'b'), 1)
>>> ((where('b') == 1) & (where('a') == 1))._hash
('and', frozenset({('==', ('a',), 1), ('==', ('b',), 1)}))
```

for queries with `.test()` since we cannot test function equality aside from just comparing whether they are the same object (it's an open problem to determine if two functions are equal!), we are out of luck; but if you use the same function then we can cache it:

```python
>>> f = lambda x: True
>>> hash(where('b').test(f)) == hash(where('b').test(lambda x: True))
False
>>> hash(where('b').test(f)) == hash(where('b').test(f))
True
```

there is a subtle bug/feature in query caching:

```python
(where('b').test(f) & where('a').test(g)) == (where('a').test(g) & where('b').test(f))
```

in general the two forms are not equivalent; e.g. if `f` tests if x is a string, and `g` performs some string operation then the second query may raise an error -- the code runs differently depending on the state of the query cache, but this is probably an edge-case.

**Comment by msiemens** [comment]
Thanks @NeroVanbiervliet for reporting this! I've added a sentence to clarify what exactly the query cache is doing. I hope it's more clear now!

@eugene-eeo Thanks for the note regarding memory usage with lambda test functions. I've added a note on that too.

**Comment by NeroVanbiervliet** [comment]
Definitely better @msiemens. Only the phrasing "as long as the database hasn’t been modified" is still a bit ambiguous to me. If the database is updated from a different process, this won't be noticed and caching will malfunction. I know this limitation with multiple processes is documented, but I initially did notice that in the docs.

**Comment by msiemens** [comment]
You're right, @NeroVanbiervliet! I've added a note on the possibility of stale results if the underlying storage (file, …) is modified from externally.

**Comment by NeroVanbiervliet** [comment]
Perfect!
