### ISSUE TITLE
Exception 'Table' object has no attribute 'write_back'

### ISSUE THREAD

**Issue by dagraham** [msiemens/tinydb#323]
Has write_back been removed in 4.x?

**Comment by dagraham** [comment]
My application allows the user to select and make changes to a document (hash). These changes might involve any of the following:
1. Changing the value of an existing key
2. Adding a new key and value
3. Deleting an existing key and value 

The old "write_back" allowed me to replace the old document with the new. Using "update" works for (1) and (2) but not for (3).   E.g., using update to add "age" but remove "gender" only adds "age":

    >>> from tinydb import TinyDB
    >>> db = TinyDB("/home/dag/tinydb-test/db.json")
    >>> db.insert({'name': 'John', 'gender': 'male'})
    1
    >>> db.get(doc_id=1)
    {'name': 'John', 'gender': 'male'}
    >>> db.update({'name': 'John', 'age': 23}, doc_ids=[1])
    [1]
    >>> db.get(doc_id=1)
    {'name': 'John', 'gender': 'male', 'age': 23}

Note in this regard that the description "Update all matching documents to have a given set of fields." is not quite correct.

Is there a way to replace an existing document with a new one?

**Comment by dagraham** [comment]
Solved:

    def replace(new):
        """
        Used with update to replace the original doc with new.
        """
        def transform(doc):
            # update doc to include key/values from new
            doc.update(new)
            # remove any key/values from doc that are not in new
            for k in list(doc.keys()):
                if k not in new:
                    del doc[k]
        return transform

**Comment by msiemens** [comment]
Hey @dagraham, thanks for reporting this! Seems like I forgot to include this change in the TinyDB v4 changelog. I've now mentioned it in dbe7ad6e068ac0b649a5e8404b95331b84348be8
