### ISSUE TITLE
pypi tar-ball doesn't include tests

### ISSUE THREAD

**Issue by arunpersaud** [msiemens/tinydb#324]
Hi

it would be great, if the pypi tar-ball could again include the tests, since these are often used, for example, for linux distributions and there having the tests and being able to run them is very valuable after building the package for the distribution.

thanks

Arun

**Comment by msiemens** [comment]
Hey! TinyDB v4 switched to Poetry for creating the release tarballs. There it seems like there is no support for adding a folder to the source distribution without it being installed. I've opened an issue at python-poetry/poetry#2513 for this

**Comment by msiemens** [comment]
Starting with TinyDB v4.7.1 the sdist now includes the test suite 🙂
