### ISSUE TITLE
In contains, doc_ids=[list of ids] in 3.15.2 has been changed to doc_id=id in 4.x

### ISSUE THREAD

**Issue by dagraham** [msiemens/tinydb#325]
I previously noted that write_back has been dropped in 4.x. Are these changes noted somewhere in the documentation?
Thanks,
Dan

**Comment by msiemens** [comment]
Actually this is mentioned in the v4 release notes: https://tinydb.readthedocs.io/en/latest/changelog.html#breaking-changes 🙃
