### ISSUE TITLE
add id to document on insertion

### ISSUE THREAD

**Issue by matthdsm** [msiemens/tinydb#326]
Hi,

Is there a way to add the `doc_id` to the document on insertion?
e.g. 
```python
>>> db.insert({"foo":"bar"})
1
>>>> db.get(doc_id=1)
{"id":1, "foo":"bar"}
```

do I need to create a custom storage or is this already supported in some way?
Thanks
M

**Comment by matthdsm** [comment]
fixed using custom middleware

```python
class InjectItemIdMiddleware(Middleware):
    """
    Inject `doc_id` as `id` into inserted document.
    If `id` key is present, delete and overwrite with db id.
    Injected data should not have an id key
    """
    def __init__(self, storage_cls):
        # Any middleware *has* to call the super constructor
        # with storage_cls
        super().__init__(storage_cls)  # (1)

    def read(self):
        data = self.storage.read()
        return data

    def write(self, data):
        for table_name in data:
            table = data[table_name]
            for doc_id in table:
                item = table[doc_id]
                try:
                    del item["id"]
                except KeyError:
                    pass
                data[table_name][doc_id]['id'] = doc_id
        self.storage.write(data)

    def close(self):
        self.storage.close()
```

**Comment by dcflachs** [comment]
@matthdsm I am glad you were able to work around this, but it may be worth reopening the issue pending input form @msiemens. Based on the documentation, and my previous usage of TinyDB (older versions) I think this is a bug report. My understanding was Documents should have a populated doc_id attribute.

**Comment by msiemens** [comment]
There's a feature request for this in #303 🙃

**Comment by matthdsm** [comment]
reopened at request of @dcflachs,

@msiemens, please close at your leisure.

Cheers
M

**Comment by dcflachs** [comment]
> There's a feature request for this in #303 🙃

I see, I was under the impression that it was already a feature based on the documentation [here](https://tinydb.readthedocs.io/en/latest/usage.html#using-document-ids) "In addition you can get the ID of already inserted documents using document.doc_id. This works both with get and all:"

But looking at the code I see that doc_id insertion is performed by the get and all functions (technically the __iter__ function in the case of all).

**Comment by msiemens** [comment]
Ah, seems like I misunderstood you. You mean adding the document ID as a document field, right? As TinyDB doesn't modify your data, it doesn't add the ID to the document itself but rather sets it an attribute when fetching documents. If you fetch data using `get`, `all`, `search` etc., you always can get the document ID using `doc.doc_id`:

```
doc = db.get(12)
print(doc.doc_id)
```

**Comment by dcflachs** [comment]
I think i may have also misunderstood the issue/request @matthdsm was originally presenting. In my mind i didnt differentiate between adding the ID to the document and having it available as a field.
