### ISSUE TITLE
TinyDB.write_back(...)`` has been removed.  What are we replacing with? 

### ISSUE THREAD

**Issue by Briankp** [msiemens/tinydb#327]
./docs/changelog.rst:53:    - ``TinyDB.write_back(...)`` has been removed
./docs/changelog.rst:190:- Feature: Add ``db.write_back(docs)`` for replacing documents
 What are we replacing with? 

When you design something please keep in-mind the folks that uses your code as a framework.

Now, what do we use?

**Comment by dagraham** [comment]
This works for me with db.update(replace(new_document), doc_ids=[doc_id])

    def replace(new):
        """
        Used with update to replace the original doc with new.
        """
        def transform(doc):
            # update doc to include key/values from new
            doc.update(new)
            # remove any key/values from doc that are not in new
            for k in list(doc.keys()):
                if k not in new:
                    del doc[k]
            return transform

**Comment by msiemens** [comment]
@Briankp I understand you're annoyed that `write_back` has been removed without a clear replacement. This was a difficult decision as it was a feature that wasn't widely used but cluttered the API.

If you depend on `write_back` and the solution @dagraham mentioned doesn't work for you, it should be possible to use a custom table class that adds the `write_back` method again.

**Comment by Briankp** [comment]
Thank you Markus and dagraham for pointing that out. 
Tinydb is one of the original and clever apps out there.
Thank you for making this happen.
