### ISSUE TITLE
Problem when querying by `doc_id`

### ISSUE THREAD

**Issue by Uzay-G** [msiemens/tinydb#329]
When I do `db.all()[0].doc_id`, I clearly see that there is an object of id `1`. Yet when I do this:

```python
query = tinydb.Query()
db.search(query.doc_id == 1)
```

It fails.

I noticed this while trying to remove an object from my db that i knew existed.

**Comment by msiemens** [comment]
Hey @Uzay-G, the query you created is searching for an object that has a field called `doc_id` with the value `1`. But the `doc.doc_id` property is not a field but a property added by TinyDB as TinyDB doesn't modify the data you insert. In other words, if you insert `{'foo': 'bar'}` it will _not_ add a `doc_id` field but add a `doc_id` property to the returned object when fetching data.

To get an object by ID you can use `db.get(doc_id=1)`

**Comment by Uzay-G** [comment]
Oh ok thanks. And so how can I `remove` an entry by querying its doc id?

**Comment by msiemens** [comment]
For removing you can pass a `doc_ids` parameter that takes a list of document IDs: `db.remove(doc_id=[1])`

**Comment by Uzay-G** [comment]
Oh ok thanks!
