### ISSUE TITLE
unable to disable query caching

### ISSUE THREAD

**Issue by Rishirandhawa** [msiemens/tinydb#331]
Hi 
TinyDB.DEFAULT_TABLE_KWARGS = {'cache_size': 0} 
doesn't seem to work. Having 4 separate processes reading and writing to DB every few mins. However, processes that are querying are receiving old data. Any ideas ?

**Comment by msiemens** [comment]
Hey @Rishirandhawa,

Are you using TinyDB v4? Because `TinyDB.DEFAULT_TABLE_KWARGS` has been removed there. You should be able to set `Table.default_query_cache_capacity = 0` or use `db.table('<name>', cache_size=0)` to control the default cache size.

**Comment by Rishirandhawa** [comment]
Ah. That could be the problem. Thanks. I will try it next time I use TinyDB on another project. For now I moved to redis as it supports multi-process environments slightly better.
