### ISSUE TITLE
Index functionality in TinyDB core

### ISSUE THREAD

**Issue by PlatonB** [msiemens/tinydb#334]
TinyDB is really unique DBMS that is simultaneously serverless and perfectly integrates into Python. There have been other attempts, but the corresponding repositories have long been abandoned. But it is difficult to imagine DBMS without even the simplest index functionality.

Suggestions:
- Not an experimental add-on for specific tasks (#286), but a general-purpose solution in the DBMS core.
- At least for one field. If possible - also a primary, but [compound](https://docs.mongodb.com/manual/core/index-compound/) index.

**Comment by msiemens** [comment]
> But it is difficult to imagine DBMS without even the simplest index functionality.

Well, I'd argue that for small datasets an index is more overhead than speedup as you need to keep it up to date, find a way to store it alongside the data itself on disk and integrate it with the query mechanism. Right now TinyDB is a relatively compact code base of around 2000 lines of code. An index implementation would add at least half of that and increasing the complexity considerably.

If you really need an index and using `sqlite` or the like is out of question you're welcome to implement an index yourself, I'd be happy to add it to the extension list. But I myself don't have time to implement and maintain a TinyDB index implementation.

**Comment by PlatonB** [comment]
What is the upper limit of the category "small" in your opinion? How do you categorize 1GB compressed JSON? 20 GB? [Examples](https://ftp.ncbi.nih.gov/snp/latest_release/JSON/).

The offer to do it myself is attractive, but I do not have enough knowledge now. I can only help by thorough testing.

> find a way to store it alongside the data itself on disk

For example, to create indexes as small satellite files. I can give an example of [data](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions/) indexed by the [tabix](http://www.htslib.org/doc/tabix.html) bioinformatics tool.
- Tables sorted by the first two columns: .vcf.gz
- Indexes corresponding to each table: .vcf.gz.tbi

**Comment by msiemens** [comment]
> What is the upper limit of the category "small" in your opinion? How do you categorize 1GB compressed JSON? 20 GB? [Examples](https://ftp.ncbi.nih.gov/snp/latest_release/JSON/).

Well, to me this would definitely fall into the "large" category. If you have a few hundred or a few thousand documents to store, TinyDB will handle it without issues. But your files are more than 1 GB in size, TinyDB most likely will start to get slow.

If you're working pm scientific data analysis, [Pandas](https://pandas.pydata.org/) might be a better fit as it's designed with large data sets in mind whereas TinyDB was designed for small-ish web or CLI applications.
