### ISSUE TITLE
Documentation expansion

### ISSUE THREAD

**Issue by montarion** [msiemens/tinydb#336]
https://tinydb.readthedocs.io/en/stable/usage.html#using-document-ids

says, in the third codeblock:

`db.contains(doc_ids=[1])`

However, the similar `table.contains(doc_ids=[1])` fails, because tables require `doc_id=int`, not `doc_ids=[list]`

**Comment by eugene-eeo** [comment]
Good spot, do you want to write a PR fixing the docs?

**Comment by msiemens** [comment]
I can clear this up. `table.update` and `table.remove` use queries by default and thus operate on multiple documents. For that reason `doc_ids` is a list of document IDs to mirror this behavior. `table.get` returns a single document and thus `doc_id` accepts a single ID.

`table.contains` used to accept a list of document IDs just as it also returns a query. But accepting a list of document IDs leaves the semantics unclear: Does `table.contains(doc_ids=[1, 4, 5])` return `True` if ALL document IDs exist or if only one of those exists? For that reason I changed it to accept a single document ID only in TinyDB v4: `table.contains(doc_id=4)` is unambiguous about when it returns `True` – if a document with this ID is present.
