### ISSUE TITLE
Error with contains with doc_ids

### ISSUE THREAD

**Issue by 0xfede7c8** [msiemens/tinydb#343]
The [docs](https://tinydb.readthedocs.io/en/stable/usage.html) specify that the keyword argument to `contains` is `doc_ids` like this:

```python
db.remove(doc_ids=[1])
```

but I'm getting 

```bash
TypeError: contains() got an unexpected keyword argument 'doc_ids'
```

**Comment by 0xfede7c8** [comment]
Probably changed to `doc_id` and receiving only one argument.
The docs should be updated.

Also, I don't recommend including this breaking changes.

**Comment by daidai21** [comment]
Example code:
```py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-


import os

from tinydb import Query
from tinydb import TinyDB


os.remove('test_tinydb.json')
db = TinyDB('test_tinydb.json')
print(db.insert({'name': 'John', 'age': 22}))
print(db.insert({'name': 'Tom', 'age': 12}))
# https://github.com/msiemens/tinydb/blob/master/tinydb/table.py#L417
print(db.remove(doc_ids=[1, 2]))


print(db.insert({'name': 'Tom', 'age': 12}))
print(db.contains(doc_id=3))
# https://github.com/msiemens/tinydb/blob/master/tinydb/table.py#L291-L293
```


The `db.contains(doc_ids=[...])` should be changed to `db.contains(doc_id=[...])` in [doc](https://tinydb.readthedocs.io/en/stable/usage.html#), about source code [link](https://github.com/msiemens/tinydb/blob/master/tinydb/table.py#L280).

**Comment by msiemens** [comment]
This was simply an oversight when updating the documentation for TinyDB v4.0. I've pushed a fix which is contained in https://tinydb.readthedocs.io/en/latest/.

> Also, I don't recommend implementing breaking changes like this one in the future.

Just to clarify: This was introduced in TinyDB v4 which is a major version where breaking changes are to be expected as specified by Semver. It's also mentioned in the [changelog](https://github.com/msiemens/tinydb/blob/master/docs/changelog.rst#v400-2020-05-02). Of course I shouldn't have forgotten to update the documentation for this particular change but I'm not making breaking changes just for the fun of it. See https://github.com/msiemens/tinydb/issues/284 for details about the changes in v4 and the rationale behind them

**Comment by 0xfede7c8** [comment]
Makes sense, thanks.
