### ISSUE TITLE
Thank you, TinyDB!

### ISSUE THREAD

**Issue by bnnk** [msiemens/tinydb#344]
Hello @msiemens ,
I am really grateful for your TinyDB project, Because your DB is really Amazing!
It helped me so much in my project and  I think this DB will become a Great Success! 👌👌👌
Thank You, @msiemens!

**Comment by msiemens** [comment]
Thank you ❤️ 

> this DB will become a Great Success

To me it already exceeded my wildest dreams and expectations so it's already more than a success to me 🙂
