### ISSUE TITLE
TinyDB creates a new table every time I try to access a singular one.

### ISSUE THREAD

**Issue by CocoaCrispies** [msiemens/tinydb#349]
So when I am trying to read from a database table, It keeps creating a new table, and will not read from the table. There are no errors, so idk what it is. Help would be appreciated :).
https://gist.github.com/CocoaCrispies/91b20a805109043660ee4b8e5637067a

**Comment by msiemens** [comment]
Hey @CocoaCrispies 

Is it possible you're using `int`s as table names? In this case Python will convert the `int`s to strings so next time when you try to read the table, it'll check if the table already exists. But as you're giving an `int` but internally it's a string, it will try to create a new table. If you use `str(ctx.guild.id)` as the table name it should work 🙃

**Comment by CocoaCrispies** [comment]
That might be it, I’ll check back once I’ve tested it!
