### ISSUE TITLE
Comparing Query results, getting multiple docs w/db.contains(list(doc_ids))?

### ISSUE THREAD

**Issue by FallenSpaces** [msiemens/tinydb#353]
Ok, I'm combining this into one issue, because i'm trying to do one thing, and there are different ways I've tried that don't seem to work.

I'm trying to do a query for 3 fields. These fields/filters are received as function kwargs. The problem is that if I add more than a couple fields/filters into one function, the if statements start to get exponentially tedious/complex.

```
def get_listings(filter1='field1', filter2='field2', filter3='field3'):

    if filter1:

        db.search(Listing.field1=='value')

    elif filter2 and not filter1:

        db.search(Listing.field2=='value')

    elif filter1 and filter2:

        db.search((Listing.field1=='value') & (Listing.field2=='value'))

etc...
```

You can see how this could get bad...So here are my attempts at simplifying:

Idea #1 - The simple/natural approach 

- Make a query
- Narrow the results by using search() on the result set. That doesn't work. I can't search the results of another search(), because it's a list, not Documents?

Idea #2 - The more complicated approach

- Get results from each search
- Compare matching docs by using frozenset().intersection()

- Documents can't be turned into a frozenset, (now Documents, not a list?) and will lose their doc_ids if I turned them into a list anyways. As a workaround, I could add the doc_ids to the json objects as they're added to the TinyDB. (Gotta to be a better way right?)

- Finally, with 3x filtered results, and added result['doc_id'] field, I can get new list of documents by using each doc_id. But...how? The documentation doesn't show how to retrieve multiple documents by doc_id. I'm guessing that would look like this: ```db.contains(list(doc_ids))``` If that's not an option, would I then iterate and pull each doc by doc_id, and then add each one into a new list?

I don't really want to add the doc_ids to the json objects, and I also don't want to iterate to get each doc one at a time with contains(). But I will if there isn't a better way!

Hopefully someone who knows this library can show me a better way to accomplish what I'm trying to do. I do this kind of filtering often, and I really like TinyDB so far, so it would be nice to use it more in future projects.

**Comment by eugene-eeo** [comment]
It can be simplified in general:

```
def get_listings(filter_1='field1', filter_2='field2', filter_3='field3'):
    fields = list(filter(bool, [filter_1, filter_2, filter_3]))
    q = Listings[fields[0]] == 'value'
    for x in fields[1:]:
        q = q & (Listings[x] == 'value')
    return db.search(q)
```

**Comment by msiemens** [comment]
What I had in mind is similar to @eugene-eeo's suggestion:

```python
def get_listings(filter1='field1', filter2='field2', filter3='field3'):
    q = Query().noop()

    if filter1:
        q = q & Listing.field1 == 'value'
    if filter2:
        q = q & Listing.field2 == 'value'
    if filter3:
        q = q & Listing.field3 == 'value'

    return db.search(q)
```

This implies that if no filter is set, all documents will be returned. This might or might not be what you intend so you might have to add a check for this case.

**Comment by FallenSpaces** [comment]
> This implies that if no filter is set, all documents will be returned. This might or might not be what you intend so you might have to add a check for this case.

I'm confused as to the point of doing this instead of `db.all()`

But, you're saying that if I don't want to retrieve all docs if no filters are set, then I should add something like ```else: return None``` ?

Thank you both for your examples. It's great to know how to do things in more than one way :-) I'd make the suggestion of adding this situation into the usage docs!

**Comment by FallenSpaces** [comment]
Wait, I'm sorry, I messed this up last night, because I was really tired. 

I'm actually using `filter1 filter2 filter3` as the name of the field.. so:

```
def get_listings(freshness_filter = False, shift_filter = False):

    Listing = Query()

    if freshness_filter: freshness_results = db.search(Listing.freshness == freshness_filter)
    if shift_filter: shift_results = db.search(Listing.shift == shift_filter )

    return matched_results

listings = get_listings(freshness_filter='new', shift_filter='part-time')

```

**Comment by FallenSpaces** [comment]
I messed up my example last night, because I was super tired. 

That being said, the first part of eugene-eeo's answer does not work the way he has it, but the second part, and msiemens answer are close enough to figure out what worked! For future reference, if anyone runs into this problem, here was my working code:

```python
def get_listings(freshness_filter  = False, status_filter= False, shift_filter= False):

	q = Query().noop()
	Listing = Query()
	
	if freshness_filter:
		
		q = q & (Listing.freshness == freshness_filter)

	if status_filter:
	
		q = q & (Listing.status == status_filter)

	if shift_filter:
	
		q = q & (Listing.shift == shift_filter)

	if not freshness_filter and not status_filter and not shift_filter:
		
		return None
	
	return db.search(q)

listings = get_listings(freshness_filter = 'new', status_filter = 'review', shift_filter = 'Part-time')
```

Just as a sidenote for others, including the parenthesis is require after `q &`, or this will not work.

Thank you both!

**Comment by msiemens** [comment]
> Just as a sidenote for others, including the parenthesis is require after `q &`, or this will not work.

You're right. I myself forgot this in my code example but the `&` operator has higher precedence than `==` in Python so parentheses are required to work around that.
