### ISSUE TITLE
Usage for getting latest doc_id is inverted in documentation

### ISSUE THREAD

**Issue by FallenSpaces** [msiemens/tinydb#355]
In the usage docs, getting the latest doc_id is written as:

```python
el = db.all()[0].doc_id
```

When the working code is:

```python
el = db.all()[-1].doc_id
```

**Comment by msiemens** [comment]
Hey @FallenSpaces, thanks for reporting this! Would you be able to create a quick pull request that fixes this?

**Comment by FallenSpaces** [comment]
Thanks for getting me to make my first ever pull request! 😬

**Comment by msiemens** [comment]
Thank you for being open to contribute 🙂 The PR is now merged, the docs have been updated 🙃
