### ISSUE TITLE
Feature idea: db.upsert(dryrun=True) which returns a diff

### ISSUE THREAD

**Issue by vincentdavis** [msiemens/tinydb#378]
I am importing and updating data from many Excel files. For many of the files I want to update the database because I think the data is more correct, some Excel files I think it will fill-in missing data and others may have slightly different coding of the fields.

I would like to have some way to do a upsert(dryrun=True) which returns a diff.

An example:

```python
for row in csvfile:
    changes = db.upsert({FirstName: row['firstname'], 'LastName':row['lastname'], 'Age': row['age']}, 
                     dry_run=True, User.FirstName==rows['firstname'])
   if 'Age' in changes.keys(): # The age value changed
        print(changes['Age']) # prints the old and new value of Age.
```

This could be more of a logging system rather than a dry run.

**Comment by eugene-eeo** [comment]
Hi, another way to simulate this would be to copy the database file, update that instead and then use some library for JSON diffing to see the differences.

**Comment by vincentdavis** [comment]
Maybe a good what to do this is with a decorator and log file. I might try a few ways to do this.
I am not sure this feature idea is a good one. It would be useful for me but that does not mean it should be part of TinyDB. 
Another feature might be data validation, maybe using something like pydantic. I might play with a way to do this.

> Hi, another way to simulate this would be to copy the database file, update that instead and then use some library for JSON diffing[1](https://pypi.org/project/deepdiff/) to see the differences.

**Comment by msiemens** [comment]
>  Another feature might be data validation, maybe using something like pydantic. I might play with a way to do this.

If you find a solution that works for you, feel free to post it here if you feel it could help others. I'll close this issue for now
