### ISSUE TITLE
Atomic read/writes

### ISSUE THREAD

**Issue by Specy-wot** [msiemens/tinydb#381]
I just wanted to know something, is the whole database (the json file) loaded in memory when you create the database with 
`TinyDB("yourJson.json")` ?
If it is, are read / writes atomic? as in, if i have two async functions that read / write to the database, are the read/writes executed immediately (or one after another) without having conflicts or concurrency issues?

**Comment by msiemens** [comment]
TinyDB uses `json.load` and `json.dump` for reading/writing JSON files which is as atomic as you can get with Python. I think that as long as only one process/thread accesses the JSON file, it should work fine with async. If however the async implementation utilizes multiple threads, it will lead to concurrency issues.

**Comment by Specy-wot** [comment]
Ok thanks!

**Comment by msiemens** [comment]
If you find that using TinyDB with Python's async causes issues, feel free to comment here so I can update the documentation accordingly!
