### ISSUE TITLE
'Table' object has no attribute 'multiple_insert'

### ISSUE THREAD

**Issue by earlev4** [msiemens/tinydb#387]
Hi!

Good day to you! I am new to the tinydb library. I greatly appreciate all the effort and work that has gone into creating and maintaining tinydb!

I am using the most current version of tinydb (4.4.0). 

I am hoping someone can help provide some guidance on this issue and this is just a simple oversight on my part.

I have a list of OrderedDict items.

```
type(song_list)
list

type(song_list[0])
collections.OrderedDict
```
Imagine the structure of the first item is:
```
song_list[0]
OrderedDict([('Title', 'All Together Now'),
             ('Artist', 'The Beatles'),
             ('Recorded', '05/12/1967'),
             ('Album', 'Yellow Submarine'),
             ('Producer', 'Paul McCartney')])
```
When trying to create a tinydb database and use 'multiple_insert':

```
from tinydb import TinyDB, Query, where
db = TinyDB('db.json')
db.multiple_insert(song_list)
```
I receive the following error.
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-bdd5a496ac97> in <module>
----> 1 db.multiple_insert(song_list)

~/anaconda3/lib/python3.8/site-packages/tinydb/database.py in __getattr__(self, name)
    248         Forward all unknown attribute calls to the default table instance.
    249         """
--> 250         return getattr(self.table(self.default_table_name), name)
    251 
    252     # Here we forward magic methods to the default table instance. These are

AttributeError: 'Table' object has no attribute 'multiple_insert'
```
I read the following documentation. 
https://tinydb.readthedocs.io/en/latest/getting-started.html#basic-usage
https://tinydb.readthedocs.io/en/stable/usage.html#inserting-data

I am wondering if the error is due to the list consisting of an OrderDict and not a dict.

Any assistance or insight would be greatly appreciated.

Thanks so much!

**Comment by earlev4** [comment]
Please forgive the posted issue. I just noticed that `multiple_insert` should be `insert_multiple`. Thanks so much!

**Comment by msiemens** [comment]
Hey @earlev4! No worries, I'm glad you were able to fix the issue 🙂
