### ISSUE TITLE
Improve documentation on custom serializers

### ISSUE THREAD

**Issue by lyz-code** [msiemens/tinydb#388]
Even though the feature was [merged in 2015](https://github.com/msiemens/tinydb/pull/50), I found no reference of how to use them in the docs. I eventually arrived to [tinydb-serialization](https://github.com/msiemens/tinydb-serialization) where it's clear how to do it.

I think it would be useful to add some pointer in the docs to make it easier for developers

**Comment by lyz-code** [comment]
Sorry, I didn't saw #371 , maybe this can be a comment there

**Comment by msiemens** [comment]
> I think it would be useful to add some pointer in the docs to make it easier for developers

If you found this in 2015, this was most likely part of the 2.x version of TinyDB. When I released TinyDB 3.0 which moved custom serializers to a separate package, there was a note about this in the [release notes](https://github.com/msiemens/tinydb/blob/master/docs/changelog.rst#v300-2015-11-13). But I'll add a note on the PR you mentioned in case someone else finds the reference to this feature when going through old pull requests 🙂

**Comment by msiemens** [comment]
I've added a note in the PR discussion. If you thinks this needs more documentat, feel free to comment and I'll reopen the issue
