### ISSUE TITLE
Searching for keys

### ISSUE THREAD

**Issue by Hunter2807** [msiemens/tinydb#396]
Hey there! 

I really love this project, and want to use it to try make an AI... What I wanna do is, the format should be `{question : [list of answers]}`... How can I search for the keys, given a text from the db? Help would be appreciated. 

Thanks in advance!

**Comment by msiemens** [comment]
Hey @Hunter2807, could you provide an example of how exactly the database you think of would look like?

**Comment by Hunter2807** [comment]
Hey @msiemens thanks for answering to this ticket

So what I want to achieve is, I want to try make an AI, which would learn whenever a person would type anything, and just stores it in JSON format... I have tried using JSON, but it didn't work.. This is what the data structure should look like

```json
{
"question": [list of responses], 
"question 2": [list of responses]
}
```
And so on... So I want to query for the keys, and check if the given text is a key... Suppose I query for a text `question`. It's a key, so it would append the response in it's value list... 
But if I then query for `question 3`, it ain't there in the keys... So it would just make a new key value pair out of it, and just update the file...

**Comment by msiemens** [comment]
Ah, you want to query for documents that for example have a `'question'` key, is that correct? Right now that case is sort of unsupported by TinyDB by which I mean there's no direct mechanism to construct a query like this. But you could work around that by passing a function to `search` which evaluates to `True` if a document matches your query:

```
print(db.search(lambda doc: 'question' in doc))
```

Would that work for your case?

I'll make a note to document this for the documentation restructuring.

**Comment by msiemens** [comment]
Wait, I just realized that this workaround won't really mesh well with the query cache as `lambda`s don't necessarily have a stable hash value. So instead I'd suggest using something like this for now:

```python
# globally:
q = lambda doc: 'question' in doc

# later:
db.search(q)
```

You'd have to make sure that you don't recreate the query lambda for each invocation of `search` to make sure the query cache recognizes that it's still the same query. 

In the medium run I think we shoud add support for something like this:

```python
Question = Query()

db.search('question'  in Question)
```

What would you think about an API like this?

**Comment by eugene-eeo** [comment]
An alternative is this, if you need nice nesting:

```
noop = lambda x: True
db.search(Query().key1.test(noop))
db.search(Query().key1.key2.test(noop))
```

It is likely to be _slightly_ slower than using a regular lambda, since this requires catching exceptions.

**Comment by msiemens** [comment]
Wait, just as I wanted to write this feature I realized that the docs already mention this type of query:

```python
>>> # Existence of a field:
>>> db.search(User.name.exists())
```

That should work here too, is that correct? Something like this?

```python
db.search(where('question 3').exists())
```

To be fair, this isn't located in the most obvious place (it's in the [Advanced Queries](https://tinydb.readthedocs.io/en/latest/usage.html#advanced-queries) section. I think a reworked documentation should make it easier to find this type of query.

**Comment by msiemens** [comment]
> Wait, just as I wanted to write this feature I realized that the docs already mention this type of query:
> 
> ```python
> >>> # Existence of a field:
> >>> db.search(User.name.exists())
> ```

@Hunter2807 Does this solve your issue?

**Comment by rewritten** [comment]
I think that @Hunter2807 was looking into a way to treat a _single_ dictionary as a database, finding key/value pairs (actually just values) by key.

The data format that would work for this use case, if TinyDB is going to be used, is:
```json
[
  {"question": "question 1", "responses": ["list of responses"]},
  {"question": "question 2", "responses": ["list of more", "responses"]},
  {"question": "question 3", "responses": []}
]
```

and then the query would be `db.search(Question.question == searched_question_text)`.

**Comment by Hunter2807** [comment]
Ah yea sorry for being inactive since a few days. Actually the issue was solved, sorry for being a bother
