### ISSUE TITLE
Python 3.3 - ImportError: cannot import name ABC

### ISSUE THREAD

**Issue by pruppert** [msiemens/tinydb#400]
I am tying to develop a Sublime Text package that includes tinyDB. I have successfully added tinyDB to the package, but when trying to run it under Sublime's Python 3.3 environment, I get the following error:

```
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/MyPackage/tinydb/storages.py", line 9, in <module>
    from abc import ABC, abstractmethod
ImportError: cannot import name ABC
```

Anyone know what is going on here or how to fix?

**Comment by msiemens** [comment]
If you're bound to use Python 3.3, you can use TinyDB v3.10.0 which is the most recent version that still had Python 3.3 official support. Maybe a couple of the following releases might work as well, but I haven't tested at which point Python 3.3 breaks. You can also access old versions oft the documentation, e.g. the [version for TinyDB 3.10.0](https://tinydb.readthedocs.io/en/v3.10.0/index.html)

**Comment by pruppert** [comment]
Thank you. I also have the option of running the sublime plugin under python 3.8. When I try to use tinyDB (4.4.0) under python 3.8, I get shown the following error:

```
    if issubclass(t, ApplicationCommand) and t is not ApplicationCommand:
TypeError: issubclass() arg 1 must be a class
```

Any idea what is going on there?

**Comment by msiemens** [comment]
Interesting. That doesn't seem to be an error within TinyDB as TinyDB doesn't have an `ApplicationCommand` 🙂

**Comment by pruppert** [comment]
Thank you for the time in responding. The 3.3 incompatibility was very helpful to know. I’ll follow up with sublime folks on the 3.8 error.
