### ISSUE TITLE
Uuid do not can't used like a key 

### ISSUE THREAD

**Issue by lolio-dev** [msiemens/tinydb#411]
Hello, when I insert a doc with a key named 'uuid' nothin append, I don't have anny error, and i don't have the item in the db. On the other hand, if I insert an other doc after the doc will have an id of '2', while it is the first doc visible of the db. It's a bug or a feature ?

**Comment by msiemens** [comment]
Hey @lolio-dev, could you provide a short example code snippet? Do you insert a document like `{'uuid': 'something'}`? Or do you set a custom document ID like `Document({...}, '<uuid>')`? In the latter case, you'd need to teach TinyDB to handle UUIDs as by default it uses incrementing integers as document IDs. This could be done like this:

```python
class Table(TinyDBTable):
    document_id_class = UUID

    def _get_next_id(self):
        return uuid4()


class DB(TinyDB):
    table_class = Table
```

**Comment by lolio-dev** [comment]
Hello @msiemens 
I try to use uuids like this : 
```py
SetupDb.list_table.insert({
                'uuid': str(self.uuid),
                'title': self.title,
                'owner': self.owner,
                'creation_date': self.creation_date,
                'authorized_persons': self.authorized_persons,
                'tasks': tasks,
})
``` 
because I didn't find how to set custom id to documents, thanks you very much for the response !

**Comment by msiemens** [comment]
I'm closing this issue as it seems suggested solution works.. Feel free to re-open it it's still an issue.

**Comment by er-raoniz** [comment]
@msiemens I received the following error when I used UUID as the default id based on your suggested implementation - 
`Unexpected error occurred: badly formed hexadecimal UUID string`

**Comment by msiemens** [comment]
@er-raoniz Can you create a new issue and post the full stack trace there?
