### ISSUE TITLE
No module named 'typing_extensions' v4.5.0

### ISSUE THREAD

**Issue by mathben** [msiemens/tinydb#413]
```bash
   File "/usr/local/lib/python3.7/dist-packages/tinydb/__init__.py", line 27, in <module
     from .queries import Query, where
   File "/usr/local/lib/python3.7/dist-packages/tinydb/queries.py", line 28, in <module>
     from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```
Running `pip install typing_extensions` fixed it. So this package is probably missing from the setup.py for version 4.5.0

**Comment by eugene-eeo** [comment]
Yup -- there is no `Protocol` in [Python 3.7's typing](https://docs.python.org/3.7/library/typing.html).
It was only added on [Python 3.8](https://docs.python.org/3.8/library/typing.html#typing.Protocol).

**Comment by msiemens** [comment]
Oh, seems like this is by accident. I did consider this case and added `typing_extensions` as a dependency:

```toml
typing-extensions = { version = "^3.10.0", python = "<3.7" }
```

But as you can tell, I mistakenly used `<` instead of the correct `<=`. I'll publish a patch release today :)

**Comment by msiemens** [comment]
Version 4.5.1 has been pushed, the CI pipeline should publish the release in the next couple of minutes 🙂
