### ISSUE TITLE
Convert type before query

### ISSUE THREAD

**Issue by yashrathi-git** [msiemens/tinydb#420]
I have stored datetime fields using tinyDB in this format `2021-07-26T20:53:43`. But is there a way to convert them to `datetime` before I query them so that I can compare them with other `datetime` objects like this. 

`d.search(date(year=2014, month=10, day=4)<=Query().time.started_at<=date.today())`

**Comment by yashrathi-git** [comment]
I was able to get required behaviour using [tinydb-serialization](https://github.com/msiemens/tinydb-serialization)

**Comment by msiemens** [comment]
@yashrathi-git You're right, this would be the proper way to store custom objects in TinyDB :)
