### ISSUE TITLE
Random - Question

### ISSUE THREAD

**Issue by ChrisChross** [msiemens/tinydb#436]
hey @msiemens,

this package is nicely implement. 
I have a question, how would you retrieve a random entry from the db? 
Let's say you have stored 100 users and you want to randomly pick one.
How would you do it? Could you over a function for it in one of the next releases?
For example: ´random_user  = db.random()´

**Comment by jasonhamilton** [comment]
It looks like you should be able to call db.all() to the all of the docs.  You should be able to get the length of all items with len().  Then select a random index value limited by the length.

**Comment by msiemens** [comment]
@ChrisChross I think the easiest way to do this is to use [`random.choice`](https://docs.python.org/3/library/random.html#random.choice). If you pass a list to this function, it will return a random element:

```python
doc = random.choice(db.all())
```

I think this is doesn't need to be a part of TinyDB itself as `random` is provided with Python itself and thus should be available everywhere where TinyDB can run 🙂

**Comment by ChrisChross** [comment]
cool, thanks!
