### ISSUE TITLE
Examine structure of database

### ISSUE THREAD

**Issue by pjakobsen** [msiemens/tinydb#44]
Not sure if this is a feature request or a documentation issue, but it would be great to have a facility where you can ask the database for it's structure,  sort of like asking for the columns of a table in SQL with DESCRIBE name_of_table; or calling keys() on a python dictionary.

In general, I'm looking for guidance on how to examine a TinyDB database when you're not quite sure what it contains.

**Comment by eugene-eeo** [comment]
@pjakobsen see https://gist.github.com/eugene-eeo/849eab3134bed48a4f0f

**Comment by msiemens** [comment]
@pjakobsen It seems like @eugene-eeo's solution works for you so I'm closing this.
