### ISSUE TITLE
Can't write accent in database

### ISSUE THREAD

**Issue by SomeMinecraftModder** [msiemens/tinydb#448]
So i have a issue with TinyDB: i'm trying to write text with accent to a database. it work, except in the json file, it look like this:
`"title": "\u00c3\u00a9\u00c3\u00a9\u00c3\u00a9\u00c3\u00a9\u00c3\u00a9\u00c3\u00a9"`
normaly it should look like this:
`"title": "éééééééé"`
(ignore the questionable content)
and when i fetch it with where(), it look like this:
`Ã©Ã©Ã©Ã©Ã©Ã©`
i have tried` ensure_ascii=False` but it still doesn't work. is this a bug or i am doing something wrong?

**Comment by msiemens** [comment]
Interesting! What version of TinyDB do you use? I just did a quick test and opening the database file with `TinyDB('test.db', ensure_ascii=False)` made the content look correct.

**Comment by SomeMinecraftModder** [comment]
well after some testing, it seem that this is an issue with bottle. guess you can't help me but still thanks!

**Comment by msiemens** [comment]
Okay, I'm closing this issue then. I'm glad you were able to figure it out 🙂
