### ISSUE TITLE
insert only if document not exists

### ISSUE THREAD

**Issue by LeiYangGH** [msiemens/tinydb#464]
I think this is a very common use case of CRUD operations. what I want:

```python
        doc = {'name': 'John', 'like': 'eggs'}
        db.insert(doc)
        if not db.contains(doc):
            db.insert(doc)
```
but the check doesn't work. I know `Query` syntax can solve:
1. query like `db.search(User.name == 'John')` will do, but it requires defining an unique key to the object.
2. insert method returns the Id, so can also check the Id exists, but it requires extra code to record the Ids.

What's the point of allowing inserting the same document multiple times?
Can insert method automatically check for duplicates?

**Comment by MrPigss** [comment]
The default implementation of tinydb, without custom tables, storages, middleware's,.... automagically generates an integer as a unique key (the doc_id) so u can search specific entries even if their contents are the same.
So every dictionary gets transformed into a [Document ](https://github.com/msiemens/tinydb/blob/967dbf9197b2943eb9bd91650f90bd9ab497bc12/tinydb/table.py#L26-L36)on insert.

> What's the point of allowing inserting the same document multiple times?

You can't.
You CAN insert Documents with the same _contents_, but these will have different doc_id's generated for them.
In other words, you can insert the same dictionary multiple times, but these dicts will get transformed into different Documents with different doc_id's.

For example:
This might be useful for an eventlog where the same event can happen multiple times.
(Of course it would be useful to use the date-time as a unique key in this case.)

> Can insert method automatically check for duplicates?

Not without losing a lot of functionality.

It is however possible to customize this behavior see [the docs](https://tinydb.readthedocs.io/en/latest/extend.html#subclassing-tinydb-and-table) for more info. but this requires a bit more work.

What you can do is use the fragment method:
```python
doc = {'name': 'John', 'like': 'eggs'}
db.insert(doc)
if not db.contains(Query().fragment(doc)):
    db.insert(doc)
```
This will check for a document containing these keys.

Let me know if this answered your question.

**Comment by LeiYangGH** [comment]
Thanks for your explanations. I think the `fragment` query is generic enough and can satisfiy my requirements.
Thank you!

**Comment by msiemens** [comment]
@MrPigss You're spot on!

TinyDB has the ability to store multiple documents with the same contents because in some cases, that's what you want to do. @MrPigss's suggestion of using a `fragments` query is the easiest solution to this, but one could also use the `upsert` method to skip the condition block:

```python
doc = {'name': 'John', 'like': 'eggs'}
db.upsert(doc, Query().fragment(doc))
```

See [Upserting Data](https://tinydb.readthedocs.io/en/latest/usage.html#upserting-data) in the documentation for details on how the `upsert` operation works.

**Comment by LeiYangGH** [comment]
Thanks, this method can reduce one line of if else block.
