### ISSUE TITLE
Suggesting Optimization for _update_table function

### ISSUE THREAD

**Issue by corradods** [msiemens/tinydb#480]
I know TinyDB is not for high performance, but it seemed very strange to me that this code was taking forever, especially since there is no IO.
Example:
```
db = TinyDB(storage=tinydb.storages.MemoryStorage)
db.drop_tables()
for i in tqdm(range(1000000)):
    db.insert(tinydb.table.Document({'key': 'value'},doc_id=i))
```

The culprit seems to be these parts of the code in the function tinydb/table.py -> Table._update_table(...) :

```
        # Convert the document IDs to the document ID class.
        # This is required as the rest of TinyDB expects the document IDs
        # to be an instance of ``self.document_id_class`` but the storage
        # might convert dict keys to strings.
        table = {
            self.document_id_class(doc_id): doc
            for doc_id, doc in raw_table.items()
        }

#...#
        # Convert the document IDs back to strings.
        # This is required as some storages (most notably the JSON file format)
        # don't support IDs other than strings.
       tables[self.name] = {
            str(doc_id): doc
            for doc_id, doc in table.items()
        }
```

The comments are clear.  However, the overhead of this is huge, especially if i don't need it (e.g., i am not using a json file format, or i am already using strings as doc_ids type).
I extended Table for implementing a custom version of  _update_table function  that simply skip these conversion steps, and the example code can do the job in few seconds instead of being unfeasible.

another case of study:
```
CachingMiddleware.WRITE_CACHE_SIZE = 100000
Table.document_id_class = str
db = TinyDB('db.json', storage=CachingMiddleware(JSONStorage))

for i in tqdm(range(1000000)):
    db.insert(tinydb.table.Document({'key': 'value'},doc_id=str(i)))

```

So my question is, is it worth it?
And is it correct that this optimization is in the base table class?
Shouldn't it be borne by middlewares or storages which actually introduce the need for the optimization?

**Comment by msiemens** [comment]
Hey @corradods,

I think this is a case where TinyDB tries to be flexible, but this flexibility comes at a cost. It is true that when you use the `MemoryStorage` or any other storage that supports arbitrary types for `dict` keys, this conversion is not needed. But, crucially, TinyDB does not know whether the storage will silently convert any `dict` key to string, as e.g. JSON does [1], or not.

There are ways this could be addressed, from making a storage tell if it will convert keys to strings to moving the task of converting keys to the storage altogether. But one way or another, this would require a breaking change to TinyDB's API and thus force the release of a new major version. Short of that, one could find stop-gap solutions like add a setting called `dont_convert_keys_i_know_what_i_am_doing` or something like that. But that's not a big improvement to extending the `Table` class and overriding the ` _update_table` method. So I think your solution to this is quite fine.


> is it worth it?

This question I can't answer for you 🙂 If you profile your program and find that this improves optimization performance of your application measurably, I guess it is worth it. As long as you're happy to maintain your patch of the `_update_table` method.

[1]: In JSON, all object keys MUST be strings, see https://www.json.org/json-en.html.

**Comment by corradods** [comment]
Hey @msiemens, 
thankyou for your answer.
When I asked "is it worth it?" I meant to have this very big overhead in managing large db to agnostically support  any doc_id/storage  type :).

About my program (that used a json with only string keys as design choice), well that part of the code was responsible for more than 90% of the execution time for doing nothing, so yes I get rid of it :D

Thanks, see you!

**Comment by msiemens** [comment]
> When I asked "is it worth it?" I meant to have this very big overhead in managing large db to agnostically support any doc_id/storage type :).

Got it! I honestly don't think TinyDB could do (or be as popular as it is) without JSON support. And if you have JSON support, converting document IDs is a necessity. So this problem has to be solved one way or another 🙂
