### ISSUE TITLE
convert type before matching in query

### ISSUE THREAD

**Issue by LeiYangGH** [msiemens/tinydb#485]
I have a field `foo` which type sometimes are int, but sometimes are string(of numbers).
If I compare directly, I will get error such as 

> TypeError: '<=' not supported between instances of 'int' and 'str'

I tried convert to int, `int(q.foo) <= given_int` but got

> TypeError: int() argument must be a string, a bytes-like object or a number, not 'Query'

I searched document and found [test](https://tinydb.readthedocs.io/en/latest/usage.html#advanced-queries) function can determine the field type

```python
        test_is_str = lambda s: isinstance(s, str)
       ...((q.foo.test(test_is_str)) & (q.foo <= str(given_int)))
        test_is_int = lambda s: not isinstance(s, str)
        ...((q.foo.test(test_is_int)) & (q.foo <= given_int))
```
But this way code seems too verbose, is there any simpler syntax to convert type before query?

**Comment by msiemens** [comment]
Hey @LeiYangGH,

I think you can use the `map()` query operator here:

```python
db.search(where('num').map(int) > 0)
```

This assume that all `num` fields are numbers or strings that represent numbers. Otherwise, you can cast to a default value like `NaN`:

```python
db.search(where('num').map(lambda x: int(x) if isinstance(x, int) or x.isnumeric() else float('nan')) > 0)
```

Does that work for you?

**Comment by LeiYangGH** [comment]
i think `map` works, thanks!

**Comment by msiemens** [comment]
Awesome 🙂
