### ISSUE TITLE
Query multiple docs by ID

### ISSUE THREAD

**Issue by pylipp** [msiemens/tinydb#486]
As a follow-up to #329 , how can I query for multiple docs using their IDs? Like 

```
doc_ids = [1, 2, 5]
db.search(doc_ids=doc_ids)
```

`db.get(doc_id)` exists but only for a single document. I could iterate over the list of doc IDs yet this might not be as efficient.

**Comment by msiemens** [comment]
That's interesting! Maybe we can make `db.get()` support a list of document IDs as `doc_id` (similar to `.remove()` does – altough it does have a `doc_ids` instead of `doc_id`). I'll have to think about that!

**Comment by Atmden** [comment]
И как в итоге получить записи по списку doc_id?
Не получается использовать в search массив из doc_ids

**Comment by patrick-nicodemus** [comment]
I would like to bump this feature request as I have a use-case for it.

**Comment by keenborder786** [comment]
Hey , I will have a look into it and start working on it.

**Comment by keenborder786** [comment]
@msiemens I have created a PR that inserts the given feature request. Please see #504
