### ISSUE TITLE
Empty table does not persist

### ISSUE THREAD

**Issue by dmarsic** [msiemens/tinydb#513]
Hi,

I attempted to create empty tables, similar to `CREATE TABLE` in SQL. TinyDB currently does not persist empty tables:

1. My initial approach didn't create a table because `Table` does not call `_update_table()` when [creating an instance](https://github.com/msiemens/tinydb/blob/master/tinydb/table.py#L97).

```python
In [1]: from tinydb import TinyDB

In [2]: db = TinyDB("example.json")

In [3]: t = db.table("emptytbl")

In [4]: db.close()

In [5]: from pathlib import Path

In [6]: Path("example.json").read_text()
Out[6]: ''
```

2. Workaround with adding `truncate()` call to ensure that the table gets written.

```python
In [1]: from tinydb import TinyDB

In [2]: db = TinyDB("example.json")

In [3]: t = db.table("emptytbl")

In [4]: t.truncate()

In [5]: db.close()

In [6]: from pathlib import Path

In [7]: Path("example.json").read_text()
Out[7]: '{"emptytbl": {}}'
```

I'm new to the project so I'm not sure if this is intentional. I propose adding a flag to `Table`, `persist_empty: bool = False`, and if the flag is true then call `_update_table` to ensure an empty table gets immediately written.

I'm happy to submit a PR if that makes sense.

**Comment by msiemens** [comment]
That's an interesting point. You're right, right now calling `table(...)` is a lazy operation that does not touch the file system until data is written to the table for the first time. I'd be happy to accept a PR for this 🙂

**Comment by msiemens** [comment]
PR #518 has been merged 🙂
