### ISSUE TITLE
Symlink git bug

### ISSUE THREAD

**Issue by andreao** [msiemens/tinydb#52]
Tried to clone the repository and got the following error:
    error: unable to create symlink CONTRIBUTING.rst (File name too long)

Managed to work around it by cloning without checking out, and disabling symlinks:
    git clone --no-checkout git@github.com:msiemens/tinydb.git
    git config core.symlinks false
    git checkout

Running OSX Yosemite.

**Comment by eugene-eeo** [comment]
It's not really an issue with TinyDB as I also had the same error when I cloned some other repository, but it was "CHANGES.rst" instead of "CONTRIBUTING.rst". I would (naively) to blame it on Apple's broken filesystem implementation but I think it's fixed in the latest git update.

**Comment by msiemens** [comment]
Thanks for reporting this. I've now changed CONTRIBUTING.rst to be a regular file and not a symlink.
