### ISSUE TITLE
Segfault on instantiation

### ISSUE THREAD

**Issue by andreao** [msiemens/tinydb#53]
Unable to use TinyDB due to the following bug

> python
Python 2.7.3 (v2.7.3:70274d53c1dd, Apr  9 2012, 20:52:43) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tinydb import TinyDB
>>> TinyDB("test")
Segmentation fault: 11

Same error in all versions of TinyDB.
Running OSX Yosemite.

**Comment by andreao** [comment]
Upgraded to python 2.79 and problem disappeared.

**Comment by msiemens** [comment]
For future reference: this might be related to this [StackOverflow thread](http://stackoverflow.com/q/19531969/997063), but I can't verify if that's true

**Comment by eugene-eeo** [comment]
:+1: as I had some problems in the past with Python 2.x as well when upgrading to Yosemite.
