### ISSUE TITLE
Does tinyDB support multi-thread/process access ?

### ISSUE THREAD

**Issue by sequoiar** [msiemens/tinydb#530]

**Comment by MrPigss** [comment]
Short answer: no.
Longer answer: I you make sure to use [multiprocessing Locks](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Lock) or [threading Locks](https://docs.python.org/3/library/threading.html#threading.Lock) in the appropriate places then it should be fine. But there's probably a better way.

**Comment by msiemens** [comment]
@MrPigss is correct here. The alternative is to use https://github.com/eugene-eeo/tinyrecord as a wrapper around TinyDB
