### ISSUE TITLE
Are there any option to persist query caches?

### ISSUE THREAD

**Issue by miratcan** [msiemens/tinydb#536]
(If there is it can be run very fast I think.)

**Comment by fenchu** [comment]
Tinydb is just a dict of objects keyed from "1" and upwards,
It is intended as a simple structure for small datasets.
You can cache on the putside by adding a wrapper around the db.search() routine.
if you need this then go for redis or another database.

**Comment by msiemens** [comment]
I full agree with @fenchu. If you're in a state where you gain a significant amount of performance by persisting the query cache, I think you'd gain at least an order of magnitude by switching to a more sophisticated database system like Sqlite (which has quite extensive [JSON support](https://www.sqlite.org/json1.html)!) or something like [DuckDB](https://duckdb.org/).
