### ISSUE TITLE
Broken link in documentation.

### ISSUE THREAD

**Issue by kamajus3** [msiemens/tinydb#539]
In the documentation's Introduction section into [Tiny PyPi](https://pypi.org/project/tinydb/), there is a link that references PyMongo. This link is intended to provide additional information or context for users. However, when users attempt to follow this link, it is found to be broken or unresponsive, leading to an error.

**Section in Question:**
In the Introduction section, the following paragraph includes the broken link:

written in pure Python: TinyDB neither needs an external server (as e.g. **PyMongo**) nor any dependencies from PyPI.

**Comment by msiemens** [comment]
Closed in #542
