### ISSUE TITLE
Remove print("Okay!")

### ISSUE THREAD

**Issue by WarmongeR1** [msiemens/tinydb#55]
Hi all, remove "print("Okay!")" please

tinydb/tinydb/middlewares.py: line 171

code:

                    for field in item:
                        try:
                            if item[field].startswith(tag):
                                print('Okay!')

**Comment by msiemens** [comment]
Oops! Seems like I didn't remove all debug output properly :blush: Thank you for reporting!

**Comment by msiemens** [comment]
I've now released v2.3.2 which fixes this issue :smiley:
