### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by ueg1990** [msiemens/tinydb#56]
Hello,

I did not know how to get in touch so i thought might as well say it here. This is a very interesting project....i read the docs and will start playing with tinyDB. I would also love to start contributing (since the project is still "tiny" :P ) and i wanted to ask what are the plans/features for future versions and how i can help :)
I was really looking for a project where i can contribute towards a python-implemented database (hopefully will get some experience from this project) and write my own later :) 

Sorry again for raising an issue for this

**Comment by msiemens** [comment]
Great to hear that you want to contribute! At the moment I don't have any specific plan for new features as I think its core is quite complete. Do you have something specific in mind what is missing?
Other than that I think TinyDB would benefit from some more useful extensions like [TinyRecord](https://github.com/eugene-eeo/tinyrecord). If you have some ideas for new extensions, I'll gladly link to them in the README.

**Comment by ueg1990** [comment]
havent played much with tinydb yet but will keep following this repo and if something comes to mind, will definitely contribute :)
