### ISSUE TITLE
Atomic update operation?

### ISSUE THREAD

**Issue by phreeza** [msiemens/tinydb#6]
Not sure how hard this would be to implement, but it would be neat to have a safe way of updating an entry. Right now I am deleting and then inserting the new entry, which seems the only way to do this, but it is quite unsafe, for example if the program is terminated right between the write and delete steps the database may become corrupted.

If there is interest in this, I would be willing to put in some work, if someone can give me guidance. Does it fundamentally go against the philosophy, or would it make sense?

**Comment by alexreg** [comment]
I hope you don't mind me asking here: is the present `update` method atomic for a single-document update, or not even that?

**Comment by msiemens** [comment]
> I hope you don't mind me asking here: is the present `update` method atomic for a single-document update, or not even that?

That depends on how exactly you define atomicity. If you're looking for atomicity as used in the ACID acronym, TinyDB doesn't come with atomicity by default. As mentioned above, one could implement some sort of atomicity by writing data to a temporary file first and then renaming it to the actual file.

But in general, TinyDB simply writes the whole database to disk on every write operation. If the Python interpreter dies or crashes mid-way, TinyDB doesn't provide any guarantees about data integrity out of the box (aside from a custom storage that provides a basic level of atomicity as mentioned above).

**Comment by alexreg** [comment]
Okay, thanks for clarifying. I think I'll go with tinyrecord, which as I understand, provides that.
