### ISSUE TITLE
Weird 'u' Printing in Front of Key-Values after db.all()

### ISSUE THREAD

**Issue by Psuedosupergenius** [msiemens/tinydb#65]
Using tinydb 2.3.2 in python 2.7.10 on mac OSX 10.10.4 I input a simple model db and then type:
db.all()

output is:

[{u'count': 7, u'fruit': u'apple'},
 {u'count': 12, u'fruit': u'peach'},
 {u'count': 5, u'fruit': u'banana'},
 {u'count': 4, u'fruit': u'kiwi'},
 {u'count': 3, u'fruit': u'mango'}]

Any idea why the letter 'u' is appearing?

**Comment by Psuedosupergenius** [comment]
Is that showing 'u' for unicode like an encoding issue?  Can I type something like db.encode("ascii") to get rid of the unicode?

**Comment by eugene-eeo** [comment]
Doesn't the standard json library return Unicode strings? Try ``json.loads('{"js":true}')``.

**Comment by msiemens** [comment]
This is actually documented behaviour: [TinyDB: Remarks on Storages](http://tinydb.readthedocs.org/en/latest/usage.html#remarks-on-storages)
