### ISSUE TITLE
New operation to update an array's value

### ISSUE THREAD

**Issue by raquel-ucl** [msiemens/tinydb#66]
I think it'd be useful to have an updating operation to append to an array element. I've tried this successfully:

```python
def append(field, value):
    """
    Append a given value to a given array field.
    """
    def transform(element):
        element[field].append(value)

    return transform
```

Can be used as:

```python
db.update(append("some_array_field","value_to_append"), eids=[1,2])
```

Perhaps it needs some try/catch in case the element is not an array and the value can't be appended.

**Comment by msiemens** [comment]
Thanks @raquel-ucl for posting your solution. I'm sure this is useful but I'm not sure whether this should ship with TinyDB. If we'd add this, we should also add all other array operations, and there are a lot of them. What are your thoughts on this? Maybe we should have a wiki or something to collect such snippets...

**Comment by msiemens** [comment]
No answer since 1 Oct 2015, closing this issue. Feel free to re-open if this is still an issue.

**Comment by karimawii** [comment]
I hope this gets added
