### ISSUE TITLE
search or count does not rereads a modified file

### ISSUE THREAD

**Issue by nachopro** [msiemens/tinydb#68]
Hi, I am a newbie tinydb user. I have a problem/feature:
I'm running an thread that insert rows validating their oneness with "count(where(..."
The problem occurs when I remove the row or purge from another side (ie ipython): the count/search thinks that the row exists.

Some suggestion? Thanks!

**Comment by msiemens** [comment]
Hey @nachopro, could you post an example script where this problem occurs?

**Comment by msiemens** [comment]
No answer since 1 Oct 2015, closing this issue. Feel free to re-open if this is still an issue.
