### ISSUE TITLE
Release on anaconda.org

### ISSUE THREAD

**Issue by richardotis** [msiemens/tinydb#71]
It would be great if tinydb were regularly released on www.anaconda.org . This would make things nicer for your downstream package authors so that we don't have to host tinydb in our own unofficial channels like https://anaconda.org/richardotis/tinydb/files since it won't always have the latest version. You can download one of those files and see an example of a simple recipe file.

I have an example workflow for uploading to anaconda.org on https://github.com/richardotis/pycalphad/blob/develop/RELEASING.rst#uploading-to-anacondaorg

**Comment by msiemens** [comment]
Hey @richardotis, it's great to hear that TinyDB gets used on Anaconda. I haven't worked with it yet, but couldn't you just rely on the PyPI package? Or does Anaconda have its own package management mechanism?

**Comment by richardotis** [comment]
Anaconda has its own package management system called conda. It's possible to just use pip, but it doesn't work with the dependency tracking of other packages. conda also makes it possible to uninstall packages easily.

The hardest part is writing a recipe file for building the conda package, but since tinydb is pure Python it's pretty easy. Here's one I wrote for the autograd package recently: https://github.com/HIPS/autograd/blob/818cbb7b6ef0f810b34a8fe658ed42f0821010f4/conda_recipe/conda.yaml

What I've been doing is building tinydb and hosting it in my own Anaconda channel, which works fine for me except it's bad for users: they can't guarantee the package is up-to-date, legitimate or that it's versioned correctly. I'd prefer for all of my library's dependencies to come directly from their project maintainers.

**Comment by msiemens** [comment]
TinyDB now is an official package on conda-forge (see conda-forge/staged-recipes#814 for details).
