### ISSUE TITLE
tinydb.Query does not exist?

### ISSUE THREAD

**Issue by JCPQ** [msiemens/tinydb#75]
Sorry, I am totally new with this. My issue is probably related with the documentation. The simple example at readthedocs (http://tinydb.readthedocs.org/en/latest/getting-started.html) does not work for me. Importing Query does not work because it does not exist:

>>> from tinydb import TinyDB, Query
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Query'

Maybe there is a discrepancy between the getting started documentation which might be for version 3.0.0 and the version I use (2.4) but this is not clear to me from the changelog. 

If I want it to work I have to do this:

from tinydb import TinyDB, where
db = TinyDB('db.json')
db.insert({'type': 'apple', 'count': 7})
db.insert({'type': 'peach', 'count': 3})
fruit=where('type')
print(db.search(fruit=='peach'))

I am not sure whether that is the correct or efficient usage. I am Working under python 3.4 with tinydb 2.4 installed via the anaconda distribution of richardotis.

**Comment by msiemens** [comment]
The documentation at http://tinydb.readthedocs.org/en/latest/getting-started.html points to the latest version of TinyDB which is v3.0.0. In the lower right corner there is a small button you can press to select an earlier version. For v2.4. it would be http://tinydb.readthedocs.org/en/v2.4/getting-started.html.

**Comment by JCPQ** [comment]
That is a great feature! Thanks!
