### ISSUE TITLE
where in list

### ISSUE THREAD

**Issue by divanovGH** [msiemens/tinydb#77]
I can't do something like this:

db.search(where('field') in ['value1', 'value2', ...])

????????

**Comment by eugene-eeo** [comment]
At the moment there is no "contains" operator- there used to be one in 2.x. Regardless you can do it easily with:

```python
where('field').test(lambda v: v in ['value1', 'value2', ...])
```

**Comment by divanovGH** [comment]
Thanks!!!! )
