### ISSUE TITLE
Main process plus cron job with single db file

### ISSUE THREAD

**Issue by thinkxl** [msiemens/tinydb#84]
I have a CRUD application where the data needs to be delete within certain time based on the day entered, for that I'm using a cron job.

It is OK to have the main process and the external task accessing the file database without issues? 

I ask because it is referred in the documentation on "Why Not Use TinyDB?" that "You need advanced features like access from **multiple processes**, indexes, a HTTP server, relationships or similar."

This scenario counts as multiple processes?

**Comment by msiemens** [comment]
Yes, that counts indeed. This was already discussed in #72 with the conclusion that TinyDB's design doesn't guarantee meaningful behaviour in such cases but one could implement a storage that does the required locking and waiting on its own (see [this comment](https://github.com/msiemens/tinydb/issues/72#issuecomment-152716985)).

**Comment by thinkxl** [comment]
Got it, thanks for the quick response.
