### ISSUE TITLE
Lru cache refresh question

### ISSUE THREAD

**Issue by hwchen** [msiemens/tinydb#87]
Hello, I have a question about the Lru Cache:

https://github.com/msiemens/tinydb/blob/master/tinydb/utils.py#L36

Should the `refresh()` method only append a value only if it already existed and was removed? For example, in when `refresh()` is called in `get()`, I think it's possible that a wrong key will still result in that key being added to the lru.

**Comment by msiemens** [comment]
Yep, that's a bug! The tests actually didn't cover that case. I've now added  and pushed the corresponding tests. Thanks for reporting!

**Comment by hwchen** [comment]
Glad I could help!
