### ISSUE TITLE
Storage interface to receive element in context

### ISSUE THREAD

**Issue by fictorial** [msiemens/tinydb#90]
What are your thoughts on passing the element from the write context (e.g. Table's insert) to the storage instead of all the data.  This would allow storages that don't have to write all of the data every time any one (or a few) elements are created/modified/deleted.

BTW, you really nailed the API in this project. Nice and simple.

**Comment by msiemens** [comment]
> BTW, you really nailed the API in this project. Nice and simple.

That's a nice thing to hear. Thank you!

> What are your thoughts on passing the element from the write context (e.g. Table's insert) to the storage instead of all the data. This would allow storages that don't have to write all of the data every time any one (or a few) elements are created/modified/deleted.

You mean that the storage is responsible for updating the corresponding element in the internal data structure? As I think about it, it looks like this: basically we have stream-based storages (e.g. which use files) vs storages with random access (e.g. MemoryStorage) which by their nature need different approaches: pass the whole data set for stream-based storages and pass only the changes for random access storages.

For example: say we only pass the modified/deleted elements to the storage. In this case, if you use a stream-based storage like JSONStorage you'll have to store all data in-memory (whereas before it would only consume memory for the whole dataset temporarily) or re-read the file on every write operation increasing I/O load. On the other hand, if using a random access storage (like the MemoryStorage) with the current approach, the storage has to write the whole database even if only parts of it changed.

Personally I think that stream-based storages are more common than random access storages which would justify the current solution. But that's more a feeling than an informed opinion. What do you think about this?

What are your thoughts on this?

**Comment by fictorial** [comment]
The idea I had was to minimize any extra I/O.  Perhaps this isn't the intended DB for larger datasets as per its name but it would be nice to be able to write a file-per-object storage layer.

**Comment by eugene-eeo** [comment]
I think it's possible if you subclass the TinyDB class and implement some mechanism for signalling diffs so that the storage layer can commit those changes efficiently. Or you could just forgo schemaless design and use sqlite if you have really big data.

**Comment by fictorial** [comment]
There are many ways to skin a cat. The TinyDB feel is quite nice ;-)

**Comment by msiemens** [comment]
> The idea I had was to minimize any extra I/O. Perhaps this isn't the intended DB for larger datasets as per its name but it would be nice to be able to write a file-per-object storage layer.

Do you have something concrete in mind? Because in case of stream-based storages it would increase I/O or the average memory consumption.

**Comment by fictorial** [comment]
Given your terminology, I wanted a mix of random and stream interfaces. The overall dataset would be random access but each element would be stream (e.g. JSON).

As it is now, the entire data set is loaded from disk each time there's a query run (in the case of JSONStorage).  The query runs and the entire data set is written back out.  This is fine for tiny data sets (as per the name of the project, I get it!) but I don't see a reason why this could be refactored slightly to allow for larger data sets by keeping the full data set in memory and writing only elements that are mutated.

But, I keep getting this nagging feeling about this that I can just use a list comprehension and write when needed.

**Comment by msiemens** [comment]
> writing only elements that are mutated

I don't think this is possible with the JSONStorage as the length of an element might change which in turn may clobber the following element in the file we're writing to. Though I'd be glad to stand corrected if I'm wrong.

**Comment by msiemens** [comment]
Where a mixed interface would definitely make sense is a storage that stores each table in a separate JSON file for example.

> I don't see a reason why this could be refactored slightly to allow for larger data sets by keeping the full data set in memory and writing only elements that are mutated.

I guess the argument here is that in some hypothetical project it may be desired to not have the full data set in memory for longer periods of time. Altough if that's the case, the user would probably have outgrown TinyDB anyways.

With that in mind I'd at least want to try out the interface you've proposed. The big question of couse is how to integrate that into the current API if the new approach turns out better than the current one. The major hurdle is that breaking the current API would require a new major release. Maybe we could do some magic with custom table classes instead...

> But, I keep getting this nagging feeling about this that I can just use a list comprehension and write when needed.

Could you give an example of what you have in mind?

**Comment by msiemens** [comment]
Just for reference (mostly for myself), the tradeoffs I've outlined before as a table:

|                      | Block based interface                                 | Stream based interface                                     |
|----------------------|-------------------------------------------------------|------------------------------------------------------------|
| Block based storage  | *Best case*                                           | Has to write the whole dataset instead of the changes only |
| Stream based storage | Keep all data in memory OR re-read before every write | *Best case*                                                |

- Stream based storage: JSONStorage
- Block based storage: MemoryStorage
- Stream based interface: current approach
- Block based interface: proposal

**Comment by msiemens** [comment]
@eugene-eeo What are your thoughts on the tradeoffs between a stream based interface vs. a block based interface as per my last comment?

**Comment by eugene-eeo** [comment]
For simplicity and familiarity Stream based interfaces are good. However for larger datasets perhaps a compromise can be reached between simplicity and performance by standing on the shoulders of something like [BerkeleyDB](https://pypi.python.org/pypi/bsddb3/6.1.1) which will address two issues:

 - Parallel writes/modifications to the data
 - Having to rewrite the entire dataset when one single element is changed
 - Transactions! :heart_eyes: 

A plus point is that it is already battle tested in terms of performance. To the best of my knowledge BerkeleyDB is relatively efficient in terms of modifications, and being a key-value database it already fits TinyDB quite well.

This will really make TinyDB more suitable for bigger datasets and combined with the nice API that it already provides will pack quite a punch.

**Comment by msiemens** [comment]
> However for larger datasets perhaps a compromise can be reached between simplicity and performance by standing on the shoulders of something like BerkeleyDB

Do you mean rewriting TinyDB to be backed by BerkleyDB by default or just adding a new storage?

**Comment by eugene-eeo** [comment]
Adding a new storage as a plugin would be the best (IMHO) way to approach this.

**Comment by msiemens** [comment]
Thinking about that topic, I believe if I wrote TinyDB from scratch, I'd propably go with a block based or some kind of hybrid approach. But given the state we're in right now, I think the benefits of keeping the interfaces for storages is a greater benefit for the project than changing the way storages work quite fundamentally for -- in some cases -- improved performance.

Re. BerkleyDB: That would an interesting experiment for sure, but nothing I can focus on in foreseeable future.
