### ISSUE TITLE
JSON gets corrupted when used between multiple threads

### ISSUE THREAD

**Issue by PrashntS** [msiemens/tinydb#91]
In one particular implementation that was depended on network IO, and was multithreaded using a task queue manager (Huey), the JSON database gets corrupted after every few minutes. I suspect it could be because of multiple threads trying to use the file handles and that possibly caused a race condition.
Is this a known limitation, or a bug? Probably TinyDB wasn't built with this in mind - and it makes sense if it is indeed the case since it IS a joy to use tinydb for simple persistence in throw-away codes. Am I missing something?
Thanks!

**Comment by eugene-eeo** [comment]
As far as I understand the code, yes, TinyDB is built with this limitation in mind. For reference, issue #72 also shows previous discussion on the topic of multiple dbs and concurrent writes. Your current best bet is to put all writes/messages to the DB in a queue and execute them on a dedicated DB thread.

**Comment by divanovGH** [comment]
What about the tinyrecord for solving this problem?

https://github.com/eugene-eeo/tinyrecord

**Comment by eugene-eeo** [comment]
Tinyrecord **does not** provide multi-process concurrent writes. However you can do writes in parallel from [multiple threads](https://github.com/eugene-eeo/tinyrecord/blob/master/tinyrecord/transaction.py#L83).

**Comment by PrashntS** [comment]
I think it makes sense to NOT fix this or call it a bug. Tinydb really is nice and cute for not-too-complex usage. If one needs more complexity perhaps MongoDB or ZeoDB is more suited for the task.

What do you people think about it? Although I would want the docs to have something of this sort so others won't have to try.

**Comment by eugene-eeo** [comment]
That would be up to @msiemens.

**Comment by msiemens** [comment]
> If one needs more complexity perhaps MongoDB or ZeoDB is more suited for the task.

I totally agree. There a number of jobs where TinyDB just is not the right tool. Concurrent access would be one although using the TinyRecord extension can alleviate this in case of threads.

> What do you people think about it? Although I would want the docs to have something of this sort so others won't have to try.

Currently the docs include this snippet:

> * You need advanced features like access from multiple processes, indexes, a HTTP server, relationships or similar.

I think this should be clarified and maybe split into a sublist. Something like this:

> * You need advanced features like:
>     * access from multiple processes or threads
>     * creating indixes for tables
>     * a HTTP server
>     * managing relationships between tables

Would that be better?

**Comment by PrashntS** [comment]
Yes, this is certainly better and to the point.

Also, have you looked into the soft size limit upto which there's no impact on the performance? I suppose that could also be useful to mention in the Docs.

**Comment by msiemens** [comment]
> Yes, this is certainly better and to the point.

Okay, I've updated this in 8b484cc7f56508f818b9fd141985c1c371e76400.

> Also, have you looked into the soft size limit upto which there's no impact on the performance? I suppose that could also be useful to mention in the Docs.

I find that somewhat hard to provide numbers on that without a point of reference. If you have a lot of element in the DB and you do a search, it may turn out to be a bottleneck as searching does a linear scan of the whole dataset. But that really depends on the application, I guess...

**Comment by msiemens** [comment]
As I think about it, I'd say I've designed TinyDB to have a nice API, not to be fast :smile:

**Comment by PrashntS** [comment]
And you've done it pretty well, I must say!
I suppose we could close this issue now, since this resolves it.

**Comment by msiemens** [comment]
> And you've done it pretty well, I must say!

That's nice to hear, thanks!
