### ISSUE TITLE
Cannot keep reference to table without keeping a reference to the database

### ISSUE THREAD

**Issue by michou** [msiemens/tinydb#92]
This throws a `ValueError: I/O operation on closed file.`:

```python
db = TinyDB('./db.json').table('foo')
db.insert({'something': 'else'})
db.insert({'int': 13})
print(db.search(Query()['int'] == 13))
print(db.all())
```

while this works:

```python
db = TinyDB('./db.json')
table = db.table('foo')
table.insert({'something': 'else'})
table.insert({'int': 13})
print(table.search(Query()['int'] == 13))
print(table.all())
```

It took me and @alexghr a couple of hours to figure out it had to do with the garbage collector deleting the `db` object (and thus closing the database).
Would it make sense to have the documentation explicitly state that losing the reference to the database will mess up your tables?

**Comment by michou** [comment]
I found it especially confusing because the documents state that _TinyDB uses a table named `_default` as default table. All operations on the database object (like `db.insert(...)`) operate on this table._ The way I read it, this meant operations on the database object were identical in behavior with operations on a table object. Which is not the case.

**Comment by msiemens** [comment]
> Would it make sense to have the documentation explicitly state that losing the reference to the database will mess up your tables?

Actually I count that as a bug. If nothing comes up, a bugfix release should be published by the end of the week.

**Bug Background**

The offending lines are [`tinydb/database.py:131-133`](https://github.com/msiemens/tinydb/blob/8b484cc7f56508f818b9fd141985c1c371e76400/tinydb/database.py#L131-L133):

```python
def __del__(self):
    if self._opened is True:
        self.close()
```

Here the storage is closed when the TinyDB object gets garbage collected. As you've pointed out, after running `TinyDB('./db.json').table('foo')` there are no more references to the TinyDB object. Thus, the underlying storage gets closed and future access fails.

**Comment by msiemens** [comment]
TinyDB v3.1.3 which includes the fix is now released :)

**Comment by michou** [comment]
Yay!
