### ISSUE TITLE
Query.any fails with nested lists

### ISSUE THREAD

**Issue by robintw** [msiemens/tinydb#95]
I've got the following TinyDB query in my code:

```
results = db.search(where('outputs').any(filename))
```
which has worked fine until I upgraded to the latest release. I'm trying to find records where any of the items in the `outputs` list are equal to the given filename.

As far I as can see from the Release Notes and the version-number change, no breaking API changes were introduced. Do you have any idea what's happening here?

**Comment by msiemens** [comment]
How exactly does this code fail? Does it raise an exception? Does it return an unexpected value?

**Comment by robintw** [comment]
Sorry, no idea how I managed to do that - I had the stack trace copied to the clipboard and everything! Here it is:

```
Traceback (most recent call last):
  File "./recipy-cmd", line 5, in <module>
    main()
  File "/Users/robin/code/recipy/recipyCmd/recipycmd.py", line 107, in main
    search(args)
  File "/Users/robin/code/recipy/recipyCmd/recipycmd.py", line 278, in search
    results = db.search(where('outputs').any(os.path.abspath(filename)))
  File "/opt/anaconda3/lib/python3.4/site-packages/tinydb/database.py", line 381, in search
    elements = [element for element in self.all() if cond(element)]
  File "/opt/anaconda3/lib/python3.4/site-packages/tinydb/database.py", line 381, in <listcomp>
    elements = [element for element in self.all() if cond(element)]
  File "/opt/anaconda3/lib/python3.4/site-packages/tinydb/queries.py", line 45, in __call__
    return self.test(value)
  File "/opt/anaconda3/lib/python3.4/site-packages/tinydb/queries.py", line 114, in impl
    return test(value)
  File "/opt/anaconda3/lib/python3.4/site-packages/tinydb/queries.py", line 188, in <lambda>
    return self._generate_test(lambda value: _cmp(value),
  File "/opt/anaconda3/lib/python3.4/site-packages/tinydb/queries.py", line 186, in _cmp
    return is_sequence(value) and any(e in cond for e in value)
  File "/opt/anaconda3/lib/python3.4/site-packages/tinydb/queries.py", line 186, in <genexpr>
    return is_sequence(value) and any(e in cond for e in value)
TypeError: 'in <string>' requires string as left operand, not list
```

**Comment by msiemens** [comment]
Interesting, I can't reproduce that. What's the return value of `os.path.abspath(filename)` on recipycmd.py, line 278?

**Comment by msiemens** [comment]
Wait, actually I think the more interesting value is the database entry that is being compared to. Could you give an example db entry?

**Comment by msiemens** [comment]
Sorry for the buzz, but I just reproduced this problem. Did the database by any chance include elements with nested lists on the `outputs` field? Like this:

```python
from tinydb import where

query = where('outputs').any('foo')
print(query({'outputs': [['foo'], 'bar']}))
```

That does result in an exception like yours.

**Comment by robintw** [comment]
Ah yes - thank you! Some of my `outputs` do have nested lists - that makes sense.

Is there an easy way to deal with nested lists when querying? (Some sort of 'nested any' command that searches in all nested lists?) I guess the alternative is to write functions and use them with `test` - but I don't know if that'd be less efficient?

**Comment by eugene-eeo** [comment]
A nicer way to deal with nested lists is to write a function, and use variable unpacking in Python. If you're on Python 3 then you have even more convenience:

```python
(a, b), *c = [(1,2), 3, 4]
assert a == 1
assert b == 2
assert c == [3, 4]
```

Now of course, this depends on the schema of your data and whether all of your lists conform to a certain pattern. Else you would have to do some ugly if-else checks.

**Comment by msiemens** [comment]
> Is there an easy way to deal with nested lists when querying? (Some sort of 'nested any' command that searches in all nested lists?) I guess the alternative is to write functions and use them with test - but I don't know if that'd be less efficient?

From the performance side the difference should be neglible as it's just one function call more. I think a custom test function is really the way to go there as the Query API can't cover every single case. The idea @eugene-eeo proposed can be a good starting point for the test function.

**Comment by msiemens** [comment]
As far as I can see, this issue has been resolved. Please reopen if that's not the case.
