### ISSUE TITLE
Proper way to transform retrieved elements?

### ISSUE THREAD

**Issue by wmayner** [msiemens/tinydb#97]
Hi,

Thank you for this excellent little library! 

I'd like to automatically call a transform function on elements whenever they're retrieved from the database (turning the JSON elements back into rich Python objects). is there a preferred way of doing this? My first thought was to extend `Table`, but it seems like it would require to some code duplication to satisfy the API (not at all terrible, but not too elegant either).

Cheers,
Will

**Comment by wmayner** [comment]
Never mind—extending `Table` is totally painless. If there's an even better way, let me know, but I'll close this :smile:

**Comment by msiemens** [comment]
I guess exteding the Table class is the way to go here :+1: If you need something fancier, you'd have to write some kind of ORM for TinyDB (there seems to be [RutledgePaulV/tiny-orm](https://github.com/RutledgePaulV/tiny-orm), but I haven't used it).

**Comment by wmayner** [comment]
Yup. The only thing I've run into is that since `all` is used internally by other functions, I can't trivially extend it by transforming the result of the `super()` call, as I did with `get` and `search`—not a big deal though.
