### ISSUE TITLE
Need a way to delete a table

### ISSUE THREAD

**Issue by deemson** [msiemens/tinydb#99]
It would be nice to see this feature in TinyDB. I will gladly assist with it if you tell me where does it belong in the code.

**Comment by eugene-eeo** [comment]
I think what you're concerned with is that it's a slightly hairy problem though, to delete say, "table-one", do you do:

```python
>>> tbl = db.table('table-one')
>>> tbl.delete()
```

(i.e. the table knows how to delete itself), or do you do:

```python
>>> db.delete('table-one')
```

With that being said I think the latter is the better option, as it shows that the DB "owns" the tables, and is essentially a glorified dict of table-names to tables. *You won't expect that an entry in a dictionary to know how to delete itself, would you?*

**Comment by deemson** [comment]
```python
>>> db.delete('table-one')
```

this looks nice

**Comment by msiemens** [comment]
`db.delete` looks ambiguous to me. Maybe `db.purge_table('table-one')` would be an option. We already have `db.purge_tables()` which removes all tables, so `purge_table` seems intuitive. What do you think?

**Comment by eugene-eeo** [comment]
:+1: for `db.purge_table`

**Comment by deemson** [comment]
After learning the code, I see that there is no way to implement table deletion without adding a delete method to storage classes. Is this acceptable?

**Comment by msiemens** [comment]
> I see that there is no way to implement table deletion without adding a delete method to storage classes

Why that? Couldn't `StorageProxy` handle that? I think it would be something like

```
data = self._storage.read() or {}
del data[self.table_name]
self._storage.write(data)
```

Of course you'd also have to update the table cache to account for the deletion, as far as I can see

**Comment by msiemens** [comment]
@deemson Are you on this? I'd like the next update of TinyDB to include this change too. No hurry, just FYI.

**Comment by deemson** [comment]
Yep, I'm on this, no worries.

**Comment by deemson** [comment]
# #100
